export type Product = {
  slug: string; name: string; brand: string; category: string; image: string;
  gallery: string[]; label: string; summary: string; specs: [string, string][];
  features: string[]; page: number;
  subcategories?: string[];
  categoryIds?: string[];
  tags?: string[];
};

export const categories = [
  { id: 'forestry', name: 'Forestry & Wildlife', short: 'Into the wild.', subtitle: 'Observe without disturbing.', mission: 'Wildlife monitoring, habitat research and remote observation.', image: 'forest', code: 'BIO / 01' },
  { id: 'geology', name: 'Geological Products', short: 'Read the earth.', subtitle: 'Every layer tells a story.', mission: 'Map structures, measure bearings and document the ground beneath your feet.', image: 'geology', code: 'GEO / 02' },
  { id: 'surveying', name: 'Surveying & DGPS', short: 'Every point matters.', subtitle: 'Find your position. Define your ground.', mission: 'Field positioning and navigation. Talk to our team about DGPS and survey-specific requirements.', image: 'surveying', code: 'GNSS / 03' },
  { id: 'navigation', name: 'Mapping & Navigation', short: 'Know your next move.', subtitle: 'Confidence in every coordinate.', mission: 'Handheld GPS and dependable navigation instruments for unfamiliar ground.', image: 'navigation', code: 'NAV / 04' },
  { id: 'thermal', name: 'Thermal & Night Vision', short: 'Beyond the visible.', subtitle: 'A different way to see.', mission: 'Reveal heat signatures and observe in low light with dedicated field imaging products.', image: 'thermal', code: 'IR / 05' },
  { id: 'optics', name: 'Optics', short: 'Bring the distant closer.', subtitle: 'Clarity changes everything.', mission: 'High-definition binoculars and observation optics for detail at a distance.', image: 'optics', code: 'OPT / 06' },
  { id: 'inspection', name: 'Inspection / Borescope Systems', short: 'Reach the unseen.', subtitle: 'Answers in the smallest spaces.', mission: 'Articulating inspection cameras for engines, machinery and difficult-to-access spaces.', image: 'inspection', code: 'INS / 07' },
  { id: 'computing', name: 'Rugged Computing', short: 'Work beyond the office.', subtitle: 'Your field is your workspace.', mission: 'Rugged mobile computing for collecting, managing and using data on location.', image: 'computing', code: 'RUG / 08' },
  { id: 'communication', name: 'Field Communication', short: 'Keep your team connected.', subtitle: 'A clear line in challenging terrain.', mission: 'Portable radio products for coordinated operations in the field.', image: 'communication', code: 'COM / 09' },
  { id: 'defense', name: 'Defense & Paramilitary', short: 'Stay field ready.', subtitle: 'Awareness in every condition.', mission: 'Explore existing imaging, navigation, optics, communication and computing equipment for demanding field operations.', image: 'thermal', code: 'FLD / 10' },
  { id: 'mining', name: 'Mining & Geology', short: 'Read the terrain.', subtitle: 'Measure the ground.', mission: 'Explore existing geological instruments, mapping equipment, inspection tools and rugged computing for field work.', image: 'geology', code: 'GEO / 11' },
] as const;

export const products: Product[] = [
  // --- Existing Field Technology Products (Preserved & Cleaned of Legacy Subcategories) ---
  { slug:'vortex-viper-hd',name:'Viper® HD',brand:'Vortex Optics',category:'optics',image:'viper',gallery:['viper','viper-front'],label:'HD BINOCULARS',summary:'An HD optical system, rugged rubber armor and a comfortable field harness. A clear view of the details that matter.',specs:[['Available configurations','8×42 / 10×50 / 12×50'],['Optical system','High definition'],['Lens coating','XR™ fully multi-coated'],['Protection','ArmorTek®'],['Carry system','GlassPak harness included']],features:['HD glass for resolution and color fidelity','Phase-corrected roof prisms for contrast','Rubber armor for a secure grip','GlassPak chest harness for comfortable field carry'],page:5,subcategories:['defense-optics'],categoryIds:['optics','defense'],tags:['Binoculars'] },
  { slug:'garmin-gpsmap-65s',name:'Handheld GPS (GPSMAP® 65s)',brand:'Garmin',category:'navigation',image:'gpsmap',gallery:['gpsmap'],label:'MULTI-BAND GPS',summary:'Find your way in challenging environments with multi-band positioning, expanded satellite support and a sunlight-readable color display.',specs:[['Display','2.6-inch color'],['Positioning','Multi-band GNSS'],['Battery life','Up to 16 hours in GPS mode'],['Navigation','Built-in navigation sensors'],['Planning','Garmin Explore compatibility']],features:['Multi-band technology for challenging locations','Sunlight-readable color display','Built-in navigation sensors','Plan and organize with the Garmin Explore app'],page:12,subcategories:['gps-survey-mapping-products','defense-navigation','defense-field-operations','mining-field-mapping','mining-mapping','mining-distance'],categoryIds:['navigation','defense','mining','surveying'],tags:['GPS/GNSS Devices','GPS','Handheld GPS'] },
  { slug:'hikmicro-lynx-lh25',name:'LYNX LH25 2.0',brand:'HIKMICRO',category:'thermal',image:'lynx',gallery:['lynx','lynx-side'],label:'THERMAL MONOCULAR',summary:'A compact thermal monocular that reveals subtle heat signatures, with a sensitive detector and a detailed OLED view.',specs:[['Detector resolution','384 × 288'],['Lens','25 mm, F1.0'],['Thermal sensitivity','NETD <20 mK'],['Detection range','Up to 1,200 m'],['Weight','275 g'],['Battery life','Up to 6.5 hours']],features:['12 μm detector with high thermal sensitivity','1024 × 768 OLED display','Replaceable rechargeable Li-ion battery','Compact and ergonomic field design'],page:40,subcategories:['defense-thermal','defense-surveillance'],categoryIds:['thermal','defense'],tags:['Thermal Cameras','Thermal Monoculars'] },
  { slug:'browning-strike-force-pro-dcl',name:'Strike Force Pro DCL',brand:'Browning',category:'forestry',image:'browning',gallery:['browning'],label:'WILDLIFE TRAIL CAMERA',summary:'Dual camera lens technology captures the field by day and night, with a fast trigger for fleeting wildlife encounters.',specs:[['Image resolution','26 megapixels'],['Trigger speed','0.15 seconds'],['Flash range','Up to 130 ft'],['Viewing screen','1.5-inch color'],['Lens system','Dual camera lens technology']],features:['Separate lens technology optimized for day and night','Fast trigger for wildlife monitoring','On-camera color viewing screen','Long-range flash capability'],page:21,subcategories:['defense-surveillance'],categoryIds:['forestry','defense'],tags:['Camera Traps'] },
  { slug:'brunton-geolite',name:'Geo Lite Transit',brand:'Brunton',category:'geology',image:'geolite-open',gallery:['geolite-open','geolite'],label:'GEOLOGICAL COMPASS',summary:'A baseplate compass with transit-style measurement, designed for bearings, strike and dip work in the field.',specs:[['Azimuth resolution','2°'],['Clinometer resolution','5°'],['Magnet','Brunton EverNorth'],['Measurement','Strike / dip / dip azimuth'],['Map tools','Protractor and magnifier']],features:['Transit-style direct-read azimuth system','Hinge clinometer for dip measurements','Bubble level for accurate strike measurement','Integrated protractor for plotting field data'],page:27,subcategories:['geological-field-mapping','mining-field-mapping','mining-survey','mining-compasses'],categoryIds:['geology','mining'],tags:['Forestry Compasses','Geological Compasses / Pocket Transits'] },
  { slug:'panasonic-toughbook',name:'TOUGHBOOK FZ-55',brand:'Panasonic Toughbook',category:'computing',image:'toughbook',gallery:['toughbook'],label:'RUGGED FIELD COMPUTING',summary:'A modular laptop platform for demanding mobile work. Ask our team to configure a TOUGHBOOK around your field applications.',specs:[['Product family','Panasonic TOUGHBOOK'],['Catalogue model','FZ-55'],['Form factor','Rugged laptop'],['Configuration','Confirmed with your quotation']],features:['Built for mobile field workflows','Flexible configuration options','Suitable for field data collection and review','Project-specific configuration support'],page:47,subcategories:['defense-rugged','defense-field-operations','mining-rugged'],categoryIds:['computing','defense','mining'],tags:['Rugged Tablets'] },
  { slug:'vortex-diamondback-hd',name:'Diamondback® HD',brand:'Vortex Optics',category:'optics',image:'diamondback',gallery:['diamondback','diamondback-side'],label:'HD BINOCULARS',summary:'Rugged observation optics with HD glass, protective lens coatings and a ready-to-deploy harness.',specs:[['Available configurations','8×42 / 10×50 / 10×42'],['Optical system','High definition'],['Lenses','Fully multi-coated'],['Protection','ArmorTek® coating'],['Carry system','GlassPak harness included']],features:['Phase correction for enhanced resolution','Rubber armor for a non-slip grip','Scratch-resistant exterior lens coating','Shock-resistant construction'],page:4,subcategories:['defense-optics'],categoryIds:['optics','defense'],tags:['Binoculars'] },
  { slug:'garmin-montana-700',name:'Montana® 700',brand:'Garmin',category:'navigation',image:'montana',gallery:['montana'],label:'TOUCHSCREEN GPS',summary:'Large-format navigation for journeys on foot or by vehicle, combining a 5-inch touchscreen with outdoor navigation sensors.',specs:[['Display','5-inch touchscreen'],['Positioning','Multiple GNSS networks'],['Battery life','18+ hours in GPS mode'],['Navigation sensors','Altimeter, barometer, compass'],['Mapping','Routable roads and trails']],features:['Large touchscreen for clear map viewing','Rugged construction for outdoor navigation','ABC sensors for awareness in the field','Mapping support for roads and trails'],page:15,subcategories:['defense-navigation','defense-field-operations','mining-field-mapping','mining-mapping','mining-distance'],categoryIds:['navigation','defense','mining'],tags:['GPS/GNSS Devices','GPS'] },
  { slug:'ralcam-h408b',name:'H408B Borescope',brand:'Ralcam',category:'inspection',image:'ralcam',gallery:['ralcam'],label:'ARTICULATING INSPECTION',summary:'Inspect confined spaces with an articulating camera and a dedicated display, built for automotive and machinery inspection.',specs:[['Display','4.3-inch'],['Camera resolution','1920 × 1080'],['Probe diameter','8.5 mm'],['Battery','Replaceable 2,600 mAh'],['Lighting','10 adjustable LEDs']],features:['Articulating lens for difficult viewing angles','Capture images and video','High-temperature protection','Dedicated screen for on-site inspections'],page:17,subcategories:['mining-inspection'],categoryIds:['inspection','mining'] },
  { slug:'brutforce-field-radio',name:'Field Radio',brand:'Brutforce',category:'communication',image:'radio',gallery:['radio','radio-side'],label:'PORTABLE COMMUNICATION',summary:'Portable two-way communication to keep field teams in touch. Confirm the right radio configuration for your operating location with our team.',specs:[['Frequency range','446–446.2 MHz'],['Channels','16'],['Battery','2,600 mAh Li-ion'],['Charging port','Micro-USB'],['Operating temperature','−25°C to 55°C']],features:['16 channels for team coordination','Rechargeable Li-ion battery','Portable format for field carry','Simple controls and clear audio'],page:34,subcategories:['defense-communication','defense-field-operations'],categoryIds:['communication','defense'],tags:['Field Radios'] },
  { slug:'brunton-compro-transit',name:'Survey Compass (ComPro Transit F-5008)',brand:'Brunton',category:'geology',image:'compro',gallery:['compro'],label:'COMPOSITE POCKET TRANSIT',summary:'Traditional transit measurement in a lightweight composite body, with sighting tools and a precision magnetic system.',specs:[['Model','F-5008'],['Body','Lightweight composite'],['Magnet','Precision NdFeB disc'],['Needle settling','Induction dampening'],['Measurements','Bearings and vertical angles']],features:['Lightweight composite lid and base','Mirror for sighting and angle measurement','Short and long sights','Magnet designed to resist demagnetization'],page:30,subcategories:['gps-survey-mapping-products','geological-field-mapping','mining-field-mapping','mining-survey','mining-compasses'],categoryIds:['geology','mining','surveying'],tags:['Survey Compass','Forestry Compasses','Geological Compasses / Pocket Transits'] },
  { slug:'brunton-f-5012-axis',name:'F-5012 Axis Compass',brand:'Brunton',category:'geology',image:'geolite',gallery:['geolite','geolite-open'],label:'AXIS BASE PLATE COMPASS',summary:'A baseplate compass for strike, dip and bearing work, with direct-read azimuth, clinometer and Brunton EverNorth magnetic system.',specs:[['Azimuth resolution','2°'],['Clinometer resolution','5°'],['Magnet','Brunton EverNorth'],['Body','Durable ABS'],['Sighting','Direct-read sighting system']],features:['Direct-read azimuth and bearing system','Hinge clinometer for strike and dip measurement','Bubble level for accurate horizontal alignment','Integrated map magnifier and protractor'],page:27,subcategories:['geological-field-mapping','mining-field-mapping','mining-survey','mining-compasses'],categoryIds:['geology','mining'],tags:['Geological Compasses / Pocket Transits'] },
  { slug:'minox-nvd-650',name:'NVD 650',brand:'MINOX',category:'thermal',image:'minox',gallery:['minox','minox-back'],label:'DIGITAL NIGHT VISION',summary:'A digital monocular with an IR emitter and recording capability for observation in low-light field conditions.',specs:[['Optical magnification','6×'],['Digital magnification','5×'],['IR wavelength','850 nm'],['IR range','Up to 350 m'],['Use','Day and night']],features:['Built-in IR emitter','Night recording functionality','Rail for additional IR illumination','Daytime use supported'],page:45,subcategories:['defense-night','defense-surveillance'],categoryIds:['thermal','defense'],tags:['Night Vision Devices'] },
  { slug:'suunto-mc2',name:'MC-2 Mirror Compass',brand:'Suunto',category:'navigation',image:'suunto',gallery:['suunto'],label:'PRECISION NAVIGATION',summary:'A sighting compass with a mirror, clinometer and adjustable declination correction for considered route finding.',specs:[['Needle','Jewel-bearing steel'],['Capsule','Liquid-filled'],['Declination','Adjustable correction'],['Measurement','Sighting and clinometer'],['Variant','Confirm hemisphere and scale']],features:['Sighting mirror and notch for bearings','Luminescent markings for low light','Baseplate with magnifying lens','Detachable snap-lock lanyard'],page:41,subcategories:['defense-navigation','defense-field-operations'],categoryIds:['navigation','defense'],tags:['Compasses','Forestry Compasses'] },
  { slug:'audiomoth',name:'AudioMoth',brand:'Open Acoustic Devices',category:'forestry',image:'audiomoth',gallery:['audiomoth','audiomoth-case'],label:'ACOUSTIC MONITORING',summary:'A compact full-spectrum acoustic logger for listening to the natural world, with an optional protective field case.',specs:[['Sample rate','Up to 384 kHz'],['Processor','EFM32 Gecko'],['Microphone','Analog MEMS'],['Protective option','IPX7 waterproof case']],features:['Full-spectrum acoustic logging','Compact field-deployment format','Protective case with compression O-ring','Case strap for straightforward installation'],page:44,tags:['Acoustic Monitoring Devices'] },
  { slug:'hikmicro-e20-plus',name:'E20 Plus',brand:'HIKMICRO',category:'thermal',image:'e20',gallery:['e20','e20-side'],label:'SMARTPHONE THERMAL CAMERA',summary:'A lightweight thermal accessory for compatible Android phones, with USB-C connection and HIKMICRO Sight app support.',specs:[['Connection','USB Type-C'],['Power consumption','360 mW'],['Weight','26 g'],['Operating temperature','−10°C to 50°C'],['Protection level','IP40']],features:['Compact thermal module for mobile observation','Powered through the connected device','HIKMICRO Sight app compatibility','Lightweight 26 g design'],page:39,tags:['Thermal Cameras'] },

  // =========================================================================
  // 1. FOREST MEASUREMENT & INVENTORY (Subcategory ID: forest-measurement-inventory)
  // =========================================================================
  {
    slug: 'diameter-tape-dbh-tape',
    name: 'Diameter Tape / DBH Tape',
    brand: 'AFFORDA',
    category: 'forestry',
    image: 'placeholder',
    gallery: ['placeholder'],
    label: 'FORESTRY MEASUREMENT',
    summary: 'Specialized measuring tape for tree diameter and circumference measurements in forestry applications.',
    specs: [['Specifications', 'Available on request']],
    features: ['Direct reading scale for tree diameter measurement', 'Built for field use in forest inventory', 'Suitable for timber cruising and forestry applications'],
    page: 1,
    subcategories: ['forest-measurement-inventory'],
    categoryIds: ['forestry'],
    tags: ['Forest Measurement & Inventory', 'Diameter Tape']
  },
  {
    slug: 'digital-tree-caliper',
    name: 'Digital Tree Caliper',
    brand: 'AFFORDA',
    category: 'forestry',
    image: 'placeholder',
    gallery: ['placeholder'],
    label: 'FORESTRY CALIPER',
    summary: 'Electronic caliper for measuring tree diameters and log dimensions in forest inventory.',
    specs: [['Specifications', 'Available on request']],
    features: ['Digital display for reading diameter measurements', 'Designed for timber cruising and forest inventory', 'Suitable for outdoor field conditions'],
    page: 1,
    subcategories: ['forest-measurement-inventory'],
    categoryIds: ['forestry'],
    tags: ['Forest Measurement & Inventory', 'Tree Calipers']
  },
  {
    slug: 'wheeler-caliper',
    name: 'Wheeler Caliper',
    brand: 'AFFORDA',
    category: 'forestry',
    image: 'placeholder',
    gallery: ['placeholder'],
    label: 'OPTICAL DENDROMETER',
    summary: 'Optical dendrometer instrument for measuring upper-stem tree diameters from the ground.',
    specs: [['Specifications', 'Available on request']],
    features: ['Measures upper-stem diameters without climbing', 'Optical sighting scale for standing trees', 'Compact instrument designed for field forestry'],
    page: 1,
    subcategories: ['forest-measurement-inventory'],
    categoryIds: ['forestry'],
    tags: ['Forest Measurement & Inventory']
  },
  {
    slug: 'tree-height-meter',
    name: 'Tree Height Meter',
    brand: 'AFFORDA',
    category: 'forestry',
    image: 'placeholder',
    gallery: ['placeholder'],
    label: 'HEIGHT MEASUREMENT',
    summary: 'Field instrument for measuring tree heights and vertical angles in forest stands.',
    specs: [['Specifications', 'Available on request']],
    features: ['Designed for tree height determination in forest stands', 'Compact handheld unit for field use', 'Aids in forest inventory and mensuration'],
    page: 1,
    subcategories: ['forest-measurement-inventory'],
    categoryIds: ['forestry'],
    tags: ['Forest Measurement & Inventory', 'Height Meter']
  },
  {
    slug: 'clinometer',
    name: 'Clinometer',
    brand: 'AFFORDA',
    category: 'forestry',
    image: 'placeholder',
    gallery: ['placeholder'],
    label: 'SLOPE & HEIGHT SIGHTING',
    summary: 'Handheld instrument for measuring angles of slope, elevation, and tree heights.',
    specs: [['Specifications', 'Available on request']],
    features: ['Measures vertical angles and degrees of slope', 'Optical sighting for field readings', 'Compact handheld design for foresters and surveyors'],
    page: 1,
    subcategories: ['forest-measurement-inventory'],
    categoryIds: ['forestry'],
    tags: ['Forest Measurement & Inventory', 'Clinometer']
  },
  {
    slug: 'hypsometer',
    name: 'Hypsometer',
    brand: 'AFFORDA',
    category: 'forestry',
    image: 'placeholder',
    gallery: ['placeholder'],
    label: 'FORESTRY HYPSOMETER',
    summary: 'Forestry instrument used for measuring tree heights and elevations.',
    specs: [['Specifications', 'Available on request']],
    features: ['Calculates tree heights and inclination', 'Designed for field mensuration and stand evaluation', 'Portable format for timber cruisers'],
    page: 1,
    subcategories: ['forest-measurement-inventory'],
    categoryIds: ['forestry'],
    tags: ['Forest Measurement & Inventory', 'Hypsometer']
  },
  {
    slug: 'relaskop',
    name: 'Relaskop',
    brand: 'AFFORDA',
    category: 'forestry',
    image: 'placeholder',
    gallery: ['placeholder'],
    label: 'STAND CRUISE INSTRUMENT',
    summary: 'Optical instrument for forest inventory, basal area estimation, and tree measurement.',
    specs: [['Specifications', 'Available on request']],
    features: ['Multi-functional optical device for forest inventory', 'Used for basal area estimation and tree measurement', 'Field instrument for professional foresters'],
    page: 1,
    subcategories: ['forest-measurement-inventory'],
    categoryIds: ['forestry'],
    tags: ['Forest Measurement & Inventory', 'Relaskop']
  },
  {
    slug: 'wedge-prism',
    name: 'Wedge Prism',
    brand: 'AFFORDA',
    category: 'forestry',
    image: 'placeholder',
    gallery: ['placeholder'],
    label: 'VARIABLE RADIUS CRUISING',
    summary: 'Optical prism used for variable radius plot sampling and basal area estimation.',
    specs: [['Specifications', 'Available on request']],
    features: ['Used for point sampling and stand basal area determination', 'Compact optical tool for pocket carry', 'Essential tool for timber cruisers'],
    page: 1,
    subcategories: ['forest-measurement-inventory'],
    categoryIds: ['forestry'],
    tags: ['Forest Measurement & Inventory', 'Wedge Prism']
  },
  {
    slug: 'densiometer',
    name: 'Densiometer',
    brand: 'AFFORDA',
    category: 'forestry',
    image: 'placeholder',
    gallery: ['placeholder'],
    label: 'CANOPY COVER ESTIMATION',
    summary: 'Field instrument for estimating forest canopy cover and overstory density.',
    specs: [['Specifications', 'Available on request']],
    features: ['Estimates forest overstory coverage and canopy density', 'Handheld instrument for ecological and forestry surveys', 'Protective case for field transport'],
    page: 1,
    subcategories: ['forest-measurement-inventory'],
    categoryIds: ['forestry'],
    tags: ['Forest Measurement & Inventory', 'Densiometer']
  },
  {
    slug: 'bark-gauge',
    name: 'Bark Gauge',
    brand: 'AFFORDA',
    category: 'forestry',
    image: 'placeholder',
    gallery: ['placeholder'],
    label: 'BARK THICKNESS GAUGE',
    summary: 'Specialized hand tool for measuring tree bark thickness in forestry studies.',
    specs: [['Specifications', 'Available on request']],
    features: ['Direct penetration measurement for bark depth', 'Aids in wood volume and growth calculation', 'Durable hand tool for field foresters'],
    page: 1,
    subcategories: ['forest-measurement-inventory'],
    categoryIds: ['forestry'],
    tags: ['Forest Measurement & Inventory', 'Bark Gauge']
  },
  {
    slug: 'increment-borer',
    name: 'Increment Borer',
    brand: 'AFFORDA',
    category: 'forestry',
    image: 'placeholder',
    gallery: ['placeholder'],
    label: 'TREE CORE SAMPLER',
    summary: 'Specialized forestry tool for extracting wood core samples to assess tree growth and age.',
    specs: [['Specifications', 'Available on request']],
    features: ['Extracts core samples without felling the tree', 'Used for dendrochronology, growth, and sound wood assessment', 'Includes coring auger and extractor'],
    page: 1,
    subcategories: ['forest-measurement-inventory'],
    categoryIds: ['forestry'],
    tags: ['Forest Measurement & Inventory', 'Increment Borer']
  },
  {
    slug: 'tally-counter',
    name: 'Tally Counter',
    brand: 'AFFORDA',
    category: 'forestry',
    image: 'placeholder',
    gallery: ['placeholder'],
    label: 'FIELD COUNTING TOOL',
    summary: 'Handheld counter for timber cruising, stem counting, and field inventory work.',
    specs: [['Specifications', 'Available on request']],
    features: ['Pushbutton increment counting', 'Reset knob for clearing counts', 'Compact handheld design with finger ring'],
    page: 1,
    subcategories: ['forest-measurement-inventory'],
    categoryIds: ['forestry'],
    tags: ['Forest Measurement & Inventory', 'Tally Counter']
  },
  {
    slug: 'loggers-tape',
    name: 'Logger’s Tape',
    brand: 'AFFORDA',
    category: 'forestry',
    image: 'placeholder',
    gallery: ['placeholder'],
    label: 'TIMBER & LOG MEASURING',
    summary: 'Retractable measuring tape designed for log scaling and forestry field measurements.',
    specs: [['Specifications', 'Available on request']],
    features: ['Spring-rewind mechanism for field operation', 'Designed for log scaling and timber cruising', 'Belt clip for convenient field carry'],
    page: 1,
    subcategories: ['forest-measurement-inventory'],
    categoryIds: ['forestry'],
    tags: ['Forest Measurement & Inventory', 'Loggers Tape']
  },
  {
    slug: 'measuring-tape',
    name: 'Measuring Tape',
    brand: 'AFFORDA',
    category: 'forestry',
    image: 'placeholder',
    gallery: ['placeholder'],
    label: 'LONG REEL TAPE',
    summary: 'Field measuring tape for layout, plot establishment, and distance measurement.',
    specs: [['Specifications', 'Available on request']],
    features: ['Reel tape designed for forestry plot layout and transects', 'Manual rewind handle for quick retrieval', 'Durable housing for field survey work'],
    page: 1,
    subcategories: ['forest-measurement-inventory'],
    categoryIds: ['forestry'],
    tags: ['Forest Measurement & Inventory', 'Measuring Tape']
  },
  {
    slug: 'laser-rangefinder',
    name: 'Laser Rangefinder',
    brand: 'AFFORDA',
    category: 'forestry',
    image: 'placeholder',
    gallery: ['placeholder'],
    label: 'DISTANCE & HEIGHT MEASUREMENT',
    summary: 'Handheld rangefinder for measuring distances and heights in forestry and field surveying.',
    specs: [['Specifications', 'Available on request']],
    features: ['Measures line-of-sight distance and height angles', 'Handheld design for field mobility', 'Suitable for plot layout and forest survey work'],
    page: 1,
    subcategories: ['forest-measurement-inventory', 'gps-survey-mapping-products'],
    categoryIds: ['forestry', 'surveying'],
    tags: ['Forest Measurement & Inventory', 'Laser Rangefinder']
  },

  // =========================================================================
  // 2. GPS, SURVEY & MAPPING PRODUCTS (Subcategory ID: gps-survey-mapping-products)
  // =========================================================================
  {
    slug: 'professional-gnss-receiver',
    name: 'Professional GNSS Receiver',
    brand: 'AFFORDA',
    category: 'forestry',
    image: 'placeholder',
    gallery: ['placeholder'],
    label: 'GNSS SURVEY RECEIVER',
    summary: 'Field GNSS receiver for mapping, surveying, and position data collection.',
    specs: [['Specifications', 'Available on request']],
    features: ['Collects geospatial positioning data in the field', 'Designed for mapping and field survey workflows', 'Compatible with survey rods and field controllers'],
    page: 1,
    subcategories: ['gps-survey-mapping-products'],
    categoryIds: ['forestry', 'surveying'],
    tags: ['GPS, Survey & Mapping Products', 'GNSS']
  },
  {
    slug: 'rtk-dgps',
    name: 'RTK / DGPS',
    brand: 'AFFORDA',
    category: 'forestry',
    image: 'placeholder',
    gallery: ['placeholder'],
    label: 'RTK POSITIONING SYSTEM',
    summary: 'Differential positioning system for high-accuracy surveying and mapping applications.',
    specs: [['Specifications', 'Available on request']],
    features: ['Designed for boundary mapping and control points', 'Supports real-time differential corrections', 'Configuration details confirmed upon inquiry'],
    page: 1,
    subcategories: ['gps-survey-mapping-products'],
    categoryIds: ['forestry', 'surveying'],
    tags: ['GPS, Survey & Mapping Products', 'RTK / DGPS']
  },
  {
    slug: 'sub-meter-gps',
    name: 'Sub-meter GPS',
    brand: 'AFFORDA',
    category: 'forestry',
    image: 'placeholder',
    gallery: ['placeholder'],
    label: 'SUB-METER MAPPING GPS',
    summary: 'Handheld GPS unit for field mapping, asset location, and GIS data collection.',
    specs: [['Specifications', 'Available on request']],
    features: ['Handheld unit for GIS data collection and field mapping', 'Designed for utility and forestry asset location', 'Built for outdoor operating environments'],
    page: 1,
    subcategories: ['gps-survey-mapping-products'],
    categoryIds: ['forestry', 'surveying'],
    tags: ['GPS, Survey & Mapping Products', 'Sub-meter GPS']
  },
  {
    slug: 'centimeter-mm-accuracy-gnss',
    name: 'Centimeter / mm-accuracy GNSS',
    brand: 'AFFORDA',
    category: 'forestry',
    image: 'placeholder',
    gallery: ['placeholder'],
    label: 'HIGH-PRECISION GNSS',
    summary: 'High-precision GNSS positioning equipment for surveying and geodetic measurements.',
    specs: [['Specifications', 'Available on request']],
    features: ['Geodetic survey receiver for high-precision mapping', 'Suitable for boundary and engineering surveys', 'Configuration details confirmed upon inquiry'],
    page: 1,
    subcategories: ['gps-survey-mapping-products'],
    categoryIds: ['forestry', 'surveying'],
    tags: ['GPS, Survey & Mapping Products', 'Precision GNSS']
  },
  {
    slug: 'electronic-data-collector',
    name: 'Electronic Data Collector',
    brand: 'AFFORDA',
    category: 'forestry',
    image: 'placeholder',
    gallery: ['placeholder'],
    label: 'SURVEY FIELD CONTROLLER',
    summary: 'Field data controller for logging measurements and managing geospatial survey data.',
    specs: [['Specifications', 'Available on request']],
    features: ['Handheld unit for logging field survey observations', 'Designed for pairing with GNSS receivers and total stations', 'Rugged housing with touchscreen and keypad input'],
    page: 1,
    subcategories: ['gps-survey-mapping-products'],
    categoryIds: ['forestry', 'surveying'],
    tags: ['GPS, Survey & Mapping Products', 'Data Collector']
  },
  {
    slug: 'digital-compass',
    name: 'Digital Compass',
    brand: 'AFFORDA',
    category: 'forestry',
    image: 'placeholder',
    gallery: ['placeholder'],
    label: 'ELECTRONIC BEARING COMPASS',
    summary: 'Electronic compass for field orientation, direction finding, and survey bearings.',
    specs: [['Specifications', 'Available on request']],
    features: ['Digital display for directional bearings and headings', 'Assists in field navigation and orientation', 'Compact handheld unit for field crews'],
    page: 1,
    subcategories: ['gps-survey-mapping-products'],
    categoryIds: ['forestry', 'surveying'],
    tags: ['GPS, Survey & Mapping Products', 'Digital Compass']
  },
  {
    slug: 'staff-compass',
    name: 'Staff Compass',
    brand: 'AFFORDA',
    category: 'forestry',
    image: 'placeholder',
    gallery: ['placeholder'],
    label: 'MOUNTABLE SURVEY COMPASS',
    summary: 'Mountable survey compass for taking bearings and angles in forestry and boundary surveys.',
    specs: [['Specifications', 'Available on request']],
    features: ['Survey compass mountable on staff or tripod', 'Used for taking directional bearings and survey angles', 'Designed for forestry and boundary layout'],
    page: 1,
    subcategories: ['gps-survey-mapping-products'],
    categoryIds: ['forestry', 'surveying'],
    tags: ['GPS, Survey & Mapping Products', 'Staff Compass']
  },
  {
    slug: 'altimeter',
    name: 'Altimeter',
    brand: 'AFFORDA',
    category: 'forestry',
    image: 'placeholder',
    gallery: ['placeholder'],
    label: 'BAROMETRIC ALTIMETER',
    summary: 'Field instrument for measuring altitude and elevation changes during field surveys.',
    specs: [['Specifications', 'Available on request']],
    features: ['Measures altitude and elevation differences in the field', 'Assists in topographic surveys and elevation profiling', 'Compact format for field carry'],
    page: 1,
    subcategories: ['gps-survey-mapping-products'],
    categoryIds: ['forestry', 'surveying'],
    tags: ['GPS, Survey & Mapping Products', 'Altimeter']
  },
  {
    slug: 'total-station',
    name: 'Total Station',
    brand: 'AFFORDA',
    category: 'forestry',
    image: 'placeholder',
    gallery: ['placeholder'],
    label: 'OPTICAL SURVEY INSTRUMENT',
    summary: 'Electronic optical instrument used in surveying for measuring angles and distances.',
    specs: [['Specifications', 'Available on request']],
    features: ['Measures angles and distances for survey layouts', 'Designed for engineering and boundary surveys', 'Mounts on standard survey tripods'],
    page: 1,
    subcategories: ['gps-survey-mapping-products'],
    categoryIds: ['forestry', 'surveying'],
    tags: ['GPS, Survey & Mapping Products', 'Total Station']
  },
  {
    slug: 'automatic-level',
    name: 'Automatic Level',
    brand: 'AFFORDA',
    category: 'forestry',
    image: 'placeholder',
    gallery: ['placeholder'],
    label: 'OPTICAL SURVEY LEVEL',
    summary: 'Optical leveling instrument used for establishing horizontal lines of sight in survey work.',
    specs: [['Specifications', 'Available on request']],
    features: ['Establishes horizontal level lines for elevation surveys', 'Optical sighting system for leveling runs', 'Mounts to standard survey tripods'],
    page: 1,
    subcategories: ['gps-survey-mapping-products'],
    categoryIds: ['forestry', 'surveying'],
    tags: ['GPS, Survey & Mapping Products', 'Automatic Level']
  },
  {
    slug: 'survey-tripod',
    name: 'Survey Tripod',
    brand: 'AFFORDA',
    category: 'forestry',
    image: 'placeholder',
    gallery: ['placeholder'],
    label: 'INSTRUMENT FIELD TRIPOD',
    summary: 'Mounting tripod for supporting survey instruments, total stations, and levels in the field.',
    specs: [['Specifications', 'Available on request']],
    features: ['Provides stable mounting for survey instruments', 'Adjustable legs for uneven field terrain', 'Standard instrument mount threading'],
    page: 1,
    subcategories: ['gps-survey-mapping-products'],
    categoryIds: ['forestry', 'surveying'],
    tags: ['GPS, Survey & Mapping Products', 'Survey Tripod']
  },
  {
    slug: 'measuring-rod',
    name: 'Measuring Rod',
    brand: 'AFFORDA',
    category: 'forestry',
    image: 'placeholder',
    gallery: ['placeholder'],
    label: 'SURVEY LEVELING ROD',
    summary: 'Graduated leveling rod for elevation readings and height measurements in field surveys.',
    specs: [['Specifications', 'Available on request']],
    features: ['Graduated rod for elevation and height readings', 'Extensible sections for convenient transport', 'Clear markings for optical leveling'],
    page: 1,
    subcategories: ['gps-survey-mapping-products'],
    categoryIds: ['forestry', 'surveying'],
    tags: ['GPS, Survey & Mapping Products', 'Measuring Rod']
  },
  {
    slug: 'plot-markers',
    name: 'Plot Markers',
    brand: 'AFFORDA',
    category: 'forestry',
    image: 'placeholder',
    gallery: ['placeholder'],
    label: 'SURVEY GROUND MARKERS',
    summary: 'Boundary markers and survey stakes for identifying sample plots and field boundaries.',
    specs: [['Specifications', 'Available on request']],
    features: ['Identifies survey corners and sample plot centers', 'Designed for ground placement in field terrain', 'Aids in relocating field plots and boundary points'],
    page: 1,
    subcategories: ['gps-survey-mapping-products'],
    categoryIds: ['forestry', 'surveying'],
    tags: ['GPS, Survey & Mapping Products', 'Plot Markers']
  },
  {
    slug: 'flagging-tape',
    name: 'Flagging Tape',
    brand: 'AFFORDA',
    category: 'forestry',
    image: 'placeholder',
    gallery: ['placeholder'],
    label: 'HIGH-VISIBILITY MARKING',
    summary: 'High-visibility tape for marking trees, boundary lines, and survey stations.',
    specs: [['Specifications', 'Available on request']],
    features: ['High-visibility marking for trees and boundaries', 'Non-adhesive roll format for easy tying', 'Ideal for forestry layout and trail marking'],
    page: 1,
    subcategories: ['gps-survey-mapping-products'],
    categoryIds: ['forestry', 'surveying'],
    tags: ['GPS, Survey & Mapping Products', 'Flagging Tape']
  },
  {
    slug: 'field-data-recorder',
    name: 'Field Data Recorder',
    brand: 'AFFORDA',
    category: 'forestry',
    image: 'placeholder',
    gallery: ['placeholder'],
    label: 'ELECTRONIC FIELD RECORDER',
    summary: 'Handheld digital device for recording notes, observations, and field inventory data.',
    specs: [['Specifications', 'Available on request']],
    features: ['Digital recording for notes and inventory data', 'Designed for mobile outdoor workflows', 'Helps reduce manual paper transcription in the field'],
    page: 1,
    subcategories: ['gps-survey-mapping-products'],
    categoryIds: ['forestry', 'surveying'],
    tags: ['GPS, Survey & Mapping Products', 'Field Data Recorder']
  },

  // =========================================================================
  // 3. FOREST FIRE-FIGHTING PRODUCTS (Subcategory ID: forest-fire-fighting-products)
  // =========================================================================
  {
    slug: 'backpack-fire-pump',
    name: 'Backpack Fire Pump',
    brand: 'AFFORDA',
    category: 'forestry',
    image: 'placeholder',
    gallery: ['placeholder'],
    label: 'PORTABLE WATER APPARATUS',
    summary: 'Backpack-mounted water container and hand pump for wildland fire suppression and mop-up.',
    specs: [['Specifications', 'Available on request']],
    features: ['Backpack container with manual slide-action pump', 'Designed for mop-up and initial attack operations', 'Harness straps for field transport across rough terrain'],
    page: 1,
    subcategories: ['forest-fire-fighting-products'],
    categoryIds: ['forestry'],
    tags: ['Forest Fire-Fighting Products', 'Backpack Fire Pump']
  },
  {
    slug: 'portable-fire-pump',
    name: 'Portable Fire Pump',
    brand: 'AFFORDA',
    category: 'forestry',
    image: 'placeholder',
    gallery: ['placeholder'],
    label: 'FORESTRY FIRE PUMP',
    summary: 'Portable pump unit designed for moving water to supply wildland fire suppression efforts.',
    specs: [['Specifications', 'Available on request']],
    features: ['Compact pump unit for remote water delivery', 'Designed for wildland fire suppression', 'Handles water transfer from natural sources'],
    page: 1,
    subcategories: ['forest-fire-fighting-products'],
    categoryIds: ['forestry'],
    tags: ['Forest Fire-Fighting Products', 'Portable Fire Pump']
  },
  {
    slug: 'fire-rake',
    name: 'Fire Rake',
    brand: 'AFFORDA',
    category: 'forestry',
    image: 'placeholder',
    gallery: ['placeholder'],
    label: 'FIRELINE HAND TOOL',
    summary: 'Heavy-duty fireline rake designed for clearing duff, litter, and fuels during wildland firefighting.',
    specs: [['Specifications', 'Available on request']],
    features: ['Heavy-duty tines for cutting roots and raking duff', 'Used to construct firelines and mineral fuel breaks', 'Durable handle built for wildland crews'],
    page: 1,
    subcategories: ['forest-fire-fighting-products'],
    categoryIds: ['forestry'],
    tags: ['Forest Fire-Fighting Products', 'Fire Rake']
  },
  {
    slug: 'fire-swatter',
    name: 'Fire Swatter',
    brand: 'AFFORDA',
    category: 'forestry',
    image: 'placeholder',
    gallery: ['placeholder'],
    label: 'FLAME SMOTHERING TOOL',
    summary: 'Flap-style smothering tool for knocking down grass and surface flames along firelines.',
    specs: [['Specifications', 'Available on request']],
    features: ['Heavy flexible flap for smothering surface flames', 'Effective on grass and light brush firelines', 'Long handle for operator safety'],
    page: 1,
    subcategories: ['forest-fire-fighting-products'],
    categoryIds: ['forestry'],
    tags: ['Forest Fire-Fighting Products', 'Fire Swatter']
  },
  {
    slug: 'pulaski-forestry-axe',
    name: 'Pulaski Forestry Axe',
    brand: 'AFFORDA',
    category: 'forestry',
    image: 'placeholder',
    gallery: ['placeholder'],
    label: 'DUAL-PURPOSE FIRE AXE',
    summary: 'Dual-purpose tool combining an axe blade and grubbing mattock for fireline construction.',
    specs: [['Specifications', 'Available on request']],
    features: ['Dual head with cutting axe and grubbing hoe', 'Standard hand tool for wildland fireline digging', 'Balanced design for chopping roots and soil'],
    page: 1,
    subcategories: ['forest-fire-fighting-products'],
    categoryIds: ['forestry'],
    tags: ['Forest Fire-Fighting Products', 'Pulaski Axe']
  },
  {
    slug: 'forestry-axe',
    name: 'Forestry Axe',
    brand: 'AFFORDA',
    category: 'forestry',
    image: 'placeholder',
    gallery: ['placeholder'],
    label: 'TIMBER & CLEARING AXE',
    summary: 'Chopping and clearing axe for trail clearance and wildland fireline operations.',
    specs: [['Specifications', 'Available on request']],
    features: ['Chopping axe for clearing logs, limbs, and brush', 'Built for forestry work and trail maintenance', 'Durable handle and forged cutting head'],
    page: 1,
    subcategories: ['forest-fire-fighting-products'],
    categoryIds: ['forestry'],
    tags: ['Forest Fire-Fighting Products', 'Forestry Axe']
  },
  {
    slug: 'mcleod-tool',
    name: 'McLeod Tool',
    brand: 'AFFORDA',
    category: 'forestry',
    image: 'placeholder',
    gallery: ['placeholder'],
    label: 'RAKE & HOE COMBINATION',
    summary: 'Dual-purpose rake and hoe tool for digging firelines and scraping vegetation.',
    specs: [['Specifications', 'Available on request']],
    features: ['Combination wide rake tines and sharp hoe blade', 'Designed for scraping firelines down to mineral soil', 'Heavy-duty construction for wildland crews'],
    page: 1,
    subcategories: ['forest-fire-fighting-products'],
    categoryIds: ['forestry'],
    tags: ['Forest Fire-Fighting Products', 'McLeod Tool']
  },
  {
    slug: 'fire-beater',
    name: 'Fire Beater',
    brand: 'AFFORDA',
    category: 'forestry',
    image: 'placeholder',
    gallery: ['placeholder'],
    label: 'FIRE SUPPRESSION BEATER',
    summary: 'Manual fire suppression tool for extinguishing low-intensity ground fires.',
    specs: [['Specifications', 'Available on request']],
    features: ['Manual tool for knocking down low ground flames', 'Flexible beater head for grass and undergrowth', 'Extended handle provides operating reach'],
    page: 1,
    subcategories: ['forest-fire-fighting-products'],
    categoryIds: ['forestry'],
    tags: ['Forest Fire-Fighting Products', 'Fire Beater']
  },
  {
    slug: 'drip-torch',
    name: 'Drip Torch',
    brand: 'AFFORDA',
    category: 'forestry',
    image: 'placeholder',
    gallery: ['placeholder'],
    label: 'PRESCRIBED BURNING TORCH',
    summary: 'Specialized torch for controlled burning, backfiring, and burn-out operations in wildland fire management.',
    specs: [['Specifications', 'Available on request']],
    features: ['Designed for controlled backfiring and burning out', 'Dispenses fuel along designated firelines', 'Standard equipment for wildfire burn operations'],
    page: 1,
    subcategories: ['forest-fire-fighting-products'],
    categoryIds: ['forestry'],
    tags: ['Forest Fire-Fighting Products', 'Drip Torch']
  },
  {
    slug: 'fire-shelter',
    name: 'Fire Shelter',
    brand: 'AFFORDA',
    category: 'forestry',
    image: 'placeholder',
    gallery: ['placeholder'],
    label: 'EMERGENCY SAFETY SHELTER',
    summary: 'Emergency shelter deployed by wildland firefighters for entrapment protection.',
    specs: [['Specifications', 'Available on request']],
    features: ['Emergency deployment shelter for wildland firefighters', 'Designed for entrapment protection', 'Compact packable format with carrying case'],
    page: 1,
    subcategories: ['forest-fire-fighting-products'],
    categoryIds: ['forestry'],
    tags: ['Forest Fire-Fighting Products', 'Fire Shelter']
  },
  {
    slug: 'fire-weather-meter',
    name: 'Fire Weather Meter',
    brand: 'AFFORDA',
    category: 'forestry',
    image: 'placeholder',
    gallery: ['placeholder'],
    label: 'HANDHELD WEATHER METER',
    summary: 'Handheld weather meter for assessing ambient conditions and fire weather in the field.',
    specs: [['Specifications', 'Available on request']],
    features: ['Handheld unit for monitoring weather conditions on scene', 'Measures temperature, wind, and relative humidity', 'Assists in assessing fire behavior factors'],
    page: 1,
    subcategories: ['forest-fire-fighting-products'],
    categoryIds: ['forestry'],
    tags: ['Forest Fire-Fighting Products', 'Fire Weather Meter']
  },
  {
    slug: 'weather-monitoring-kit',
    name: 'Weather Monitoring Kit',
    brand: 'AFFORDA',
    category: 'forestry',
    image: 'placeholder',
    gallery: ['placeholder'],
    label: 'FIELD WEATHER KIT',
    summary: 'Field weather kit for monitoring temperature, wind, and relative humidity.',
    specs: [['Specifications', 'Available on request']],
    features: ['Field kit for measuring atmospheric conditions', 'Includes instruments for wind and humidity checks', 'Portable carry case for field operations'],
    page: 1,
    subcategories: ['forest-fire-fighting-products'],
    categoryIds: ['forestry'],
    tags: ['Forest Fire-Fighting Products', 'Weather Kit']
  },
  {
    slug: 'water-tank',
    name: 'Water Tank',
    brand: 'AFFORDA',
    category: 'forestry',
    image: 'placeholder',
    gallery: ['placeholder'],
    label: 'MOBILE WATER STORAGE',
    summary: 'Water storage container for vehicle mounting or temporary fireline staging.',
    specs: [['Specifications', 'Available on request']],
    features: ['Water storage container for field supply points', 'Suitable for vehicle mounting or temporary staging', 'Equipped with fill and discharge ports'],
    page: 1,
    subcategories: ['forest-fire-fighting-products'],
    categoryIds: ['forestry'],
    tags: ['Forest Fire-Fighting Products', 'Water Tank']
  },
  {
    slug: 'fire-hose',
    name: 'Fire Hose',
    brand: 'AFFORDA',
    category: 'forestry',
    image: 'placeholder',
    gallery: ['placeholder'],
    label: 'WILDLAND FIRE HOSE',
    summary: 'Flexible delivery hose designed for wildland fire operations.',
    specs: [['Specifications', 'Available on request']],
    features: ['Delivery hose designed for wildland fire applications', 'Built for field deployment across rugged terrain', 'Compatible with standard forestry hose fittings'],
    page: 1,
    subcategories: ['forest-fire-fighting-products'],
    categoryIds: ['forestry'],
    tags: ['Forest Fire-Fighting Products', 'Fire Hose']
  },
  {
    slug: 'hose-reel',
    name: 'Hose Reel',
    brand: 'AFFORDA',
    category: 'forestry',
    image: 'placeholder',
    gallery: ['placeholder'],
    label: 'FIELD HOSE REEL',
    summary: 'Reel unit for storing, deploying, and retrieving hose lines during field operations.',
    specs: [['Specifications', 'Available on request']],
    features: ['Organizes, deploys, and retrieves hose lines', 'Suitable for vehicle beds and utility apparatus', 'Prevents kinks and tangled hose lays'],
    page: 1,
    subcategories: ['forest-fire-fighting-products'],
    categoryIds: ['forestry'],
    tags: ['Forest Fire-Fighting Products', 'Hose Reel']
  },
  {
    slug: 'portable-water-pump',
    name: 'Portable Water Pump',
    brand: 'AFFORDA',
    category: 'forestry',
    image: 'placeholder',
    gallery: ['placeholder'],
    label: 'PORTABLE WATER PUMP',
    summary: 'Portable pumping equipment for drafting water from natural sources or storage tanks.',
    specs: [['Specifications', 'Available on request']],
    features: ['Portable pump for drafting and moving water in the field', 'Designed for remote wildland fire support', 'Compact frame for transport to water sources'],
    page: 1,
    subcategories: ['forest-fire-fighting-products'],
    categoryIds: ['forestry'],
    tags: ['Forest Fire-Fighting Products', 'Portable Water Pump']
  },
  {
    slug: 'fire-extinguisher',
    name: 'Fire Extinguisher',
    brand: 'AFFORDA',
    category: 'forestry',
    image: 'placeholder',
    gallery: ['placeholder'],
    label: 'EQUIPMENT EXTINGUISHER',
    summary: 'Portable extinguisher unit for emergency fire response on field vehicles and equipment.',
    specs: [['Specifications', 'Available on request']],
    features: ['Handheld extinguisher for equipment and vehicles', 'Provides immediate response on field machinery', 'Includes mounting bracket for transport'],
    page: 1,
    subcategories: ['forest-fire-fighting-products'],
    categoryIds: ['forestry'],
    tags: ['Forest Fire-Fighting Products', 'Fire Extinguisher']
  },
  {
    slug: 'firefighting-backpack',
    name: 'Firefighting Backpack',
    brand: 'AFFORDA',
    category: 'forestry',
    image: 'placeholder',
    gallery: ['placeholder'],
    label: 'WILDLAND PACK',
    summary: 'Load-bearing pack designed for carrying wildland fire equipment, gear, and supplies.',
    specs: [['Specifications', 'Available on request']],
    features: ['Designed to carry wildland gear, hydration, and tools', 'Padded harness balances load across rough terrain', 'Multiple compartments for field essentials'],
    page: 1,
    subcategories: ['forest-fire-fighting-products'],
    categoryIds: ['forestry'],
    tags: ['Forest Fire-Fighting Products', 'Firefighting Backpack']
  },
  {
    slug: 'personal-protective-equipment',
    name: 'Personal Protective Equipment',
    brand: 'AFFORDA',
    category: 'forestry',
    image: 'placeholder',
    gallery: ['placeholder'],
    label: 'WILDLAND PPE',
    summary: 'Protective gear ensemble for wildland firefighting and field operations.',
    specs: [['Specifications', 'Available on request']],
    features: ['Protective clothing and gear for wildland crews', 'Designed for heat and outdoor field hazards', 'Sizing and configuration confirmed upon inquiry'],
    page: 1,
    subcategories: ['forest-fire-fighting-products'],
    categoryIds: ['forestry'],
    tags: ['Forest Fire-Fighting Products', 'PPE']
  }
];

export const brandDescriptions: Record<string,string> = {
  'AFFORDA':'Specialized supplier of professional field, forestry, surveying, and wildfire management equipment.',
  'Vortex Optics':'A closer connection to the world beyond. Discover HD binoculars and precision observation optics.',
  'Garmin':'Find your position and your next destination with purpose-built handheld navigation.',
  'Brunton':'Tools for reading the earth. Explore geological transits and precision field compasses.',
  'Browning':'Observe life in the wild with dedicated trail-camera technology.',
  'Brutforce':'Keep field teams connected with portable communication products.',
  'Ralcam':'Reach difficult spaces with articulating inspection camera systems.',
  'HIKMICRO':'See temperature and heat signatures with portable thermal imaging.',
  'Panasonic Toughbook':'Rugged computing platforms configured for mobile professional work.',
  'DGPS solutions':'Tell us your survey accuracy, correction network and field workflow requirements. Our team will help identify an appropriate DGPS solution.',
  'Suunto':'Dependable sighting compasses and navigation tools for the field.',
  'MINOX':'Digital night vision for observation beyond daylight.',
  'Open Acoustic Devices':'Compact acoustic loggers for ecological research and wildlife monitoring.',
};

export const finderOptions: Record<string, Record<string, string[]>> = {
  'Forestry & Wildlife': {
    'Forest Measurement': ['diameter-tape-dbh-tape', 'digital-tree-caliper', 'clinometer', 'hypsometer', 'laser-rangefinder'],
    'Mapping & Navigation': ['garmin-gpsmap-65s', 'professional-gnss-receiver', 'rtk-dgps', 'laser-rangefinder'],
    'Fire Suppression': ['backpack-fire-pump', 'portable-fire-pump', 'pulaski-forestry-axe', 'drip-torch', 'fire-weather-meter'],
    'Wildlife monitoring': ['browning-strike-force-pro-dcl', 'audiomoth'],
    'Night observation': ['hikmicro-lynx-lh25', 'minox-nvd-650'],
  },
  'Surveying & Mapping': { 'Navigation':['garmin-gpsmap-65s','garmin-montana-700'], 'DGPS positioning':['rtk-dgps','professional-gnss-receiver'], 'Field computing':['panasonic-toughbook','electronic-data-collector'] },
  'Geology & Research': { 'Compass & transit measurement':['brunton-geolite','brunton-compro-transit','brunton-f-5012-axis'], 'Navigation & positioning':['suunto-mc2','garmin-gpsmap-65s'] },
  'Industrial Inspection': { 'Confined-space inspection':['ralcam-h408b'], 'Thermal observation':['hikmicro-e20-plus','hikmicro-lynx-lh25'], 'Field computing':['panasonic-toughbook'] },
  'Field Operations': { 'Team communication':['brutforce-field-radio'], 'Navigation':['garmin-gpsmap-65s','suunto-mc2'], 'Night observation':['hikmicro-lynx-lh25','minox-nvd-650'] },
  'Defense & Paramilitary': {
    'Thermal Imaging':['hikmicro-lynx-lh25'],
    'Night Vision':['minox-nvd-650'],
    'GPS / Navigation':['garmin-gpsmap-65s','garmin-montana-700','suunto-mc2'],
    'Binoculars / Optics':['vortex-viper-hd','vortex-diamondback-hd'],
    'Communication':['brutforce-field-radio'],
    'Rugged Computing':['panasonic-toughbook'],
    'Surveillance / Monitoring':['browning-strike-force-pro-dcl','hikmicro-lynx-lh25','minox-nvd-650'],
  },
  'Mining & Geology': {
    'Geological Survey':['brunton-geolite','brunton-compro-transit','brunton-f-5012-axis'],
    'Mapping / GNSS':['garmin-gpsmap-65s','garmin-montana-700'],
    'Compasses / Pocket Transits':['brunton-geolite','brunton-compro-transit','brunton-f-5012-axis'],
    'Distance Measurement':['garmin-gpsmap-65s','garmin-montana-700'],
    'Rugged Computing':['panasonic-toughbook'],
    'Field Inspection':['ralcam-h408b'],
  },
};

export function findEquipment(industry: string, requirement: string) {
  const options = finderOptions[industry];
  if (!options || !Object.hasOwn(options, requirement)) throw new Error('Choose a valid industry and requirement.');
  return products.filter(p => options[requirement].includes(p.slug));
}
export function productBelongsToCategory(product: Product, categoryId: string) {
  return product.category === categoryId || product.categoryIds?.includes(categoryId) === true;
}
export const whatsAppUrl = (message: string) => `https://wa.me/919818320178?text=${encodeURIComponent(message)}`;
