import type { Product } from '@/lib/catalogue';

export const canonGoProProducts: Product[] = [
  // =========================================================================
  // BRAND: CANON (Image Stabilized Optics & Field Observation)
  // =========================================================================
  {
    slug: 'canon-12x36-is-iii',
    aliases: ['12x36-is-iii', 'canon-12x36-is', 'canon-12x36'],
    name: 'Canon 12x36 IS III Binoculars',
    brand: 'Canon',
    category: 'optics',
    image: 'canon-12x36-is-iii',
    gallery: ['canon-12x36-is-iii'],
    label: '12X IMAGE STABILIZED FIELD OBSERVATION BINOCULARS',
    summary: 'Compact and lightweight 12x magnification image-stabilized binoculars featuring Canon proprietary Vari-Angle Prism (VAP) technology, doublet field-flattener lenses, and Super Spectra multi-coating for shake-free long-range handheld observation. (Canon Model 9526B002, ASIN B00XOD5C1W).',
    specs: [
      ['Model Number', '9526B002'],
      ['Magnification', '12x'],
      ['Objective Lens Diameter', '36 mm'],
      ['Image Stabilization System', 'Vari-Angle Prism (VAP) Optical IS'],
      ['Real Field of View', '5.0°'],
      ['Apparent Field of View', '55.3°'],
      ['Field of View at 1000m', '87.5 m (262 ft / 1000 yds)'],
      ['Exit Pupil Diameter', '3.0 mm'],
      ['Eye Relief', '14.5 mm'],
      ['Minimum Focusing Distance', '6.0 m (19.7 ft)'],
      ['Prism Type', 'Porro II Prism'],
      ['Lens Coatings', 'Super Spectra Coating, Doublet Field Flattener'],
      ['Power Source', '2x AA Alkaline or NiMH Batteries'],
      ['Battery Life', 'Approx. 9 hours at 25°C continuous IS'],
      ['Dimensions (W x H x D)', '127 x 174 x 70 mm'],
      ['Weight', '660 g (excluding batteries)'],
    ],
    features: [
      'Canon Vari-Angle Prism (VAP) optical image stabilization neutralizes hand tremor for high-power steady viewing',
      'High 12x magnification brings distant wildlife, tactical objectives, and field terrain into razor-sharp focus',
      'Doublet field-flattener lenses eliminate curvilinear distortion for edge-to-edge optical clarity',
      'Super Spectra lens coatings maximize light transmission, color fidelity, and contrast while minimizing ghosting',
      'Ergonomic, lightweight 660g chassis with tactile fingertip IS activation button for rapid one-touch stabilization',
    ],
    page: 50,
    subcategories: ['defense-optics'],
    categoryIds: ['optics', 'defense'],
    tags: ['Binoculars', 'Observation Optics'],
  },
  {
    slug: 'canon-10x42-l-is-wp',
    aliases: ['10x42-l-is-wp', 'canon-10x42-l-is', 'canon-10x42-is'],
    name: 'Canon 10x42 L IS WP Binoculars',
    brand: 'Canon',
    category: 'optics',
    image: 'canon-10x42-l-is-wp',
    gallery: ['canon-10x42-l-is-wp'],
    label: 'WATERPROOF 10X L-SERIES IMAGE STABILIZED BINOCULARS',
    summary: 'Flagship waterproof image-stabilized binoculars engineered with legendary Canon L-series optics, Ultra-low Dispersion (UD) elements, large 4.2mm exit pupil, and full JIS 7 submersible waterproofing for demanding marine and field observation.',
    specs: [
      ['Magnification', '10x'],
      ['Objective Lens Diameter', '42 mm'],
      ['Optical Construction', 'L-Series with 2 Ultra-low Dispersion (UD) elements'],
      ['Image Stabilization System', 'Vari-Angle Prism (VAP) Optical IS'],
      ['Real Field of View', '6.5°'],
      ['Apparent Field of View', '59.2°'],
      ['Field of View at 1000m', '114 m (342 ft / 1000 yds)'],
      ['Exit Pupil Diameter', '4.2 mm'],
      ['Eye Relief', '16.0 mm'],
      ['Minimum Focusing Distance', '2.5 m (8.2 ft)'],
      ['Prism Type', 'Porro II Prism'],
      ['Environmental Sealing', 'Waterproof (JIS 7 submersible: 1m depth for 30 minutes)'],
      ['Power Source', '2x AA Alkaline or Lithium Batteries'],
      ['Battery Life', 'Approx. 8 hours (alkaline or lithium) at 25°C'],
      ['Dimensions (W x H x D)', '137 x 176 x 85 mm'],
      ['Weight', '1,110 g (excluding batteries)'],
    ],
    features: [
      'Premium Canon L-series optics incorporating two UD lens elements per side virtually eliminate chromatic aberration',
      'JIS 7 grade waterproof construction withstands complete water submersion up to 1 meter for 30 minutes',
      'Bright 4.2mm exit pupil delivers superior low-light performance during dawn, dusk, and maritime conditions',
      'Optical image stabilizer compensates for vessel rocking, vehicle vibration, and severe hand motion',
      'Generous 16mm eye relief and twist-up eyecups provide full visual field for eye-glass wearers',
    ],
    page: 50,
    subcategories: ['defense-optics'],
    categoryIds: ['optics', 'defense'],
    tags: ['Binoculars', 'Observation Optics'],
  },
  {
    slug: 'canon-18x50-is-all-weather',
    aliases: ['18x50-is-all-weather', 'canon-18x50-is', 'canon-18x50'],
    name: 'Canon 18x50 IS All Weather Binoculars',
    brand: 'Canon',
    category: 'optics',
    image: 'canon-18x50-is-all-weather',
    gallery: ['canon-18x50-is-all-weather'],
    label: 'ULTRA-HIGH MAGNIFICATION 18X ALL-WEATHER IS BINOCULARS',
    summary: 'Ultra-powerful 18x magnification binoculars equipped with large 50mm objective lenses, UD optical glass, and high-frequency optical image stabilization in an all-weather weather-sealed chassis for extreme long-range surveillance.',
    specs: [
      ['Magnification', '18x'],
      ['Objective Lens Diameter', '50 mm'],
      ['Optical Construction', 'UD (Ultra-low Dispersion) lens elements'],
      ['Image Stabilization System', 'Vari-Angle Prism (VAP) Optical IS'],
      ['Real Field of View', '3.7°'],
      ['Apparent Field of View', '60.3°'],
      ['Field of View at 1000m', '65 m (194 ft / 1000 yds)'],
      ['Exit Pupil Diameter', '2.8 mm'],
      ['Eye Relief', '15.0 mm'],
      ['Minimum Focusing Distance', '6.0 m (19.7 ft)'],
      ['Prism Type', 'Porro II Prism'],
      ['Weather Sealing', 'All-Weather water-resistant (JIS 4 equivalent)'],
      ['Power Source', '2x AA Alkaline or Lithium Batteries'],
      ['Battery Life', 'Approx. 2.5 hours (alkaline) / 8 hours (lithium) at 25°C'],
      ['Dimensions (W x H x D)', '152 x 193 x 81 mm'],
      ['Weight', '1,180 g (excluding batteries)'],
    ],
    features: [
      'Formidable 18x magnification enables long-range target recognition without requiring a cumbersome spotting scope tripod',
      'Vari-Angle Prism stabilization maintains a steady, rock-solid field of view even at maximum optical power',
      'Large 50mm objective apertures gather abundant light for identification of distant details in harsh conditions',
      'UD optical elements dramatically reduce color fringing for crisp high-contrast border definition',
      'All-weather water-resistant exterior housing engineered for heavy precipitation, mountain cold, and coastal mist',
    ],
    page: 50,
    subcategories: ['defense-optics'],
    categoryIds: ['optics', 'defense'],
    tags: ['Binoculars', 'Observation Optics'],
  },
  {
    slug: 'canon-15x50-is-all-weather',
    aliases: ['15x50-is-all-weather', 'canon-15x50-is', 'canon-15x50'],
    name: 'Canon 15x50 IS All Weather Binoculars',
    brand: 'Canon',
    category: 'optics',
    image: 'canon-15x50-is-all-weather',
    gallery: ['canon-15x50-is-all-weather'],
    label: 'HIGH-POWER 15X ALL-WEATHER IMAGE STABILIZED BINOCULARS',
    summary: 'High-magnification 15x50 all-weather binoculars engineered with Ultra-low Dispersion (UD) glass, wide 61° apparent angle of view, and optical image stabilization for prolonged reconnaissance, border patrol, and wildlife observation.',
    specs: [
      ['Magnification', '15x'],
      ['Objective Lens Diameter', '50 mm'],
      ['Optical Construction', 'UD (Ultra-low Dispersion) lens elements'],
      ['Image Stabilization System', 'Vari-Angle Prism (VAP) Optical IS'],
      ['Real Field of View', '4.5°'],
      ['Apparent Field of View', '61.0°'],
      ['Field of View at 1000m', '79 m (236 ft / 1000 yds)'],
      ['Exit Pupil Diameter', '3.3 mm'],
      ['Eye Relief', '15.0 mm'],
      ['Minimum Focusing Distance', '6.0 m (19.7 ft)'],
      ['Prism Type', 'Porro II Prism'],
      ['Weather Sealing', 'All-Weather water-resistant (JIS 4 equivalent)'],
      ['Power Source', '2x AA Alkaline or Lithium Batteries'],
      ['Battery Life', 'Approx. 2.5 hours (alkaline) / 8 hours (lithium) at 25°C'],
      ['Dimensions (W x H x D)', '152 x 193 x 81 mm'],
      ['Weight', '1,180 g (excluding batteries)'],
    ],
    features: [
      'Wide 61.0° apparent field of view provides expansive panoramic coverage while retaining sharp 15x detail',
      'Optical image stabilizer instantly counteracts handheld shakiness and vehicle engine vibration',
      'Large 50mm objective elements paired with UD glass provide superior light transmission and chromatic fidelity',
      'Robust JIS 4 weather-resistant casing safeguards internal prisms and electronics against torrential rain and spray',
      '1/4"-20 standard tripod socket integrated into base for optional stationary surveillance mounting',
    ],
    page: 50,
    subcategories: ['defense-optics'],
    categoryIds: ['optics', 'defense'],
    tags: ['Binoculars', 'Observation Optics'],
  },
  {
    slug: 'canon-12x32-is',
    aliases: ['12x32-is', 'canon-12x32'],
    name: 'Canon 12x32 IS Binoculars',
    brand: 'Canon',
    category: 'optics',
    image: 'canon-12x32-is',
    gallery: ['canon-12x32-is'],
    label: 'DUAL-MODE POWERED IMAGE STABILIZED BINOCULARS',
    summary: 'Mid-size 12x binoculars featuring advanced Lens Shift optical image stabilization with dual Standard and Powered IS modes, ergonomically contoured body, and 10-hour battery life for steady handheld observation.',
    specs: [
      ['Magnification', '12x'],
      ['Objective Lens Diameter', '32 mm'],
      ['Image Stabilization System', 'Lens Shift Mechanism (Standard IS & Powered IS)'],
      ['Real Field of View', '5.0°'],
      ['Apparent Field of View', '55.3°'],
      ['Field of View at 1000m', '87 m (262 ft / 1000 yds)'],
      ['Exit Pupil Diameter', '2.7 mm'],
      ['Eye Relief', '14.5 mm'],
      ['Minimum Focusing Distance', '2.0 m (6.6 ft)'],
      ['Prism Type', 'Porro II Prism'],
      ['Power Source', '2x AA Alkaline, NiMH, or Lithium Batteries'],
      ['Battery Life', 'Approx. 10 hours at 25°C'],
      ['Dimensions (W x H x D)', '142 x 171 x 77 mm'],
      ['Weight', '780 g (excluding batteries)'],
    ],
    features: [
      'Lens Shift technology incorporates separate Standard IS for moving targets and Powered IS for stationary lock-on',
      'Compact 32mm format bridges portable field mobility with strong 12x optical reach',
      'Close 2.0-meter minimum focusing distance allows close-range inspection of botanical and structural specimens',
      'Ergonomic non-slip rubber grip with thumb rests designed for fatigue-free long observation shifts',
      'Extended 10-hour continuous runtime powered by easily accessible standard AA cells',
    ],
    page: 50,
    subcategories: ['defense-optics'],
    categoryIds: ['optics', 'defense'],
    tags: ['Binoculars', 'Observation Optics'],
  },
  {
    slug: 'canon-10x30-is-ii',
    aliases: ['10x30-is-ii', 'canon-10x30-is', 'canon-10x30'],
    name: 'Canon 10x30 IS II Binoculars',
    brand: 'Canon',
    category: 'optics',
    image: 'canon-10x30-is-ii',
    gallery: ['canon-10x30-is-ii'],
    label: 'COMPACT 10X IMAGE STABILIZED FIELD BINOCULARS',
    summary: 'Second-generation 10x image-stabilized binoculars offering rapid image acquisition, doublet field-flattener sharpness, low power consumption, and lightweight 600g construction for versatile field and expedition reconnaissance.',
    specs: [
      ['Magnification', '10x'],
      ['Objective Lens Diameter', '30 mm'],
      ['Image Stabilization System', 'Vari-Angle Prism (VAP) Optical IS'],
      ['Real Field of View', '6.0°'],
      ['Apparent Field of View', '55.3°'],
      ['Field of View at 1000m', '105 m (314 ft / 1000 yds)'],
      ['Exit Pupil Diameter', '3.0 mm'],
      ['Eye Relief', '14.5 mm'],
      ['Minimum Focusing Distance', '4.2 m (13.8 ft)'],
      ['Prism Type', 'Porro II Prism'],
      ['Lens Coatings', 'Super Spectra Coating'],
      ['Power Source', '2x AA Alkaline or NiMH Batteries'],
      ['Battery Life', 'Approx. 9 hours at 25°C'],
      ['Dimensions (W x H x D)', '127 x 150 x 70 mm'],
      ['Weight', '600 g (excluding batteries)'],
    ],
    features: [
      'Balanced 10x magnification with generous 6.0° real field of view for quick subject tracking',
      'Vari-Angle Prism image stabilization corrects involuntary hand jitter with low power consumption',
      'Canon Super Spectra multicoating suppresses internal flare and delivers vibrant, true-to-life color rendering',
      'Field flattener technology ensures sharp focus across the entire visual frame out to the edges',
      'Low-profile 600g chassis fits readily into field packs and vehicles for fast deployment',
    ],
    page: 50,
    subcategories: ['defense-optics'],
    categoryIds: ['optics', 'defense'],
    tags: ['Binoculars', 'Observation Optics'],
  },
  {
    slug: 'canon-10x20-is',
    aliases: ['10x20-is', 'canon-10x20'],
    name: 'Canon 10x20 IS Binoculars',
    brand: 'Canon',
    category: 'optics',
    image: 'canon-10x20-is',
    gallery: ['canon-10x20-is'],
    label: 'ULTRA-COMPACT 10X LENS SHIFT IS BINOCULARS',
    summary: 'Ultra-compact, pocketable 10x binoculars featuring Canon EF lens-derived Lens Shift image stabilization, 12-hour continuous runtime from a single CR123A battery, and 430g lightweight build for mobile field scouting.',
    specs: [
      ['Magnification', '10x'],
      ['Objective Lens Diameter', '20 mm'],
      ['Image Stabilization System', 'Lens Shift Optical IS'],
      ['Real Field of View', '5.3°'],
      ['Apparent Field of View', '49.5°'],
      ['Field of View at 1000m', '93 m (278 ft / 1000 yds)'],
      ['Exit Pupil Diameter', '2.0 mm'],
      ['Eye Relief', '13.5 mm'],
      ['Minimum Focusing Distance', '2.0 m (6.6 ft)'],
      ['Prism Type', 'Porro Prism'],
      ['Power Source', '1x CR123A Lithium Battery'],
      ['Battery Life', 'Approx. 12 hours at 25°C'],
      ['Dimensions (W x H x D)', '118 x 142 x 69 mm'],
      ['Weight', '430 g (excluding battery)'],
    ],
    features: [
      'Derived from Canon renowned EF camera lens stabilization mechanism for smooth, whisper-quiet compensation',
      'Exceptionally light 430g chassis allows effortless all-day pocket carrying without neck strain',
      'Impressive 12-hour battery autonomy on a single lithium CR123A cell',
      'Close 2.0-meter minimum focusing distance enables flexible near and far target observation',
      'Curved contouring and central focus wheel ensure natural, single-handed stabilization and focus',
    ],
    page: 50,
    subcategories: ['defense-optics'],
    categoryIds: ['optics', 'defense'],
    tags: ['Binoculars', 'Observation Optics'],
  },
  {
    slug: 'canon-8x20-is',
    aliases: ['8x20-is', 'canon-8x20'],
    name: 'Canon 8x20 IS Binoculars',
    brand: 'Canon',
    category: 'optics',
    image: 'canon-8x20-is',
    gallery: ['canon-8x20-is'],
    label: 'ULTRA-LIGHTWEIGHT 8X LENS SHIFT IS BINOCULARS',
    summary: 'Canon lightest image-stabilized binoculars at 420g, combining 8x magnification, wide 6.6° real field of view, EF Lens Shift technology, and 12-hour lithium battery life for rapid handheld observation.',
    specs: [
      ['Magnification', '8x'],
      ['Objective Lens Diameter', '20 mm'],
      ['Image Stabilization System', 'Lens Shift Optical IS'],
      ['Real Field of View', '6.6°'],
      ['Apparent Field of View', '49.5°'],
      ['Field of View at 1000m', '115 m (346 ft / 1000 yds)'],
      ['Exit Pupil Diameter', '2.5 mm'],
      ['Eye Relief', '13.5 mm'],
      ['Minimum Focusing Distance', '2.0 m (6.6 ft)'],
      ['Prism Type', 'Porro Prism'],
      ['Power Source', '1x CR123A Lithium Battery'],
      ['Battery Life', 'Approx. 12 hours at 25°C'],
      ['Dimensions (W x H x D)', '118 x 142 x 69 mm'],
      ['Weight', '420 g (excluding battery)'],
    ],
    features: [
      'Lightest image-stabilized binoculars in class at just 420g for uncompromised expedition mobility',
      'Wide 6.6° real angle of view and 115m field of view provide effortless target tracking and spatial awareness',
      'Lens Shift stabilization eliminates handshake, allowing steady inspection of wildlife, terrain, and distant landmarks',
      'Super Spectra coating maintains high contrast and rich coloration in diverse outdoor lighting',
      'Up to 12 hours of operational life on a single compact CR123A lithium cell',
    ],
    page: 50,
    subcategories: ['defense-optics'],
    categoryIds: ['optics', 'defense'],
    tags: ['Binoculars', 'Observation Optics'],
  },

  // =========================================================================
  // BRAND: GOPRO (Action Cameras & 360° Field Imaging)
  // =========================================================================
  {
    slug: 'gopro-hero13-black',
    aliases: ['hero13-black', 'hero-13', 'hero13', 'chdhx-131'],
    name: 'GoPro HERO13 Black',
    brand: 'GoPro',
    category: 'defense',
    image: 'gopro-hero13-black',
    gallery: ['gopro-hero13-black', 'gopro-hero13-black-2'],
    label: 'FLAGSHIP 5.3K60 ACTION CAMERA WITH HB-SERIES LENS SYSTEM',
    summary: 'Flagship tactical action and field imaging camera featuring 5.3K60 video, 27.13MP photos, HyperSmooth 6.0 stabilization with 360° Horizon Lock, magnetic latch mounting, HB-Series smart lens auto-detection, and waterproof durability to 10m (33ft). (GoPro Model CHDHX-131-master).',
    specs: [
      ['Model Number', 'CHDHX-131-master'],
      ['Video Resolution', '5.3K60, 4K120, 2.7K240, 1080p240'],
      ['Photo Resolution', '27.13 MP (5568 x 4872)'],
      ['Burst Slo-Mo', '720p at 400 fps (13x), 900p at 360 fps, 5.3K at 120 fps'],
      ['Image Stabilization', 'HyperSmooth 6.0 with 360° Horizon Lock'],
      ['Lens Compatibility', 'HB-Series Lenses (Ultra Wide, Macro, Anamorphic, ND Filters) with Auto-Detection'],
      ['Waterproof Rating', '10 m (33 ft) without housing'],
      ['Audio Architecture', '3-microphone array with wind-noise reduction & Bluetooth audio support'],
      ['High Dynamic Range', 'HLG HDR Video & 10-bit color (GP-Log)'],
      ['Battery', 'Removable 1900 mAh Enduro Battery'],
      ['Mounting System', 'Built-in folding fingers + Magnetic latch mount + 1/4-20 tripod thread'],
      ['Dimensions (W x H x D)', '71.8 x 50.8 x 33.6 mm'],
      ['Weight', '159 g (camera + battery + mounting fingers)'],
    ],
    features: [
      'Intelligent HB-Series lens integration automatically detects attached Ultra Wide, Macro, or ND lenses and calibrates settings',
      'HyperSmooth 6.0 video stabilization with 360° Horizon Lock keeps footage perfectly level through extreme roll and tilt',
      'High-capacity 1900 mAh Enduro battery provides extended runtimes across freezing temperatures and high heat',
      'Triple mounting versatility combining folding fingers, magnetic quick-release latching, and standard 1/4-20 threading',
      'Rugged waterproof chassis submersible to 10m (33ft) engineered for harsh tactical, marine, and expedition conditions',
    ],
    page: 52,
    subcategories: ['defense-surveillance', 'defense-field-operations'],
    categoryIds: ['defense'],
    tags: ['Action Cameras', 'Surveillance', 'Field Operations'],
  },
  {
    slug: 'gopro-hero12-black',
    aliases: ['hero12-black', 'hero-12', 'hero12', 'chdhx-121'],
    name: 'GoPro HERO12 Black',
    brand: 'GoPro',
    category: 'defense',
    image: 'gopro-hero12-black',
    gallery: ['gopro-hero12-black'],
    label: 'HIGH-RESOLUTION 5.3K HDR FIELD ACTION CAMERA',
    summary: 'Battle-tested action camera delivering 5.3K60 HDR video, 27.13MP stills, Emmy-winning HyperSmooth 6.0 stabilization, Bluetooth wireless audio support, 10-bit GP-Log encoding, and 10m (33ft) native waterproofing. (GoPro Model CHDHX-121-master).',
    specs: [
      ['Model Number', 'CHDHX-121-master'],
      ['Video Resolution', '5.3K60, 4K120, 2.7K240, 1080p240'],
      ['Photo Resolution', '27.13 MP (5568 x 4872)'],
      ['Image Stabilization', 'HyperSmooth 6.0 with 360° Horizon Lock'],
      ['High Dynamic Range', 'HDR Video (5.3K and 4K) & HDR Photo'],
      ['Waterproof Rating', '10 m (33 ft) without housing'],
      ['Audio Support', 'Bluetooth audio for wireless mic / headset integration + 3-mic processing'],
      ['Aspect Ratios', '8:7 full-sensor capture (supports 16:9, 9:16 vertical, 4:3)'],
      ['Battery', 'Removable 1720 mAh Enduro Battery'],
      ['Mounting System', 'Built-in folding fingers + 1/4-20 mounting thread'],
      ['Dimensions (W x H x D)', '71.8 x 50.8 x 33.6 mm'],
      ['Weight', '154 g (camera + battery + mounting fingers)'],
    ],
    features: [
      'Versatile 8:7 extra-large sensor captures expansive field of view ready for wide landscape or vertical mobile crops',
      'HyperSmooth 6.0 with AutoBoost provides maximum electronic stabilization with minimal image cropping',
      'Integrated Bluetooth audio allows field operators to connect wireless earpieces and microphones directly',
      'Native 1/4-20 mounting socket on base provides instant compatibility with standard tactical and industrial tripods',
      'Cold-weather optimized Enduro battery delivers reliable power during sub-zero winter or high-altitude operations',
    ],
    page: 52,
    subcategories: ['defense-surveillance', 'defense-field-operations'],
    categoryIds: ['defense'],
    tags: ['Action Cameras', 'Surveillance', 'Field Operations'],
  },
  {
    slug: 'gopro-max2',
    aliases: ['max2', 'gopro-max-2', 'chdhz-311'],
    name: 'GoPro MAX2',
    brand: 'GoPro',
    category: 'defense',
    image: 'gopro-max2',
    gallery: ['gopro-max2'],
    label: '8K 360° SPHERICAL FIELD RECONNAISSANCE CAMERA',
    summary: 'Next-generation 8K 360-degree spherical camera featuring dual high-grade replaceable optical glass lenses, 29.5MP 360° photo capture, 12MP single-lens mode, 6-microphone spatial audio, and unbreakable Max HyperSmooth stabilization. (GoPro Model CHDHZ-311-master).',
    specs: [
      ['Model Number', 'CHDHZ-311-master'],
      ['360° Video Resolution', 'True 8K 360° Video (7680 x 3840)'],
      ['360° Photo Resolution', '29.5 MP (7680 x 3840)'],
      ['Single-Lens Mode', '12.0 MP (4000 x 3000) photo & 4K single-lens video'],
      ['Image Stabilization', 'Max HyperSmooth with unbreakable 360° Horizon Leveling'],
      ['Optics', 'Dual high-grade optical glass lenses (replaceable)'],
      ['Audio System', '6-microphone array delivering 360° spherical spatial audio'],
      ['Waterproof Rating', 'Rugged all-weather waterproof construction'],
      ['Battery', 'Removable Enduro 1960 mAh Lithium-Ion battery'],
      ['Reframe Tools', 'Keyframe reframing and AI-assisted tracking via GoPro mobile/desktop'],
      ['Dimensions (W x H x D)', '64.0 x 69.7 x 48.7 mm'],
      ['Weight', '195 g'],
    ],
    features: [
      'Full 360° spherical 8K capture documents entire operational surroundings simultaneously without blind spots',
      'Max HyperSmooth delivers ultimate stabilization with 360° horizon leveling regardless of camera orientation',
      'User-replaceable optical glass lenses maintain field serviceability in abrasive and rugged environments',
      'Dual-mode functionality allows switching between complete spherical capture and traditional single-lens wide video',
      'Six integrated directional microphones record immersive spatial sound for accurate situational acoustic reproduction',
    ],
    page: 52,
    subcategories: ['defense-surveillance', 'defense-field-operations'],
    categoryIds: ['defense'],
    tags: ['Action Cameras', 'Surveillance', 'Field Operations'],
  },
  {
    slug: 'gopro-max',
    aliases: ['max', 'gopro-max-360', 'chdhz-203'],
    name: 'GoPro MAX',
    brand: 'GoPro',
    category: 'defense',
    image: 'gopro-max',
    gallery: ['gopro-max'],
    label: '5.6K 360° DUAL-LENS ACTION & SURVEILLANCE CAMERA',
    summary: 'Versatile 360-degree camera capturing 5.6K30 spherical video, 16.6MP 360° photos, 270° distortion-free PowerPano panoramas, and single-lens HERO mode with Max HyperSmooth stabilization and 5m (16ft) waterproofing. (GoPro Model CHDHZ-203-master).',
    specs: [
      ['Model Number', 'CHDHZ-203-master'],
      ['360° Video Resolution', '5.6K30 360° Video (5760 x 2880)'],
      ['360° Photo Resolution', '16.6 MP (5760 x 2880)'],
      ['Single-Lens Mode', '1440p60, 1080p60 HERO video & 5.5 MP photos'],
      ['Panoramic Photos', 'PowerPano 270° distortion-free 6.2 MP panoramic stills'],
      ['Image Stabilization', 'Max HyperSmooth with in-camera horizon leveling'],
      ['Digital Lenses', 'Narrow, Linear, Wide, and Max SuperView (149°)'],
      ['Audio System', '6-mic processing delivering directional audio and wind reduction'],
      ['Waterproof Rating', '5 m (16 ft) without housing'],
      ['Battery', 'Removable Enduro 1600 mAh Lithium-Ion battery'],
      ['Dimensions (W x H x D)', '64.0 x 69.7 x 39.7 mm'],
      ['Weight', '159 g'],
    ],
    features: [
      'Three cameras in one: spherical 360° video rig, standard single-lens HERO camera, and instant panoramic shooter',
      'Max SuperView delivers GoPro widest 149° field of view for total perimeter surveillance and incident recording',
      'Max TimeWarp captures stabilized 360° time-lapse videos with automatic speed ramping',
      'Intuitive color touchscreen makes framing, previewing, and adjusting settings fast and simple in the field',
      'Rugged 5-meter waterproof build withstands water immersion, mud, and heavy rain without an external housing',
    ],
    page: 52,
    subcategories: ['defense-surveillance', 'defense-field-operations'],
    categoryIds: ['defense'],
    tags: ['Action Cameras', 'Surveillance', 'Field Operations'],
  },
  {
    slug: 'gopro-hero',
    aliases: ['hero', 'gopro-hero-4k', 'chdhf-131'],
    name: 'GoPro HERO',
    brand: 'GoPro',
    category: 'defense',
    image: 'gopro-hero',
    gallery: ['gopro-hero'],
    label: 'ULTRA-COMPACT 86G 4K FIELD ACTION CAMERA',
    summary: 'Ultra-compact and featherweight 86g action camera delivering 4K30 video, 12MP photos, intuitive touchscreen interface, HyperSmooth digital stabilization, and 5m (16ft) waterproof durability for discreet tactical body mounting and field deployment. (GoPro Model CHDHF-131-master).',
    specs: [
      ['Model Number', 'CHDHF-131-master'],
      ['Video Resolution', 'Ultra HD 4K30, 1080p30, and 2.7K60 slow-motion (2x)'],
      ['Photo Resolution', '12 MP single photos'],
      ['Form Factor', 'GoPro smallest and lightest 4K camera (35% smaller than HERO13)'],
      ['Image Stabilization', 'HyperSmooth video stabilization via GoPro Quik app'],
      ['Display', 'Rear LCD touch screen with intuitive swipe controls'],
      ['Waterproof Rating', '5 m (16 ft) without housing'],
      ['Battery', 'Built-in 1255 mAh Enduro battery (up to 100 mins 4K recording)'],
      ['Mounting System', 'Built-in folding mounting fingers'],
      ['Dimensions (W x H x D)', '56.6 x 47.7 x 29.4 mm'],
      ['Weight', '86 g (camera + integrated battery)'],
    ],
    features: [
      'Featherweight 86-gram design allows unobtrusive helmet, vest, or body-worn mounting without operator fatigue',
      'One-button QuikCapture powers on the camera and immediately starts recording 4K video with a single press',
      'Submersible to 5m (16ft) for dependable operation in heavy rain, river crossings, and wet conditions',
      'Hydrophobic lens cover sheds water droplets to keep lenses clear during adverse outdoor weather',
      'Enduro battery technology ensures consistent recording performance across severe cold and hot weather',
    ],
    page: 52,
    subcategories: ['defense-surveillance', 'defense-field-operations'],
    categoryIds: ['defense'],
    tags: ['Action Cameras', 'Surveillance', 'Field Operations'],
  },
  {
    slug: 'gopro-lit-hero',
    aliases: ['lit-hero', 'gopro-lit', 'chdhf-132'],
    name: 'GoPro LIT HERO',
    brand: 'GoPro',
    category: 'defense',
    image: 'gopro-lit-hero',
    gallery: ['gopro-lit-hero'],
    label: 'ILLUMINATED 4K ACTION CAMERA WITH INTEGRATED LED FIELD LIGHT',
    summary: 'Ultra-compact tactical action camera featuring an integrated front-facing LED illumination light, 4K30 video capture, 12MP photos, touchscreen controls, and rugged all-weather waterproof casing for low-light night operations and close-quarters field documentation. (GoPro Model CHDHF-132-master).',
    specs: [
      ['Model Number', 'CHDHF-132-master'],
      ['Integrated Illumination', 'Built-in front high-output LED field light with multi-level brightness'],
      ['Video Resolution', 'Ultra HD 4K30, 1080p30, and 2.7K60 slow-motion (2x)'],
      ['Photo Resolution', '12 MP single photos'],
      ['Low-Light Capability', 'Forward LED illumination illuminates subjects up to 6 ft (2 m) in total darkness'],
      ['Display', 'Rear LCD touch screen with intuitive quick-tap control'],
      ['Waterproof Rating', 'Waterproof all-weather construction'],
      ['Battery', 'Built-in 1255 mAh Enduro battery'],
      ['Mounting System', 'Built-in folding mounting fingers'],
      ['Dimensions (W x H x D)', '56.6 x 48.4 x 29.45 mm'],
      ['Weight', '93 g (camera + integrated light + battery)'],
    ],
    features: [
      'Integrated forward LED light illuminates close-quarters subjects, tactical entryways, and equipment in low light',
      'Ultra-lightweight 93g profile engineered for weapon, helmet, or tactical vest attachment',
      '4K Ultra HD video recording provides crisp evidence and documentation clarity',
      'Simple one-touch operation allows rapid recording and light activation under pressure',
      'All-weather sealed enclosure ensures uninterrupted performance in mud, rain, and dusty environments',
    ],
    page: 52,
    subcategories: ['defense-surveillance', 'defense-field-operations'],
    categoryIds: ['defense'],
    tags: ['Action Cameras', 'Surveillance', 'Field Operations'],
  },
];
