export type Product = {
  slug: string; name: string; brand: string; category: string; image: string;
  gallery: string[]; label: string; summary: string; specs: [string, string][];
  features: string[]; page: number;
  subcategories?: string[];
  tags?: string[];
};

export const categories = [
  { id: 'forestry', name: 'Forestry & Wildlife', short: 'Into the wild.', subtitle: 'Observe without disturbing.', mission: 'Wildlife monitoring, habitat research and remote observation.', image: 'forest', code: 'BIO / 01' },
  { id: 'geology', name: 'Geological Equipment', short: 'Read the earth.', subtitle: 'Every layer tells a story.', mission: 'Map structures, measure bearings and document the ground beneath your feet.', image: 'geology', code: 'GEO / 02' },
  { id: 'surveying', name: 'Surveying & DGPS', short: 'Every point matters.', subtitle: 'Find your position. Define your ground.', mission: 'Field positioning and navigation. Talk to our team about DGPS and survey-specific requirements.', image: 'surveying', code: 'GNSS / 03' },
  { id: 'navigation', name: 'Mapping & Navigation', short: 'Know your next move.', subtitle: 'Confidence in every coordinate.', mission: 'Handheld GPS and dependable navigation instruments for unfamiliar ground.', image: 'navigation', code: 'NAV / 04' },
  { id: 'thermal', name: 'Thermal & Night Vision', short: 'Beyond the visible.', subtitle: 'A different way to see.', mission: 'Reveal heat signatures and observe in low light with dedicated field imaging equipment.', image: 'thermal', code: 'IR / 05' },
  { id: 'optics', name: 'Optics', short: 'Bring the distant closer.', subtitle: 'Clarity changes everything.', mission: 'High-definition binoculars and observation optics for detail at a distance.', image: 'optics', code: 'OPT / 06' },
  { id: 'inspection', name: 'Inspection / Borescope Systems', short: 'Reach the unseen.', subtitle: 'Answers in the smallest spaces.', mission: 'Articulating inspection cameras for engines, machinery and difficult-to-access spaces.', image: 'inspection', code: 'INS / 07' },
  { id: 'computing', name: 'Rugged Computing', short: 'Work beyond the office.', subtitle: 'Your field is your workspace.', mission: 'Rugged mobile computing for collecting, managing and using data on location.', image: 'computing', code: 'RUG / 08' },
  { id: 'communication', name: 'Field Communication', short: 'Keep your team connected.', subtitle: 'A clear line in challenging terrain.', mission: 'Portable radio equipment for coordinated operations in the field.', image: 'communication', code: 'COM / 09' },
] as const;

export const products: Product[] = [
  { slug:'vortex-viper-hd',name:'Viper® HD',brand:'Vortex Optics',category:'optics',image:'viper',gallery:['viper','viper-front'],label:'HD BINOCULARS',summary:'An HD optical system, rugged rubber armor and a comfortable field harness. A clear view of the details that matter.',specs:[['Available configurations','8×42 / 10×50 / 12×50'],['Optical system','High definition'],['Lens coating','XR™ fully multi-coated'],['Protection','ArmorTek®'],['Carry system','GlassPak harness included']],features:['HD glass for resolution and color fidelity','Phase-corrected roof prisms for contrast','Rubber armor for a secure grip','GlassPak chest harness for comfortable field carry'],page:5,subcategories:['optics-forestry'],tags:['Binoculars'] },
  { slug:'garmin-gpsmap-65s',name:'GPSMAP® 65s',brand:'Garmin',category:'navigation',image:'gpsmap',gallery:['gpsmap'],label:'MULTI-BAND GPS',summary:'Find your way in challenging environments with multi-band positioning, expanded satellite support and a sunlight-readable color display.',specs:[['Display','2.6-inch color'],['Positioning','Multi-band GNSS'],['Battery life','Up to 16 hours in GPS mode'],['Navigation','Built-in navigation sensors'],['Planning','Garmin Explore compatibility']],features:['Multi-band technology for challenging locations','Sunlight-readable color display','Built-in navigation sensors','Plan and organize with the Garmin Explore app'],page:12,subcategories:['forest-survey','field-expedition'],tags:['GPS/GNSS Devices','GPS'] },
  { slug:'hikmicro-lynx-lh25',name:'LYNX LH25 2.0',brand:'HIKMICRO',category:'thermal',image:'lynx',gallery:['lynx','lynx-side'],label:'THERMAL MONOCULAR',summary:'A compact thermal monocular that reveals subtle heat signatures, with a sensitive detector and a detailed OLED view.',specs:[['Detector resolution','384 × 288'],['Lens','25 mm, F1.0'],['Thermal sensitivity','NETD <20 mK'],['Detection range','Up to 1,200 m'],['Weight','275 g'],['Battery life','Up to 6.5 hours']],features:['12 μm detector with high thermal sensitivity','1024 × 768 OLED display','Replaceable rechargeable Li-ion battery','Compact and ergonomic field design'],page:40,subcategories:['wildlife-monitoring','optics-forestry'],tags:['Thermal Cameras'] },
  { slug:'browning-strike-force-pro-dcl',name:'Strike Force Pro DCL',brand:'Browning',category:'forestry',image:'browning',gallery:['browning'],label:'WILDLIFE TRAIL CAMERA',summary:'Dual camera lens technology captures the field by day and night, with a fast trigger for fleeting wildlife encounters.',specs:[['Image resolution','26 megapixels'],['Trigger speed','0.15 seconds'],['Flash range','Up to 130 ft'],['Viewing screen','1.5-inch color'],['Lens system','Dual camera lens technology']],features:['Separate lens technology optimized for day and night','Fast trigger for wildlife monitoring','On-camera color viewing screen','Long-range flash capability'],page:21,subcategories:['wildlife-monitoring'],tags:['Camera Traps'] },
  { slug:'brunton-geolite',name:'Geo Lite Transit',brand:'Brunton',category:'geology',image:'geolite-open',gallery:['geolite-open','geolite'],label:'GEOLOGICAL COMPASS',summary:'A baseplate compass with transit-style measurement, designed for bearings, strike and dip work in the field.',specs:[['Azimuth resolution','2°'],['Clinometer resolution','5°'],['Magnet','Brunton EverNorth'],['Measurement','Strike / dip / dip azimuth'],['Map tools','Protractor and magnifier']],features:['Transit-style direct-read azimuth system','Hinge clinometer for dip measurements','Bubble level for accurate strike measurement','Integrated protractor for plotting field data'],page:27,subcategories:['forest-survey'],tags:['Forestry Compasses'] },
  { slug:'panasonic-toughbook',name:'TOUGHBOOK FZ-55',brand:'Panasonic Toughbook',category:'computing',image:'toughbook',gallery:['toughbook'],label:'RUGGED FIELD COMPUTING',summary:'A modular laptop platform for demanding mobile work. Ask our team to configure a TOUGHBOOK around your field applications.',specs:[['Product family','Panasonic TOUGHBOOK'],['Catalogue model','FZ-55'],['Form factor','Rugged laptop'],['Configuration','Confirmed with your quotation']],features:['Built for mobile field workflows','Flexible configuration options','Suitable for field data collection and review','Project-specific configuration support'],page:47,subcategories:['field-expedition','forestry-software'],tags:['Rugged Tablets'] },
  { slug:'vortex-diamondback-hd',name:'Diamondback® HD',brand:'Vortex Optics',category:'optics',image:'diamondback',gallery:['diamondback','diamondback-side'],label:'HD BINOCULARS',summary:'Rugged observation optics with HD glass, protective lens coatings and a ready-to-deploy harness.',specs:[['Available configurations','8×42 / 10×50 / 10×42'],['Optical system','High definition'],['Lenses','Fully multi-coated'],['Protection','ArmorTek® coating'],['Carry system','GlassPak harness included']],features:['Phase correction for enhanced resolution','Rubber armor for a non-slip grip','Scratch-resistant exterior lens coating','Shock-resistant construction'],page:4,subcategories:['optics-forestry'],tags:['Binoculars'] },
  { slug:'garmin-montana-700',name:'Montana® 700',brand:'Garmin',category:'navigation',image:'montana',gallery:['montana'],label:'TOUCHSCREEN GPS',summary:'Large-format navigation for journeys on foot or by vehicle, combining a 5-inch touchscreen with outdoor navigation sensors.',specs:[['Display','5-inch touchscreen'],['Positioning','Multiple GNSS networks'],['Battery life','18+ hours in GPS mode'],['Navigation sensors','Altimeter, barometer, compass'],['Mapping','Routable roads and trails']],features:['Large touchscreen for clear map viewing','Rugged construction for outdoor navigation','ABC sensors for awareness in the field','Mapping support for roads and trails'],page:15,subcategories:['forest-survey','field-expedition'],tags:['GPS/GNSS Devices','GPS'] },
  { slug:'ralcam-h408b',name:'H408B Borescope',brand:'Ralcam',category:'inspection',image:'ralcam',gallery:['ralcam'],label:'ARTICULATING INSPECTION',summary:'Inspect confined spaces with an articulating camera and a dedicated display, built for automotive and machinery inspection.',specs:[['Display','4.3-inch'],['Camera resolution','1920 × 1080'],['Probe diameter','8.5 mm'],['Battery','Replaceable 2,600 mAh'],['Lighting','10 adjustable LEDs']],features:['Articulating lens for difficult viewing angles','Capture images and video','High-temperature protection','Dedicated screen for on-site inspections'],page:17 },
  { slug:'brutforce-field-radio',name:'Field Radio',brand:'Brutforce',category:'communication',image:'radio',gallery:['radio','radio-side'],label:'PORTABLE COMMUNICATION',summary:'Portable two-way communication to keep field teams in touch. Confirm the right radio configuration for your operating location with our team.',specs:[['Frequency range','446–446.2 MHz'],['Channels','16'],['Battery','2,600 mAh Li-ion'],['Charging port','Micro-USB'],['Operating temperature','−25°C to 55°C']],features:['16 channels for team coordination','Rechargeable Li-ion battery','Portable format for field carry','Simple controls and clear audio'],page:34,subcategories:['field-expedition'],tags:['Field Radios'] },
  { slug:'brunton-compro-transit',name:'ComPro Transit',brand:'Brunton',category:'geology',image:'compro',gallery:['compro'],label:'COMPOSITE POCKET TRANSIT',summary:'Traditional transit measurement in a lightweight composite body, with sighting tools and a precision magnetic system.',specs:[['Model','F-5008'],['Body','Lightweight composite'],['Magnet','Precision NdFeB disc'],['Needle settling','Induction dampening'],['Measurements','Bearings and vertical angles']],features:['Lightweight composite lid and base','Mirror for sighting and angle measurement','Short and long sights','Magnet designed to resist demagnetization'],page:30,subcategories:['forest-survey'],tags:['Forestry Compasses'] },
  { slug:'minox-nvd-650',name:'NVD 650',brand:'MINOX',category:'thermal',image:'minox',gallery:['minox','minox-back'],label:'DIGITAL NIGHT VISION',summary:'A digital monocular with an IR emitter and recording capability for observation in low-light field conditions.',specs:[['Optical magnification','6×'],['Digital magnification','5×'],['IR wavelength','850 nm'],['IR range','Up to 350 m'],['Use','Day and night']],features:['Built-in IR emitter','Night recording functionality','Rail for additional IR illumination','Daytime use supported'],page:45,subcategories:['wildlife-monitoring','optics-forestry'],tags:['Night Vision Devices'] },
  { slug:'suunto-mc2',name:'MC-2 Mirror Compass',brand:'Suunto',category:'navigation',image:'suunto',gallery:['suunto'],label:'PRECISION NAVIGATION',summary:'A sighting compass with a mirror, clinometer and adjustable declination correction for considered route finding.',specs:[['Needle','Jewel-bearing steel'],['Capsule','Liquid-filled'],['Declination','Adjustable correction'],['Measurement','Sighting and clinometer'],['Variant','Confirm hemisphere and scale']],features:['Sighting mirror and notch for bearings','Luminescent markings for low light','Baseplate with magnifying lens','Detachable snap-lock lanyard'],page:41,subcategories:['forest-survey','field-expedition'],tags:['Compasses','Forestry Compasses'] },
  { slug:'audiomoth',name:'AudioMoth',brand:'Open Acoustic Devices',category:'forestry',image:'audiomoth',gallery:['audiomoth','audiomoth-case'],label:'ACOUSTIC MONITORING',summary:'A compact full-spectrum acoustic logger for listening to the natural world, with an optional protective field case.',specs:[['Sample rate','Up to 384 kHz'],['Processor','EFM32 Gecko'],['Microphone','Analog MEMS'],['Protective option','IPX7 waterproof case']],features:['Full-spectrum acoustic logging','Compact field-deployment format','Protective case with compression O-ring','Case strap for straightforward installation'],page:44,subcategories:['wildlife-monitoring'],tags:['Acoustic Monitoring Devices'] },
  { slug:'hikmicro-e20-plus',name:'E20 Plus',brand:'HIKMICRO',category:'thermal',image:'e20',gallery:['e20','e20-side'],label:'SMARTPHONE THERMAL CAMERA',summary:'A lightweight thermal accessory for compatible Android phones, with USB-C connection and HIKMICRO Sight app support.',specs:[['Connection','USB Type-C'],['Power consumption','360 mW'],['Weight','26 g'],['Operating temperature','−10°C to 50°C'],['Protection level','IP40']],features:['Compact thermal module for mobile observation','Powered through the connected device','HIKMICRO Sight app compatibility','Lightweight 26 g design'],page:39,subcategories:['forest-fire'],tags:['Thermal Cameras'] },
];

export const brandDescriptions: Record<string,string> = {
  'Vortex Optics':'A closer connection to the world beyond. Discover HD binoculars and precision observation optics.',
  'Garmin':'Find your position and your next destination with purpose-built handheld navigation.',
  'Brunton':'Tools for reading the earth. Explore geological transits and precision field compasses.',
  'Browning':'Observe life in the wild with dedicated trail-camera technology.',
  'Brutforce':'Keep field teams connected with portable communication equipment.',
  'Ralcam':'Reach difficult spaces with articulating inspection camera systems.',
  'HIKMICRO':'See temperature and heat signatures with portable thermal imaging.',
  'Panasonic Toughbook':'Rugged computing platforms configured for mobile professional work.',
  'DGPS solutions':'Tell us your survey accuracy, correction network and field workflow requirements. Our team will help identify an appropriate DGPS solution.',
  'Suunto':'Dependable sighting compasses and navigation tools for the field.',
  'MINOX':'Digital night vision for observation beyond daylight.',
  'Open Acoustic Devices':'Compact acoustic loggers for ecological research and wildlife monitoring.',
};

export const finderOptions: Record<string, Record<string, string[]>> = {
  'Forestry & Wildlife': { 'Wildlife monitoring':['browning-strike-force-pro-dcl','audiomoth'], 'Long-distance observation':['vortex-viper-hd','vortex-diamondback-hd'], 'Night observation':['hikmicro-lynx-lh25','minox-nvd-650'] },
  'Surveying & Mapping': { 'Navigation':['garmin-gpsmap-65s','garmin-montana-700'], 'DGPS positioning':[], 'Field computing':['panasonic-toughbook'] },
  'Geology & Research': { 'Measurement':['brunton-geolite','brunton-compro-transit'], 'Navigation':['suunto-mc2','garmin-gpsmap-65s'], 'Data collection':['panasonic-toughbook'] },
  'Industrial Inspection': { 'Confined-space inspection':['ralcam-h408b'], 'Thermal observation':['hikmicro-e20-plus','hikmicro-lynx-lh25'], 'Field computing':['panasonic-toughbook'] },
  'Field Operations': { 'Team communication':['brutforce-field-radio'], 'Navigation':['garmin-gpsmap-65s','suunto-mc2'], 'Night observation':['hikmicro-lynx-lh25','minox-nvd-650'] },
};

export function findEquipment(industry: string, requirement: string) {
  const options = finderOptions[industry];
  if (!options || !Object.hasOwn(options, requirement)) throw new Error('Choose a valid industry and requirement.');
  return products.filter(p => options[requirement].includes(p.slug));
}
export const whatsAppUrl = (message: string) => `https://wa.me/919818320178?text=${encodeURIComponent(message)}`;
