export type Product = {
  slug: string; name: string; brand: string; category: string; image: string;
  gallery: string[]; label: string; summary: string; specs: [string, string][];
  features: string[]; page: number;
  subcategories?: string[];
  categoryIds?: string[];
  tags?: string[];
};

export const categories = [
  { id: 'forestry', name: 'Forestry & Wildlife', short: 'Into the wild.', subtitle: 'Observe without disturbing.', mission: 'Wildlife monitoring, habitat research and remote observation.', image: 'forest', code: 'BIO / 01' },
  { id: 'geology', name: 'Geological Products', short: 'Read the earth.', subtitle: 'Every layer tells a story.', mission: 'Map structures, measure bearings and document the ground beneath your feet.', image: 'geology', code: 'GEO / 02' },
  { id: 'surveying', name: 'Surveying & DGPS', short: 'Every point matters.', subtitle: 'Find your position. Define your ground.', mission: 'Field positioning and navigation. Talk to our team about DGPS and survey-specific requirements.', image: 'surveying', code: 'GNSS / 03' },
  { id: 'navigation', name: 'Mapping & Navigation', short: 'Know your next move.', subtitle: 'Confidence in every coordinate.', mission: 'Handheld GPS and dependable navigation instruments for unfamiliar ground.', image: 'navigation', code: 'NAV / 04' },
  { id: 'thermal', name: 'Thermal & Night Vision', short: 'Beyond the visible.', subtitle: 'A different way to see.', mission: 'Reveal heat signatures and observe in low light with dedicated field imaging products.', image: 'thermal', code: 'IR / 05' },
  { id: 'optics', name: 'Optics', short: 'Bring the distant closer.', subtitle: 'Clarity changes everything.', mission: 'High-definition binoculars and observation optics for detail at a distance.', image: 'optics', code: 'OPT / 06' },
  { id: 'inspection', name: 'Inspection / Borescope Systems', short: 'Reach the unseen.', subtitle: 'Answers in the smallest spaces.', mission: 'Articulating inspection cameras for engines, machinery and difficult-to-access spaces.', image: 'inspection', code: 'INS / 07' },
  { id: 'computing', name: 'Rugged Computing', short: 'Work beyond the office.', subtitle: 'Your field is your workspace.', mission: 'Rugged mobile computing for collecting, managing and using data on location.', image: 'computing', code: 'RUG / 08' },
  { id: 'communication', name: 'Field Communication', short: 'Keep your team connected.', subtitle: 'A clear line in challenging terrain.', mission: 'Portable radio products for coordinated operations in the field.', image: 'communication', code: 'COM / 09' },
  { id: 'defense', name: 'Defense & Paramilitary', short: 'Stay field ready.', subtitle: 'Awareness in every condition.', mission: 'Explore existing imaging, navigation, optics, communication and computing equipment for demanding field operations.', image: 'thermal', code: 'FLD / 10' },
  { id: 'mining', name: 'Mining & Geology', short: 'Read the terrain.', subtitle: 'Measure the ground.', mission: 'Explore existing geological instruments, mapping equipment, inspection tools and rugged computing for field work.', image: 'geology', code: 'GEO / 11' },
] as const;

export const products: Product[] = [
  // --- Existing Field Technology Products (Preserved & Cleaned of Legacy Subcategories) ---
  { slug:'vortex-viper-hd',name:'Viper® HD',brand:'Vortex Optics',category:'optics',image:'viper',gallery:['viper','viper-front'],label:'HD BINOCULARS',summary:'An HD optical system, rugged rubber armor and a comfortable field harness. A clear view of the details that matter.',specs:[['Available configurations','8×42 / 10×50 / 12×50'],['Optical system','High definition'],['Lens coating','XR™ fully multi-coated'],['Protection','ArmorTek®'],['Carry system','GlassPak harness included']],features:['HD glass for resolution and color fidelity','Phase-corrected roof prisms for contrast','Rubber armor for a secure grip','GlassPak chest harness for comfortable field carry'],page:5,subcategories:['defense-optics'],categoryIds:['optics','defense'],tags:['Binoculars'] },
  { slug:'garmin-gpsmap-65s',name:'Handheld GPS (GPSMAP® 65s)',brand:'Garmin',category:'navigation',image:'gpsmap',gallery:['gpsmap'],label:'MULTI-BAND GPS',summary:'Find your way in challenging environments with multi-band positioning, expanded satellite support and a sunlight-readable color display.',specs:[['Display','2.6-inch color'],['Positioning','Multi-band GNSS'],['Battery life','Up to 16 hours in GPS mode'],['Navigation','Built-in navigation sensors'],['Planning','Garmin Explore compatibility']],features:['Multi-band technology for challenging locations','Sunlight-readable color display','Built-in navigation sensors','Plan and organize with the Garmin Explore app'],page:12,subcategories:['gps-survey-mapping-products','defense-navigation','defense-field-operations','mining-field-mapping','mining-mapping','mining-distance'],categoryIds:['navigation','defense','mining','surveying'],tags:['GPS/GNSS Devices','GPS','Handheld GPS'] },
  { slug:'hikmicro-lynx-lh25',name:'LYNX LH25 2.0',brand:'HIKMICRO',category:'thermal',image:'lynx',gallery:['lynx','lynx-side'],label:'THERMAL MONOCULAR',summary:'A compact thermal monocular that reveals subtle heat signatures, with a sensitive detector and a detailed OLED view.',specs:[['Detector resolution','384 × 288'],['Lens','25 mm, F1.0'],['Thermal sensitivity','NETD <20 mK'],['Detection range','Up to 1,200 m'],['Weight','275 g'],['Battery life','Up to 6.5 hours']],features:['12 μm detector with high thermal sensitivity','1024 × 768 OLED display','Replaceable rechargeable Li-ion battery','Compact and ergonomic field design'],page:40,subcategories:['defense-thermal','defense-surveillance'],categoryIds:['thermal','defense'],tags:['Thermal Cameras','Thermal Monoculars'] },
  { slug:'browning-strike-force-pro-dcl',name:'Strike Force Pro DCL',brand:'Browning',category:'forestry',image:'browning',gallery:['browning'],label:'WILDLIFE TRAIL CAMERA',summary:'Dual camera lens technology captures the field by day and night, with a fast trigger for fleeting wildlife encounters.',specs:[['Image resolution','26 megapixels'],['Trigger speed','0.15 seconds'],['Flash range','Up to 130 ft'],['Viewing screen','1.5-inch color'],['Lens system','Dual camera lens technology']],features:['Separate lens technology optimized for day and night','Fast trigger for wildlife monitoring','On-camera color viewing screen','Long-range flash capability'],page:21,subcategories:['defense-surveillance'],categoryIds:['forestry','defense'],tags:['Camera Traps'] },
  { slug:'brunton-geolite',name:'Geo Lite Transit',brand:'Brunton',category:'geology',image:'geolite-open',gallery:['geolite-open','geolite'],label:'GEOLOGICAL COMPASS',summary:'A baseplate compass with transit-style measurement, designed for bearings, strike and dip work in the field.',specs:[['Azimuth resolution','2°'],['Clinometer resolution','5°'],['Magnet','Brunton EverNorth'],['Measurement','Strike / dip / dip azimuth'],['Map tools','Protractor and magnifier']],features:['Transit-style direct-read azimuth system','Hinge clinometer for dip measurements','Bubble level for accurate strike measurement','Integrated protractor for plotting field data'],page:27,subcategories:['geological-field-mapping','mining-field-mapping','mining-survey','mining-compasses'],categoryIds:['geology','mining'],tags:['Forestry Compasses','Geological Compasses / Pocket Transits'] },
  { slug:'panasonic-toughbook',name:'TOUGHBOOK FZ-55',brand:'Panasonic Toughbook',category:'computing',image:'toughbook',gallery:['toughbook'],label:'RUGGED FIELD COMPUTING',summary:'A modular laptop platform for demanding mobile work. Ask our team to configure a TOUGHBOOK around your field applications.',specs:[['Product family','Panasonic TOUGHBOOK'],['Catalogue model','FZ-55'],['Form factor','Rugged laptop'],['Configuration','Confirmed with your quotation']],features:['Built for mobile field workflows','Flexible configuration options','Suitable for field data collection and review','Project-specific configuration support'],page:47,subcategories:['defense-rugged','defense-field-operations','mining-rugged'],categoryIds:['computing','defense','mining'],tags:['Rugged Tablets'] },
  { slug:'vortex-diamondback-hd',name:'Diamondback® HD',brand:'Vortex Optics',category:'optics',image:'diamondback',gallery:['diamondback','diamondback-side'],label:'HD BINOCULARS',summary:'Rugged observation optics with HD glass, protective lens coatings and a ready-to-deploy harness.',specs:[['Available configurations','8×42 / 10×50 / 10×42'],['Optical system','High definition'],['Lenses','Fully multi-coated'],['Protection','ArmorTek® coating'],['Carry system','GlassPak harness included']],features:['Phase correction for enhanced resolution','Rubber armor for a non-slip grip','Scratch-resistant exterior lens coating','Shock-resistant construction'],page:4,subcategories:['defense-optics'],categoryIds:['optics','defense'],tags:['Binoculars'] },
  { slug:'garmin-montana-700',name:'Montana® 700',brand:'Garmin',category:'navigation',image:'montana',gallery:['montana'],label:'TOUCHSCREEN GPS',summary:'Large-format navigation for journeys on foot or by vehicle, combining a 5-inch touchscreen with outdoor navigation sensors.',specs:[['Display','5-inch touchscreen'],['Positioning','Multiple GNSS networks'],['Battery life','18+ hours in GPS mode'],['Navigation sensors','Altimeter, barometer, compass'],['Mapping','Routable roads and trails']],features:['Large touchscreen for clear map viewing','Rugged construction for outdoor navigation','ABC sensors for awareness in the field','Mapping support for roads and trails'],page:15,subcategories:['defense-navigation','defense-field-operations','mining-field-mapping','mining-mapping','mining-distance'],categoryIds:['navigation','defense','mining'],tags:['GPS/GNSS Devices','GPS'] },
  { slug:'ralcam-h408b',name:'H408B Borescope',brand:'Ralcam',category:'inspection',image:'ralcam',gallery:['ralcam'],label:'ARTICULATING INSPECTION',summary:'Inspect confined spaces with an articulating camera and a dedicated display, built for automotive and machinery inspection.',specs:[['Display','4.3-inch'],['Camera resolution','1920 × 1080'],['Probe diameter','8.5 mm'],['Battery','Replaceable 2,600 mAh'],['Lighting','10 adjustable LEDs']],features:['Articulating lens for difficult viewing angles','Capture images and video','High-temperature protection','Dedicated screen for on-site inspections'],page:17,subcategories:['mining-inspection'],categoryIds:['inspection','mining'] },
  { slug:'brutforce-field-radio',name:'Field Radio',brand:'Brutforce',category:'communication',image:'radio',gallery:['radio','radio-side'],label:'PORTABLE COMMUNICATION',summary:'Portable two-way communication to keep field teams in touch. Confirm the right radio configuration for your operating location with our team.',specs:[['Frequency range','446–446.2 MHz'],['Channels','16'],['Battery','2,600 mAh Li-ion'],['Charging port','Micro-USB'],['Operating temperature','−25°C to 55°C']],features:['16 channels for team coordination','Rechargeable Li-ion battery','Portable format for field carry','Simple controls and clear audio'],page:34,subcategories:['defense-communication','defense-field-operations'],categoryIds:['communication','defense'],tags:['Field Radios'] },
  { slug:'brunton-compro-transit',name:'Survey Compass (ComPro Transit F-5008)',brand:'Brunton',category:'geology',image:'compro',gallery:['compro'],label:'COMPOSITE POCKET TRANSIT',summary:'Traditional transit measurement in a lightweight composite body, with sighting tools and a precision magnetic system.',specs:[['Model','F-5008'],['Body','Lightweight composite'],['Magnet','Precision NdFeB disc'],['Needle settling','Induction dampening'],['Measurements','Bearings and vertical angles']],features:['Lightweight composite lid and base','Mirror for sighting and angle measurement','Short and long sights','Magnet designed to resist demagnetization'],page:30,subcategories:['gps-survey-mapping-products','geological-field-mapping','mining-field-mapping','mining-survey','mining-compasses'],categoryIds:['geology','mining','surveying'],tags:['Survey Compass','Forestry Compasses','Geological Compasses / Pocket Transits'] },
  { slug:'brunton-f-5012-axis',name:'F-5012 Axis Compass',brand:'Brunton',category:'geology',image:'geolite',gallery:['geolite','geolite-open'],label:'AXIS BASE PLATE COMPASS',summary:'A baseplate compass for strike, dip and bearing work, with direct-read azimuth, clinometer and Brunton EverNorth magnetic system.',specs:[['Azimuth resolution','2°'],['Clinometer resolution','5°'],['Magnet','Brunton EverNorth'],['Body','Durable ABS'],['Sighting','Direct-read sighting system']],features:['Direct-read azimuth and bearing system','Hinge clinometer for strike and dip measurement','Bubble level for accurate horizontal alignment','Integrated map magnifier and protractor'],page:27,subcategories:['geological-field-mapping','mining-field-mapping','mining-survey','mining-compasses'],categoryIds:['geology','mining'],tags:['Geological Compasses / Pocket Transits'] },
  { slug:'minox-nvd-650',name:'NVD 650',brand:'MINOX',category:'thermal',image:'minox',gallery:['minox','minox-back'],label:'DIGITAL NIGHT VISION',summary:'A digital monocular with an IR emitter and recording capability for observation in low-light field conditions.',specs:[['Optical magnification','6×'],['Digital magnification','5×'],['IR wavelength','850 nm'],['IR range','Up to 350 m'],['Use','Day and night']],features:['Built-in IR emitter','Night recording functionality','Rail for additional IR illumination','Daytime use supported'],page:45,subcategories:['defense-night','defense-surveillance'],categoryIds:['thermal','defense'],tags:['Night Vision Devices'] },
  { slug:'suunto-mc2',name:'MC-2 Mirror Compass',brand:'Suunto',category:'navigation',image:'suunto',gallery:['suunto'],label:'PRECISION NAVIGATION',summary:'A sighting compass with a mirror, clinometer and adjustable declination correction for considered route finding.',specs:[['Needle','Jewel-bearing steel'],['Capsule','Liquid-filled'],['Declination','Adjustable correction'],['Measurement','Sighting and clinometer'],['Variant','Confirm hemisphere and scale']],features:['Sighting mirror and notch for bearings','Luminescent markings for low light','Baseplate with magnifying lens','Detachable snap-lock lanyard'],page:41,subcategories:['defense-navigation','defense-field-operations'],categoryIds:['navigation','defense'],tags:['Compasses','Forestry Compasses'] },
  { slug:'audiomoth',name:'AudioMoth',brand:'Open Acoustic Devices',category:'forestry',image:'audiomoth',gallery:['audiomoth','audiomoth-case'],label:'ACOUSTIC MONITORING',summary:'A compact full-spectrum acoustic logger for listening to the natural world, with an optional protective field case.',specs:[['Sample rate','Up to 384 kHz'],['Processor','EFM32 Gecko'],['Microphone','Analog MEMS'],['Protective option','IPX7 waterproof case']],features:['Full-spectrum acoustic logging','Compact field-deployment format','Protective case with compression O-ring','Case strap for straightforward installation'],page:44,tags:['Acoustic Monitoring Devices'] },
  { slug:'hikmicro-e20-plus',name:'E20 Plus',brand:'HIKMICRO',category:'thermal',image:'e20',gallery:['e20','e20-side'],label:'SMARTPHONE THERMAL CAMERA',summary:'A lightweight thermal accessory for compatible Android phones, with USB-C connection and HIKMICRO Sight app support.',specs:[['Connection','USB Type-C'],['Power consumption','360 mW'],['Weight','26 g'],['Operating temperature','−10°C to 50°C'],['Protection level','IP40']],features:['Compact thermal module for mobile observation','Powered through the connected device','HIKMICRO Sight app compatibility','Lightweight 26 g design'],page:39,tags:['Thermal Cameras'] },

  // =========================================================================
  // 1. FOREST MEASUREMENT & INVENTORY (Subcategory ID: forest-measurement-inventory)
  // =========================================================================
  {
    slug: 'diameter-tape-dbh-tape',
    name: 'Diameter Tape / DBH Tape',
    brand: 'AFFORDA',
    category: 'forestry',
    image: 'placeholder',
    gallery: ['placeholder'],
    label: 'FORESTRY MEASUREMENT',
    summary: 'Specialized direct-reading diameter tape for measuring tree DBH (diameter at breast height) and circumference with precision field graduations.',
    specs: [['Measurement Type', 'Direct DBH & Linear Circumference'], ['Blade Material', 'Reinforced Woven Synthetic / Steel']],
    features: ['Direct diameter conversion scale from circumference', 'High-contrast graduations for legibility in dense shade', 'Rugged housing built for repeated forest cruiser deployment', 'Standard protocol tool for timber cruising and forest inventory'],
    page: 1,
    subcategories: ['forest-measurement-inventory'],
    categoryIds: ['forestry'],
    tags: ['Forest Measurement & Inventory', 'Diameter Tape']
  },
  {
    slug: 'digital-tree-caliper',
    name: 'Digital Tree Caliper',
    brand: 'AFFORDA',
    category: 'forestry',
    image: 'placeholder',
    gallery: ['placeholder'],
    label: 'ELECTRONIC INVENTORY',
    summary: 'Electronic tree diameter caliper designed for digital recording, rapid timber stand inventory, and log scaling in all weather conditions.',
    specs: [['Display', 'High-Contrast Digital LCD Screen'], ['Measurement', 'Tree Trunk Diameter & Log Scaling']],
    features: ['Electronic sensor for rapid diameter measurement capture', 'Rigid aluminum alloy beam engineered for rough forest terrain', 'Reduces manual transcription errors during cruise sampling', 'Compatible with digital forestry inventory workflows'],
    page: 1,
    subcategories: ['forest-measurement-inventory'],
    categoryIds: ['forestry'],
    tags: ['Forest Measurement & Inventory', 'Tree Calipers']
  },
  {
    slug: 'wheeler-caliper',
    name: 'Wheeler Caliper',
    brand: 'AFFORDA',
    category: 'forestry',
    image: 'placeholder',
    gallery: ['placeholder'],
    label: 'OPTICAL DENDROMETER',
    summary: 'Optical dendrometer instrument for measuring upper-stem diameters and standing tree taper directly from the ground without climbing.',
    specs: [['Instrument Class', 'Optical Caliper / Upper Stem Dendrometer'], ['Measurement Range', 'Standing Tree Stem Diameters at Height']],
    features: ['Measures upper stem diameters from ground distance', 'Eliminates climbing or destructive sampling during volume estimation', 'Precision optical sighting with calibrated scale', 'Compact and balanced for expedition forestry work'],
    page: 1,
    subcategories: ['forest-measurement-inventory'],
    categoryIds: ['forestry'],
    tags: ['Forest Measurement & Inventory']
  },
  {
    slug: 'tree-height-meter',
    name: 'Tree Height Meter',
    brand: 'AFFORDA',
    category: 'forestry',
    image: 'placeholder',
    gallery: ['placeholder'],
    label: 'HYPSOMETRIC TOOL',
    summary: 'Dedicated instrument for rapid, accurate estimation of standing tree heights, merchantable lengths, and canopy elevations in forest stands.',
    specs: [['Application', 'Canopy Elevation & Tree Height Mensuration'], ['Sight Type', 'Direct Optical Scale / Reticle']],
    features: ['Fast optical estimation of total and merchantable tree height', 'Pre-calculated scales for standard baseline survey distances', 'Rugged, lightweight housing designed for continuous cruising', 'Simple handheld operation with minimal field setup time'],
    page: 1,
    subcategories: ['forest-measurement-inventory'],
    categoryIds: ['forestry'],
    tags: ['Forest Measurement & Inventory', 'Tree Height']
  },
  {
    slug: 'clinometer',
    name: 'Clinometer',
    brand: 'AFFORDA',
    category: 'forestry',
    image: 'placeholder',
    gallery: ['placeholder'],
    label: 'SLOPE & HEIGHT METER',
    summary: 'Precision handheld optical clinometer for measuring heights, vertical angles, and slope gradients in timber stands and rugged terrain.',
    specs: [['Measurement Scales', 'Degrees / Percentage Slope'], ['Damping', 'Liquid-Damped Precision Bearing']],
    features: ['Dual-scale sighting for degrees and percent slope', 'Liquid-damped bearing for fast, stable settling in breezy conditions', 'Precision optical parallax-free card reading', 'Robust anodized alloy housing for outdoor field longevity'],
    page: 1,
    subcategories: ['forest-measurement-inventory'],
    categoryIds: ['forestry'],
    tags: ['Forest Measurement & Inventory', 'Clinometers']
  },
  {
    slug: 'hypsometer',
    name: 'Hypsometer',
    brand: 'AFFORDA',
    category: 'forestry',
    image: 'placeholder',
    gallery: ['placeholder'],
    label: 'CANOPY HEIGHT INSTRUMENT',
    summary: 'Hypsometer instrument designed for calculating total tree heights, crown clearance, and terrain angles from baseline stand distances.',
    specs: [['Measurement Function', 'Tree Height, Distance & Slope Angle'], ['Field Mode', 'Direct Calculation Display']],
    features: ['Integrated trigonometry solver for instantaneous height calculations', 'Allows single-operator height and crown clearance measurement', 'High-contrast sighting optics suitable for varying canopy light', 'Engineered for forest inventory and biometric timber cruises'],
    page: 1,
    subcategories: ['forest-measurement-inventory'],
    categoryIds: ['forestry'],
    tags: ['Forest Measurement & Inventory', 'Hypsometers']
  },
  {
    slug: 'laser-rangefinder',
    name: 'Laser Rangefinder',
    brand: 'AFFORDA',
    category: 'forestry',
    image: 'placeholder',
    gallery: ['placeholder'],
    label: 'DISTANCE MEASUREMENT',
    summary: 'High-precision laser distance meter for measuring stand baseline distances, tree offsets, and boundary positions in forestry and land survey.',
    specs: [['Measurement Mode', 'Laser Distance & Line-of-Sight Angle'], ['Application', 'Forestry Plot Measurement & Boundary Survey']],
    features: ['Instant laser measurement through forest understory and foliage', 'Calculates horizontal distance, tilt angle, and vertical elevation', 'Weather-sealed optical housing for demanding outdoor conditions', 'Reused across forest inventory and GPS/mapping workflows'],
    page: 1,
    subcategories: ['forest-measurement-inventory', 'gps-survey-mapping-products'],
    categoryIds: ['forestry', 'surveying'],
    tags: ['Forest Measurement & Inventory', 'GPS, Survey & Mapping Products', 'Laser Rangefinder']
  },
  {
    slug: 'relaskop',
    name: 'Relaskop',
    brand: 'AFFORDA',
    category: 'forestry',
    image: 'placeholder',
    gallery: ['placeholder'],
    label: 'VARIABLE PLOT SAMPLING',
    summary: 'Point sampling and relascope instrument for rapid determination of basal area per hectare, tree height, and timber stand volume.',
    specs: [['Sampling Method', 'Bitterlich Variable Plot / Angle Gauge'], ['Measurement', 'Basal Area Factor (BAF) & Form Class']],
    features: ['Automatic slope correction for accurate point sampling on hillsides', 'Direct determination of basal area factor per hectare', 'Measures upper stem diameter and tree heights reliably', 'The recognized international standard for angle-count forest cruising'],
    page: 1,
    subcategories: ['forest-measurement-inventory'],
    categoryIds: ['forestry'],
    tags: ['Forest Measurement & Inventory', 'Relaskop']
  },
  {
    slug: 'wedge-prism',
    name: 'Wedge Prism',
    brand: 'AFFORDA',
    category: 'forestry',
    image: 'placeholder',
    gallery: ['placeholder'],
    label: 'POINT SAMPLING PRISM',
    summary: 'Calibrated optical glass wedge prism for determining basal area in variable plot forest sampling and timber cruise tallies.',
    specs: [['Optical Type', 'Precision Ground Optical Glass'], ['Application', 'Basal Area Determination / Point Cruising']],
    features: ['Precision refraction angle calibrated for standard basal area factors', 'Ground optical glass supplied with protective field pouch', 'Fast boundary tree tallying for inventory cruisers', 'Compact, zero-battery field sampling tool for all environments'],
    page: 1,
    subcategories: ['forest-measurement-inventory'],
    categoryIds: ['forestry'],
    tags: ['Forest Measurement & Inventory', 'Wedge Prism']
  },
  {
    slug: 'densiometer',
    name: 'Densiometer',
    brand: 'AFFORDA',
    category: 'forestry',
    image: 'placeholder',
    gallery: ['placeholder'],
    label: 'CANOPY COVER GAUGE',
    summary: 'Spherical crown densiometer for measuring forest canopy cover, canopy closure percentage, and solar exposure in ecological research.',
    specs: [['Mirror Type', 'Spherical Mirrored Surface'], ['Grid', 'Engraved Crosshair Sampling Grid']],
    features: ['Rapid estimation of forest canopy closure percentage', 'Built-in leveling bubble for consistent horizontal readings', 'Protective durable field enclosure for outdoor survival', 'Widely adopted standard in habitat assessment and silviculture'],
    page: 1,
    subcategories: ['forest-measurement-inventory'],
    categoryIds: ['forestry'],
    tags: ['Forest Measurement & Inventory', 'Densiometer']
  },
  {
    slug: 'bark-gauge',
    name: 'Bark Gauge',
    brand: 'AFFORDA',
    category: 'forestry',
    image: 'placeholder',
    gallery: ['placeholder'],
    label: 'BARK THICKNESS GAUGE',
    summary: 'Hardened stainless steel gauge for measuring wood bark thickness to calculate true diameter inside bark (DIB) and wood volume.',
    specs: [['Material', 'Hardened Stainless Steel Probe'], ['Measurement Range', 'Depth Scale Graduations']],
    features: ['Sharp penetrating chisel edge to reach wood cambium cleanly', 'Direct-reading millimeter graduation collar', 'Comfortable ergonomic grip for dense and fibrous bark species', 'Essential for wood volume calculations and fire resistance studies'],
    page: 1,
    subcategories: ['forest-measurement-inventory'],
    categoryIds: ['forestry'],
    tags: ['Forest Measurement & Inventory', 'Bark Gauge']
  },
  {
    slug: 'increment-borer',
    name: 'Increment Borer',
    brand: 'AFFORDA',
    category: 'forestry',
    image: 'placeholder',
    gallery: ['placeholder'],
    label: 'DENDROCHRONOLOGY TOOL',
    summary: 'Hardened alloy steel increment borer for extracting core samples to assess tree age, annual growth increments, and wood soundness.',
    specs: [['Material', 'Hardened High-Grade Alloy Steel'], ['Core Extraction', 'Precision Extractor Spoon Included']],
    features: ['Extracts clean core samples without causing serious tree harm', 'Hardened cutting edge designed for hard and soft wood species', 'Complete set with handle, auger borer bit, and extractor spoon', 'Crucial tool for dendrochronology, pathology, and yield studies'],
    page: 1,
    subcategories: ['forest-measurement-inventory'],
    categoryIds: ['forestry'],
    tags: ['Forest Measurement & Inventory', 'Increment Borer']
  },
  {
    slug: 'tally-counter',
    name: 'Tally Counter',
    brand: 'AFFORDA',
    category: 'forestry',
    image: 'placeholder',
    gallery: ['placeholder'],
    label: 'INVENTORY TALLY',
    summary: 'Mechanical four-digit tally counter for stand tree counting, regeneration seedling surveys, and wildlife transect counts.',
    specs: [['Count Capacity', '0000 to 9999'], ['Reset Mechanism', 'Instant Rotary Zero-Reset Knob']],
    features: ['Positive tactile thumb click for accurate count registration', 'Chrome-plated metal casing with finger ring for field security', 'Instant rotary reset knob to zero counts between plots', 'Standard tool for regenerative seedling surveys and forest enumeration'],
    page: 1,
    subcategories: ['forest-measurement-inventory'],
    categoryIds: ['forestry'],
    tags: ['Forest Measurement & Inventory', 'Tally Counter']
  },
  {
    slug: 'loggers-tape',
    name: 'Logger’s Tape',
    brand: 'AFFORDA',
    category: 'forestry',
    image: 'placeholder',
    gallery: ['placeholder'],
    label: 'AUTO-REWIND TAPE',
    summary: 'Heavy-duty automatic rewind tape with release hook for measuring log lengths and tree diameters in forest harvesting operations.',
    specs: [['Blade Type', 'Nylon-Coated Spring Steel'], ['Mechanism', 'Heavy-Duty Spring Return / Release Hook']],
    features: ['Automatic spring recoil for efficient single-worker operation', 'Combination linear length and diameter scale graduations', 'Shatterproof aluminum alloy casing with belt clip', 'Replaceable blade and release nail for harsh forestry logging'],
    page: 1,
    subcategories: ['forest-measurement-inventory'],
    categoryIds: ['forestry'],
    tags: ['Forest Measurement & Inventory', 'Logger’s Tape']
  },
  {
    slug: 'measuring-tape',
    name: 'Measuring Tape',
    brand: 'AFFORDA',
    category: 'forestry',
    image: 'placeholder',
    gallery: ['placeholder'],
    label: 'FIELD SURVEY TAPE',
    summary: 'Open-reel fiberglass field measuring tape for laying out sample plots, cruise lines, and boundary transects in rugged outdoor terrain.',
    specs: [['Blade Construction', 'High-Tensile Woven Fiberglass'], ['Reel Type', 'High-Impact Open Reel with Rapid Rewind']],
    features: ['Non-conductive, stretch-resistant fiberglass blade', 'Double-sided markings in metric and imperial units', 'Open-reel design sheds mud, debris, and forest ground moisture', 'Anchor spike and folding winding arm for easy field handling'],
    page: 1,
    subcategories: ['forest-measurement-inventory'],
    categoryIds: ['forestry'],
    tags: ['Forest Measurement & Inventory', 'Measuring Tape']
  },

  // =========================================================================
  // 2. GPS, SURVEY & MAPPING PRODUCTS (Subcategory ID: gps-survey-mapping-products)
  // =========================================================================
  {
    slug: 'professional-gnss-receiver',
    name: 'Professional GNSS Receiver',
    brand: 'AFFORDA',
    category: 'surveying',
    image: 'placeholder',
    gallery: ['placeholder'],
    label: 'SURVEY-GRADE GNSS',
    summary: 'Multi-constellation, multi-frequency GNSS receiver engineered for survey-grade geospatial data collection in challenging outdoor terrain.',
    specs: [['Tracking Constellations', 'GPS, GLONASS, Galileo, BeiDou, QZSS'], ['Form Factor', 'Integrated Smart Antenna & Receiver']],
    features: ['Multi-frequency tracking for reliable positioning under forest canopy', 'Rugged IP67/IP68 weatherproofing against heavy rain and dust', 'Wireless Bluetooth and UHF link for rover/base configurations', 'Engineered for GIS data capture, cadastral, and boundary surveys'],
    page: 1,
    subcategories: ['gps-survey-mapping-products'],
    categoryIds: ['surveying', 'forestry'],
    tags: ['GPS, Survey & Mapping Products', 'GNSS Receiver']
  },
  {
    slug: 'rtk-dgps',
    name: 'RTK / DGPS',
    brand: 'AFFORDA',
    category: 'surveying',
    image: 'placeholder',
    gallery: ['placeholder'],
    label: 'HIGH-PRECISION POSITIONING',
    summary: 'Real-Time Kinematic (RTK) and Differential GPS positioning system delivering instant centimeter-level accuracy for land and forest mapping.',
    specs: [['Correction Type', 'RTK / SBAS / Differential DGPS'], ['Accuracy Grade', 'Centimeter-Level Real-Time Precision']],
    features: ['Real-time correction calculation via base station or NTRIP network', 'Rapid satellite fix initialization in complex open and semi-canopy fields', 'Seamless integration with survey data controllers and GIS software', 'Supplied as complete rover or base/rover field package'],
    page: 1,
    subcategories: ['gps-survey-mapping-products'],
    categoryIds: ['surveying', 'forestry'],
    tags: ['GPS, Survey & Mapping Products', 'RTK', 'DGPS']
  },
  {
    slug: 'sub-meter-gps',
    name: 'Sub-meter GPS',
    brand: 'AFFORDA',
    category: 'surveying',
    image: 'placeholder',
    gallery: ['placeholder'],
    label: 'GIS MAPPING GPS',
    summary: 'Rugged handheld receiver GPS system engineered for sub-meter mapping accuracy in natural resource and forestry GIS applications.',
    specs: [['Positioning Accuracy', 'Sub-Meter Real-Time / Post-Processed'], ['Application', 'Forestry GIS, Asset Inventory & Mapping']],
    features: ['Sub-meter positional precision for asset and boundary mapping', 'Optimized multi-path rejection technology for tree cover environments', 'All-day battery endurance for extended field deployments', 'Direct export to standard GIS shapefiles and geodatabases'],
    page: 1,
    subcategories: ['gps-survey-mapping-products'],
    categoryIds: ['surveying', 'forestry'],
    tags: ['GPS, Survey & Mapping Products', 'Sub-meter GPS']
  },
  {
    slug: 'centimeter-mm-accuracy-gnss',
    name: 'Centimeter / mm-accuracy GNSS',
    brand: 'AFFORDA',
    category: 'surveying',
    image: 'placeholder',
    gallery: ['placeholder'],
    label: 'GEODETIC GNSS',
    summary: 'High-end geodetic GNSS receiver system capable of millimeter static and centimeter kinematic baseline precision in boundary surveys.',
    specs: [['Measurement Class', 'Geodetic / High-Precision Survey'], ['Kinematic Accuracy', 'Centimeter / Millimeter Baseline Precision']],
    features: ['Dual-frequency / triple-frequency multi-constellation engine', 'Advanced multipath mitigation for steep terrain and dense margins', 'Internal tilt compensation for non-vertical pole measurements', 'Ideal for geodetic control networks, dam monitoring, and civil boundaries'],
    page: 1,
    subcategories: ['gps-survey-mapping-products'],
    categoryIds: ['surveying', 'forestry'],
    tags: ['GPS, Survey & Mapping Products', 'GNSS']
  },
  {
    slug: 'electronic-data-collector',
    name: 'Electronic Data Collector',
    brand: 'AFFORDA',
    category: 'computing',
    image: 'placeholder',
    gallery: ['placeholder'],
    label: 'FIELD CONTROLLER',
    summary: 'Rugged field computer and survey controller featuring a sunlight-readable display, physical keypad, and specialized survey interface.',
    specs: [['Operating System', 'Rugged Field OS / Android / Windows'], ['Enclosure', 'IP67 Submersible & Shockproof']],
    features: ['Sunlight-readable touchscreen operable with gloves and stylus', 'Direct connectivity to GNSS receivers, total stations, and laser sensors', 'Long-life hot-swappable batteries for uninterrupted field shifts', 'Drop-tested against concrete in harsh field conditions'],
    page: 1,
    subcategories: ['gps-survey-mapping-products'],
    categoryIds: ['computing', 'surveying'],
    tags: ['GPS, Survey & Mapping Products', 'Electronic Data Collector']
  },
  {
    slug: 'digital-compass',
    name: 'Digital Compass',
    brand: 'AFFORDA',
    category: 'navigation',
    image: 'placeholder',
    gallery: ['placeholder'],
    label: 'ELECTRONIC BEARING',
    summary: 'Electronic handheld digital compass with tilt compensation, magnetic declination adjustment, and backlit digital bearing display.',
    specs: [['Azimuth Accuracy', 'Digital Bearing Resolution'], ['Sensors', '3-Axis Electronic Compass & Tilt Sensor']],
    features: ['Accurate digital heading readouts with tilt compensation', 'Automatic local magnetic declination adjustment', 'Backlit LCD display for low-light and night operations', 'Built-in electronic clinometer for slope angles'],
    page: 1,
    subcategories: ['gps-survey-mapping-products'],
    categoryIds: ['navigation', 'forestry'],
    tags: ['GPS, Survey & Mapping Products', 'Digital Compass']
  },
  {
    slug: 'staff-compass',
    name: 'Staff Compass',
    brand: 'AFFORDA',
    category: 'surveying',
    image: 'placeholder',
    gallery: ['placeholder'],
    label: 'FORESTRY SURVEY COMPASS',
    summary: 'Staff-mounted forestry survey compass with sighting vanes and ball-and-socket tripod/staff mount for forest boundary traverses.',
    specs: [['Mount Type', 'Jacob Staff / Ball & Socket Tripod Mount'], ['Compass Dial', 'Full 360° Azimuth or Quadrant Graduations']],
    features: ['Folding sighting vanes for precise forest line-of-sight sighting', 'Needle lifter mechanism to protect pivot jewel during transport', 'Liquid dampening or induction dampening for quick needle settle', 'The historical standard for timber boundary surveys and traverses'],
    page: 1,
    subcategories: ['gps-survey-mapping-products'],
    categoryIds: ['surveying', 'forestry'],
    tags: ['GPS, Survey & Mapping Products', 'Staff Compass']
  },
  {
    slug: 'altimeter',
    name: 'Altimeter',
    brand: 'AFFORDA',
    category: 'navigation',
    image: 'placeholder',
    gallery: ['placeholder'],
    label: 'BAROMETRIC ALTIMETER',
    summary: 'Precision barometric altimeter and barometer for measuring absolute elevation, contour mapping, and microclimate pressure changes.',
    specs: [['Sensor Type', 'Precision Aneroid / Electronic Barometric Sensor'], ['Scale Resolution', 'High-Resolution Altitude & Pressure']],
    features: ['Calibrated elevation tracking for field topography and contour mapping', 'Barometric pressure indicator for weather trend monitoring', 'Shock-resistant casing with temperature compensation', 'Zero-reset ring for relative height difference calculations'],
    page: 1,
    subcategories: ['gps-survey-mapping-products'],
    categoryIds: ['navigation', 'forestry'],
    tags: ['GPS, Survey & Mapping Products', 'Altimeter']
  },
  {
    slug: 'total-station',
    name: 'Total Station',
    brand: 'AFFORDA',
    category: 'surveying',
    image: 'placeholder',
    gallery: ['placeholder'],
    label: 'OPTICAL TOTAL STATION',
    summary: 'Electronic total station integrating electronic theodolite, optical distance measurement (EDM), and onboard geospatial logging.',
    specs: [['Angle Accuracy', 'High-Precision Angle Resolution'], ['EDM Range', 'Reflectorless & Prism Distance Measurement']],
    features: ['Reflectorless laser EDM for hard-to-reach terrain and tree heights', 'Precision dual-axis compensator for automatic level correction', 'Onboard survey software for topographic traverses and stakeout', 'Rugged optical and electronic construction for environmental resistance'],
    page: 1,
    subcategories: ['gps-survey-mapping-products'],
    categoryIds: ['surveying'],
    tags: ['GPS, Survey & Mapping Products', 'Total Station']
  },
  {
    slug: 'automatic-level',
    name: 'Automatic Level',
    brand: 'AFFORDA',
    category: 'surveying',
    image: 'placeholder',
    gallery: ['placeholder'],
    label: 'OPTICAL LEVELING',
    summary: 'Self-leveling optical level with magnetic damped compensator for establishing accurate horizontal grade lines and elevation profiles.',
    specs: [['Magnification', 'Optical Telescope Optics'], ['Compensator', 'Magnetic Damped Automatic Compensator']],
    features: ['Automatic compensator ensures line of sight remains horizontal', 'High-grade coated optics for bright, sharp reticle viewing', 'Endless horizontal drive knobs for smooth and precise targeting', 'Sealed water-resistant housing for field engineering and survey'],
    page: 1,
    subcategories: ['gps-survey-mapping-products'],
    categoryIds: ['surveying'],
    tags: ['GPS, Survey & Mapping Products', 'Automatic Level']
  },
  {
    slug: 'survey-tripod',
    name: 'Survey Tripod',
    brand: 'AFFORDA',
    category: 'surveying',
    image: 'placeholder',
    gallery: ['placeholder'],
    label: 'INSTRUMENT MOUNT',
    summary: 'Heavy-duty survey tripod with standard 5/8" threaded head for total stations, automatic levels, and GNSS base station masts.',
    specs: [['Construction', 'Heavy-Duty Aluminum / Fiberglass Composite'], ['Mounting Thread', 'Standard 5/8" × 11 Instrument Fastener']],
    features: ['Stable wide-stance legs with hardened steel ground points', 'Quick-release clamp system for rapid height adjustments', 'Torsion-resistant head for maximum stability under high-magnification instruments', 'Includes shoulder carry strap for cross-country field transport'],
    page: 1,
    subcategories: ['gps-survey-mapping-products'],
    categoryIds: ['surveying'],
    tags: ['GPS, Survey & Mapping Products', 'Survey Tripod']
  },
  {
    slug: 'measuring-rod',
    name: 'Measuring Rod',
    brand: 'AFFORDA',
    category: 'surveying',
    image: 'placeholder',
    gallery: ['placeholder'],
    label: 'TELESCOPIC LEVELING STAFF',
    summary: 'Telescopic leveling staff / measuring rod for elevation determinations, clearance heights, and topographic cross-sections.',
    specs: [['Graduations', 'High-Contrast E-Scale / Millimeter Graduations'], ['Construction', 'Non-Conductive Telescopic Sections']],
    features: ['Spring-loaded locking buttons secure extended sections firmly', 'High-visibility markings resistant to abrasion and sunlight', 'Includes circular leveling bubble to ensure vertical alignment', 'Compact retracted length for convenient vehicle or field carry'],
    page: 1,
    subcategories: ['gps-survey-mapping-products'],
    categoryIds: ['surveying'],
    tags: ['GPS, Survey & Mapping Products', 'Measuring Rod']
  },
  {
    slug: 'plot-markers',
    name: 'Plot Markers',
    brand: 'AFFORDA',
    category: 'surveying',
    image: 'placeholder',
    gallery: ['placeholder'],
    label: 'BOUNDARY MARKERS',
    summary: 'Permanent field boundary markers, aluminum identification tags, and ground monuments for forestry sample plots and property corners.',
    specs: [['Material', 'Corrosion-Resistant Cast Aluminum / Polyurethane'], ['Type', 'Ground Monument Caps & Whiskers']],
    features: ['Stamps or scribes easily for custom plot numbering and identifiers', 'Resistant to corrosion, soil acidity, and extreme weather', 'Bright color options for rapid relocation during recurring monitoring', 'Anchor-pronged design resists displacement by wildlife or ground movement'],
    page: 1,
    subcategories: ['gps-survey-mapping-products'],
    categoryIds: ['surveying', 'forestry'],
    tags: ['GPS, Survey & Mapping Products', 'Plot Markers']
  },
  {
    slug: 'flagging-tape',
    name: 'Flagging Tape',
    brand: 'AFFORDA',
    category: 'surveying',
    image: 'placeholder',
    gallery: ['placeholder'],
    label: 'HIGH-VISIBILITY MARKING',
    summary: 'Fluorescent weather-resistant PVC flagging tape for delineating survey lines, boundary points, and timber harvest boundaries.',
    specs: [['Material', 'Weatherproof Non-Adhesive PVC Film'], ['Visibility Grade', 'Fluorescent High-Visibility Neon']],
    features: ['High-visibility neon colors distinguishable through dense vegetation', 'Remains supple and tear-resistant in sub-zero and humid weather', 'Non-toxic formulation safe for natural forest environments', 'Easily tied and flagged by hand without specialized dispensers'],
    page: 1,
    subcategories: ['gps-survey-mapping-products'],
    categoryIds: ['surveying', 'forestry'],
    tags: ['GPS, Survey & Mapping Products', 'Flagging Tape']
  },
  {
    slug: 'field-data-recorder',
    name: 'Field Data Recorder',
    brand: 'AFFORDA',
    category: 'computing',
    image: 'placeholder',
    gallery: ['placeholder'],
    label: 'RUGGED DATA TERMINAL',
    summary: 'Electronic handheld field data terminal designed for recording biometric cruise data, timber tallies, and GPS coordinates on location.',
    specs: [['Ingress Protection', 'IP67 Dust & Water Immersion Sealed'], ['Input Options', 'Physical Keypad & Multi-Touch Glove Screen']],
    features: ['Integrated alphanumeric keypad for rapid data entry without looking', 'Extreme battery endurance lasting multiple operational field shifts', 'Direct connectivity to digital calipers, GPS, and electronic sensors', 'Encrypted local storage with cloud synchronization upon network return'],
    page: 1,
    subcategories: ['gps-survey-mapping-products'],
    categoryIds: ['computing', 'surveying'],
    tags: ['GPS, Survey & Mapping Products', 'Field Data Recorder']
  },

  // =========================================================================
  // 3. FOREST FIRE-FIGHTING PRODUCTS (Subcategory ID: forest-fire-fighting-products)
  // =========================================================================
  {
    slug: 'backpack-fire-pump',
    name: 'Backpack Fire Pump',
    brand: 'AFFORDA',
    category: 'forestry',
    image: 'placeholder',
    gallery: ['placeholder'],
    label: 'WILDFIRE SUPPRESSION',
    summary: 'Ergonomic collapsible or rigid tank backpack fire pump with double-action brass slide pump for wildfire mop-up and initial attack.',
    specs: [['Tank Capacity', '19–20 Liters (5 Gallons)'], ['Pump Mechanism', 'Handheld Dual-Action Brass Trombone Pump']],
    features: ['Padded shoulder straps and lumbar support for long wilderness pack-ins', 'Dual-action brass pump produces solid stream or spray pattern', 'Heavy-duty puncture-resistant ballistic polymer or canvas tank', 'Quick-fill opening with removable debris strainer screen'],
    page: 1,
    subcategories: ['forest-fire-fighting-products'],
    categoryIds: ['forestry'],
    tags: ['Forest Fire-Fighting Products', 'Backpack Fire Pump']
  },
  {
    slug: 'portable-fire-pump',
    name: 'Portable Fire Pump',
    brand: 'AFFORDA',
    category: 'forestry',
    image: 'placeholder',
    gallery: ['placeholder'],
    label: 'HIGH-PRESSURE PUMP',
    summary: 'Engine-driven high-pressure centrifugal portable fire pump designed for wildland initial attack and uphill water relay delivery.',
    specs: [['Engine Type', 'High-Output 4-Stroke OHV Engine'], ['Discharge Pressure', 'High-Pressure Centrifugal Flow']],
    features: ['Compact tubular carry frame for wilderness transport', 'Produces high pressure required for long hose lays and uphill elevation', 'Compatible with standard wildland quick-connect fittings and suction hoses', 'Reliable recoil start with low-oil shutdown protection'],
    page: 1,
    subcategories: ['forest-fire-fighting-products'],
    categoryIds: ['forestry'],
    tags: ['Forest Fire-Fighting Products', 'Portable Fire Pump']
  },
  {
    slug: 'fire-rake',
    name: 'Fire Rake',
    brand: 'AFFORDA',
    category: 'forestry',
    image: 'placeholder',
    gallery: ['placeholder'],
    label: 'FIRELINE HAND TOOL',
    summary: 'Council-style fire rake with triangular tempered steel mower teeth for cutting roots and raking duff to mineral soil along containment lines.',
    specs: [['Head Type', 'Replaceable Tempered Spring-Steel Triangular Teeth'], ['Handle Material', 'High-Strength Fiberglass / Ash Wood']],
    features: ['Self-sharpening triangular teeth easily cut brush, briars, and roots', 'Riveted or bolted teeth can be individually replaced if damaged', 'Long reach handle permits vigorous raking from standing position', 'Essential standard hand tool for clearing containment firelines'],
    page: 1,
    subcategories: ['forest-fire-fighting-products'],
    categoryIds: ['forestry'],
    tags: ['Forest Fire-Fighting Products', 'Fire Rake']
  },
  {
    slug: 'fire-swatter',
    name: 'Fire Swatter',
    brand: 'AFFORDA',
    category: 'forestry',
    image: 'placeholder',
    gallery: ['placeholder'],
    label: 'GRASS FIRE TOOL',
    summary: 'Flexible vulcanized rubber flap swatter for smothering surface flames and grass fires along wildfire containment perimeters.',
    specs: [['Flap Material', 'Flame-Resistant Heavy-Duty Vulcanized Rubber'], ['Handle', 'Reinforced Hardwood or Fiberglass Handle']],
    features: ['Smothers oxygen from creeping ground fires and grass fuels', 'Durable flame-resistant flap withstands repeated contact with hot embers', 'Reinforced metal fastening bracket prevents head separation', 'Ideal for fast suppression of light fuels without water consumption'],
    page: 1,
    subcategories: ['forest-fire-fighting-products'],
    categoryIds: ['forestry'],
    tags: ['Forest Fire-Fighting Products', 'Fire Swatter']
  },
  {
    slug: 'pulaski-forestry-axe',
    name: 'Pulaski Forestry Axe',
    brand: 'AFFORDA',
    category: 'forestry',
    image: 'placeholder',
    gallery: ['placeholder'],
    label: 'DUAL-PURPOSE AXE / ADZE',
    summary: 'Iconic wildland firefighting combination tool featuring a single-bit axe blade on one side and a narrow trenching adze grub hoe on the other.',
    specs: [['Head Weight', 'Forged High-Carbon Steel'], ['Tool Functions', 'Cutting Axe Bit & Grubbing Trenching Mattock']],
    features: ['Dual-sided head chops deadfall logs and grubs roots simultaneously', 'Forged high-carbon steel head heat-treated for edge retention', 'Reinforced handle eye designed to resist high impact forces', 'Indispensable primary hand tool for wildland fire crews worldwide'],
    page: 1,
    subcategories: ['forest-fire-fighting-products'],
    categoryIds: ['forestry'],
    tags: ['Forest Fire-Fighting Products', 'Pulaski Axe']
  },
  {
    slug: 'forestry-axe',
    name: 'Forestry Axe',
    brand: 'AFFORDA',
    category: 'forestry',
    image: 'placeholder',
    gallery: ['placeholder'],
    label: 'FELLING & LIMBING AXE',
    summary: 'Balanced timber axe designed for clearing brush, limbing fallen timber, and fireline fuel break construction in thick forest stands.',
    specs: [['Blade Forging', 'Drop-Forged High Carbon Tool Steel'], ['Handle Pattern', 'Ergonomic Hickory / Impact Fiberglass']],
    features: ['Hand-ground cutting edge for efficient timber penetration', 'Balanced weight distribution for maximum felling leverage', 'Hardened poll suitable for driving polymer felling wedges', 'Supplied with heavy-duty blade edge sheath'],
    page: 1,
    subcategories: ['forest-fire-fighting-products'],
    categoryIds: ['forestry'],
    tags: ['Forest Fire-Fighting Products', 'Forestry Axe']
  },
  {
    slug: 'mcleod-tool',
    name: 'McLeod Tool',
    brand: 'AFFORDA',
    category: 'forestry',
    image: 'placeholder',
    gallery: ['placeholder'],
    label: 'RAKE & HOE COMBINATION',
    summary: 'Combination rake and hoe fireline tool featuring a broad scraping hoe on one side and heavy tines on the opposite side.',
    specs: [['Blade Configuration', 'Combination Hoe Blade & Coarse Raking Teeth'], ['Construction', 'Heavy-Gauge Heat-Treated Carbon Steel']],
    features: ['Rakes duff, pine needles, and brush while simultaneously hoeing soil', 'Beveled scraping edge easily cuts through soil to bare mineral dirt', 'Heavy-duty ferrule and socket connection for rigorous leverage', 'Standard tool of initial attack fireline squads'],
    page: 1,
    subcategories: ['forest-fire-fighting-products'],
    categoryIds: ['forestry'],
    tags: ['Forest Fire-Fighting Products', 'McLeod Tool']
  },
  {
    slug: 'fire-beater',
    name: 'Fire Beater',
    brand: 'AFFORDA',
    category: 'forestry',
    image: 'placeholder',
    gallery: ['placeholder'],
    label: 'FIRE SUPPRESSION BEATER',
    summary: 'Heavy-duty industrial rubber beater tool designed to suppress low-intensity brush, heather, and undergrowth fires.',
    specs: [['Beater Surface', 'Industrial Grade Heavy Rubberized Fabric'], ['Handle Length', 'Long Outreach Fiberglass / Hardwood Handle']],
    features: ['Rapid flame suffocation on advancing ground fires and grass fronts', 'Extended reach protects firefighter from radiant heat exposure', 'Flexible construction prevents fatigue during continuous beating action', 'Corrosion-proof hardware built for demanding outdoor storage'],
    page: 1,
    subcategories: ['forest-fire-fighting-products'],
    categoryIds: ['forestry'],
    tags: ['Forest Fire-Fighting Products', 'Fire Beater']
  },
  {
    slug: 'drip-torch',
    name: 'Drip Torch',
    brand: 'AFFORDA',
    category: 'forestry',
    image: 'placeholder',
    gallery: ['placeholder'],
    label: 'PRESCRIBED BURNING',
    summary: 'Heavy-gauge aluminum backfiring drip torch with reversible burner spout and anti-flashback loop for controlled backburns.',
    specs: [['Fuel Capacity', 'Standard 1.25 Gallon (approx. 5 Liters)'], ['Safety System', 'Check Valve & Anti-Flashback Breather Loop']],
    features: ['Anti-flashback loop prevents fire from traveling inside the reservoir', 'Reversible spout stores securely inside canister during transport', 'Dispenses consistent burning fuel mixture reliably along firelines', 'Approved construction for prescribed burns and backfiring operations'],
    page: 1,
    subcategories: ['forest-fire-fighting-products'],
    categoryIds: ['forestry'],
    tags: ['Forest Fire-Fighting Products', 'Drip Torch']
  },
  {
    slug: 'fire-shelter',
    name: 'Fire Shelter',
    brand: 'AFFORDA',
    category: 'forestry',
    image: 'placeholder',
    gallery: ['placeholder'],
    label: 'EMERGENCY PROTECTION',
    summary: 'Multi-layer aluminum foil and woven silica emergency deployment shelter protecting wildland firefighters from radiant heat entrapment.',
    specs: [['Construction', 'Multi-Layer Foil & Silica Composite'], ['Protection Factor', 'High Reflectivity Against Radiant Heat Flux']],
    features: ['Reflects radiant heat and traps breathable air during burnovers', 'Rapid deployment pull-straps for emergency sheltering in seconds', 'Complete with durable weather-resistant PVC field carry case', 'Standard emergency equipment for wildland fire personnel'],
    page: 1,
    subcategories: ['forest-fire-fighting-products'],
    categoryIds: ['forestry'],
    tags: ['Forest Fire-Fighting Products', 'Fire Shelter']
  },
  {
    slug: 'fire-weather-meter',
    name: 'Fire Weather Meter',
    brand: 'AFFORDA',
    category: 'forestry',
    image: 'placeholder',
    gallery: ['placeholder'],
    label: 'FIRE BEHAVIOR WEATHER',
    summary: 'Compact handheld electronic weather meter calculating relative humidity, wind speed, temperature, and fine fuel moisture on scene.',
    specs: [['Sensors', 'Impeller Wind Speed, Capacitive Humidity & Temperature'], ['Calculations', 'Fine Fuel Moisture (FDFM) & Probability of Ignition']],
    features: ['Calculates critical fire behavior indicators directly on scene', 'Replaces traditional psychrometers with instantaneous digital readings', 'Drop-tested waterproof floating casing designed for wildland crews', 'Large backlit display visible in smoke and direct bright sunlight'],
    page: 1,
    subcategories: ['forest-fire-fighting-products'],
    categoryIds: ['forestry'],
    tags: ['Forest Fire-Fighting Products', 'Fire Weather Meter']
  },
  {
    slug: 'weather-monitoring-kit',
    name: 'Weather Monitoring Kit',
    brand: 'AFFORDA',
    category: 'forestry',
    image: 'placeholder',
    gallery: ['placeholder'],
    label: 'BELT WEATHER KIT',
    summary: 'Complete belt weather kit including sling psychrometer, anemometer, compass, and slide rule tables for fire danger indices.',
    specs: [['Kit Components', 'Sling Psychrometer, Wind Meter, Water Bottle, Tables'], ['Carrying Case', 'Heavy-Duty Ballistic Nylon Pouch with Belt Loops']],
    features: ['Comprehensive field weather assessment independent of digital sensors', 'Includes psychrometric tables for relative humidity and dewpoint calculations', 'Reliable backup weather determination for incident commanders and lookouts', 'Packed in rugged water-resistant pouch for mobile field deployment'],
    page: 1,
    subcategories: ['forest-fire-fighting-products'],
    categoryIds: ['forestry'],
    tags: ['Forest Fire-Fighting Products', 'Weather Kit']
  },
  {
    slug: 'water-tank',
    name: 'Water Tank',
    brand: 'AFFORDA',
    category: 'forestry',
    image: 'placeholder',
    gallery: ['placeholder'],
    label: 'MOBILE WATER STORAGE',
    summary: 'Collapsible bladder or skid-mounted baffled water tank for forest fire supply points, utility pickup beds, and temporary staging.',
    specs: [['Construction', 'Heavy-Duty Reinforced Polymer / Polyethylene'], ['Coupling', 'Standard Fire Hose Quick-Connect Outlets']],
    features: ['Baffled internal structure stabilizes water surge during vehicle transit', 'UV-stabilized puncture-resistant materials engineered for outdoor survival', 'Rapid fill ports compatible with drafting pumps and municipal hydrants', 'Collapses to compact volume for storage and transport when drained'],
    page: 1,
    subcategories: ['forest-fire-fighting-products'],
    categoryIds: ['forestry'],
    tags: ['Forest Fire-Fighting Products', 'Water Tank']
  },
  {
    slug: 'fire-hose',
    name: 'Fire Hose',
    brand: 'AFFORDA',
    category: 'forestry',
    image: 'placeholder',
    gallery: ['placeholder'],
    label: 'WILDLAND FORESTRY HOSE',
    summary: 'Lightweight synthetic single-jacket wildland fire hose rated for high-pressure delivery over long forestry hose lays.',
    specs: [['Material', '100% High-Tenacity Synthetic Single Jacket'], ['Working Pressure', 'High-Pressure Wildland Working Rating']],
    features: ['Engineered for lightweight pack-in and steep grade deployment', 'High abrasion resistance against rocks, thorns, and jagged roots', 'Available in standard quick-connect diameters', 'Mildew-resistant lining requires no drying before temporary repack'],
    page: 1,
    subcategories: ['forest-fire-fighting-products'],
    categoryIds: ['forestry'],
    tags: ['Forest Fire-Fighting Products', 'Fire Hose']
  },
  {
    slug: 'hose-reel',
    name: 'Hose Reel',
    brand: 'AFFORDA',
    category: 'forestry',
    image: 'placeholder',
    gallery: ['placeholder'],
    label: 'FIELD HOSE DEPLOYMENT',
    summary: 'Wildland hose reel for rapid deployment and retrieval of high-pressure forestry booster hose on fire attack vehicles.',
    specs: [['Drive Mechanism', 'Manual Hand Crank / Auxiliary Rewind'], ['Drum Capacity', 'Accommodates Standard Forestry Hose Lengths']],
    features: ['Smooth fluid swivel joint prevents kinked flow under high pressure', 'Heavy-gauge steel frame with powder coat finish for corrosion resistance', 'Drag brake and locking pin prevent unintended unwinding during transit', 'Compact footprint designed for fire utility vehicles and pump skids'],
    page: 1,
    subcategories: ['forest-fire-fighting-products'],
    categoryIds: ['forestry'],
    tags: ['Forest Fire-Fighting Products', 'Hose Reel']
  },
  {
    slug: 'portable-water-pump',
    name: 'Portable Water Pump',
    brand: 'AFFORDA',
    category: 'forestry',
    image: 'placeholder',
    gallery: ['placeholder'],
    label: 'DRAFTING & RELAY PUMP',
    summary: 'Lightweight water pump for drafting from natural rivers, streams, and ponds to supply firelines and remote sprinkler setups.',
    specs: [['Discharge Capability', 'High-Pressure / High-Volume Forestry Transfer'], ['Portability', 'Backpack Harness Mountable']],
    features: ['Capable of high suction lift from natural mountain water sources', 'Spark-arrestor equipped muffler for safety in dry timber environments', 'Anodized aluminum pump head resists sediment and sand abrasion', 'Straightforward field maintenance requiring basic tools'],
    page: 1,
    subcategories: ['forest-fire-fighting-products'],
    categoryIds: ['forestry'],
    tags: ['Forest Fire-Fighting Products', 'Portable Water Pump']
  },
  {
    slug: 'fire-extinguisher',
    name: 'Fire Extinguisher',
    brand: 'AFFORDA',
    category: 'forestry',
    image: 'placeholder',
    gallery: ['placeholder'],
    label: 'VEHICLE & CAMP EXTINGUISHER',
    summary: 'Heavy-duty dry chemical and compressed air foam (CAFS) fire extinguisher rated for forestry equipment, vehicles, and camps.',
    specs: [['Extinguishing Agent', 'ABC Dry Chemical / Foam Options'], ['Rating Class', 'Class A (Wood/Grass), Class B (Fuels), Class C (Electrical)']],
    features: ['Rugged steel cylinder with corrosion-resistant brass valve assembly', 'Includes heavy-duty vehicle mounting bracket with quick-release clamp', 'Pressure gauge indicator for immediate readiness verification', 'Effective initial suppression for forest harvesting equipment and vehicles'],
    page: 1,
    subcategories: ['forest-fire-fighting-products'],
    categoryIds: ['forestry'],
    tags: ['Forest Fire-Fighting Products', 'Fire Extinguisher']
  },
  {
    slug: 'firefighting-backpack',
    name: 'Firefighting Backpack',
    brand: 'AFFORDA',
    category: 'forestry',
    image: 'placeholder',
    gallery: ['placeholder'],
    label: 'WILDLAND WEB GEAR',
    summary: 'Ergonomic wildland firefighter web gear pack with fire shelter pouch, fusee pockets, hydration bladder, and tool carriers.',
    specs: [['Material', 'Heavy-Duty Heat-Resistant Ballistic Nylon'], ['Attachment System', 'Dedicated Fire Shelter Deployment Pouch']],
    features: ['Ergonomically balances weight on hips to reduce spinal fatigue during hikes', 'Quick-release buckle allows rapid jettison in burnover emergencies', 'Reinforced holster loops for hand tools, water bottles, and weather meters', 'Flame-retardant hardware and high-tensile stitching'],
    page: 1,
    subcategories: ['forest-fire-fighting-products'],
    categoryIds: ['forestry'],
    tags: ['Forest Fire-Fighting Products', 'Firefighting Backpack']
  },
  {
    slug: 'personal-protective-equipment',
    name: 'Personal Protective Equipment',
    brand: 'AFFORDA',
    category: 'forestry',
    image: 'placeholder',
    gallery: ['placeholder'],
    label: 'PPE FOR WILDFIRE CREWS',
    summary: 'Certified wildland PPE ensemble including flame-resistant Nomex shirt and trousers, forestry hard hat, shroud, goggles, and leather gloves.',
    specs: [['Compliance', 'Flame-Resistant Wildland Safety Standards'], ['Ensemble Components', 'FR Apparel, Shroud, Helmet, Fire Goggles & Gloves']],
    features: ['Inherently flame-resistant fabric provides durable thermal defense', 'Breathable weave prevents heat stress during rigorous handline construction', 'High-impact hard hat with neck shroud shielding from falling debris and embers', 'Heavy-duty chrome-tanned leather gloves for tool grip and heat shielding'],
    page: 1,
    subcategories: ['forest-fire-fighting-products'],
    categoryIds: ['forestry'],
    tags: ['Forest Fire-Fighting Products', 'PPE']
  }
];

export const brandDescriptions: Record<string,string> = {
  'AFFORDA':'Specialized professional field, forestry, surveying, and wildfire equipment engineered for precision, durability, and demanding terrain.',
  'Vortex Optics':'A closer connection to the world beyond. Discover HD binoculars and precision observation optics.',
  'Garmin':'Find your position and your next destination with purpose-built handheld navigation.',
  'Brunton':'Tools for reading the earth. Explore geological transits and precision field compasses.',
  'Browning':'Observe life in the wild with dedicated trail-camera technology.',
  'Brutforce':'Keep field teams connected with portable communication products.',
  'Ralcam':'Reach difficult spaces with articulating inspection camera systems.',
  'HIKMICRO':'See temperature and heat signatures with portable thermal imaging.',
  'Panasonic Toughbook':'Rugged computing platforms configured for mobile professional work.',
  'DGPS solutions':'Tell us your survey accuracy, correction network and field workflow requirements. Our team will help identify an appropriate DGPS solution.',
  'Suunto':'Dependable sighting compasses and navigation tools for the field.',
  'MINOX':'Digital night vision for observation beyond daylight.',
  'Open Acoustic Devices':'Compact acoustic loggers for ecological research and wildlife monitoring.',
};

export const finderOptions: Record<string, Record<string, string[]>> = {
  'Forestry & Wildlife': {
    'Forest Measurement': ['diameter-tape-dbh-tape', 'digital-tree-caliper', 'clinometer', 'hypsometer', 'laser-rangefinder'],
    'Mapping & Navigation': ['garmin-gpsmap-65s', 'professional-gnss-receiver', 'rtk-dgps', 'laser-rangefinder'],
    'Fire Suppression': ['backpack-fire-pump', 'portable-fire-pump', 'pulaski-forestry-axe', 'drip-torch', 'fire-weather-meter'],
    'Wildlife monitoring': ['browning-strike-force-pro-dcl', 'audiomoth'],
    'Night observation': ['hikmicro-lynx-lh25', 'minox-nvd-650'],
  },
  'Surveying & Mapping': { 'Navigation':['garmin-gpsmap-65s','garmin-montana-700'], 'DGPS positioning':['rtk-dgps','professional-gnss-receiver'], 'Field computing':['panasonic-toughbook','electronic-data-collector'] },
  'Geology & Research': { 'Compass & transit measurement':['brunton-geolite','brunton-compro-transit','brunton-f-5012-axis'], 'Navigation & positioning':['suunto-mc2','garmin-gpsmap-65s'] },
  'Industrial Inspection': { 'Confined-space inspection':['ralcam-h408b'], 'Thermal observation':['hikmicro-e20-plus','hikmicro-lynx-lh25'], 'Field computing':['panasonic-toughbook'] },
  'Field Operations': { 'Team communication':['brutforce-field-radio'], 'Navigation':['garmin-gpsmap-65s','suunto-mc2'], 'Night observation':['hikmicro-lynx-lh25','minox-nvd-650'] },
  'Defense & Paramilitary': {
    'Thermal Imaging':['hikmicro-lynx-lh25'],
    'Night Vision':['minox-nvd-650'],
    'GPS / Navigation':['garmin-gpsmap-65s','garmin-montana-700','suunto-mc2'],
    'Binoculars / Optics':['vortex-viper-hd','vortex-diamondback-hd'],
    'Communication':['brutforce-field-radio'],
    'Rugged Computing':['panasonic-toughbook'],
    'Surveillance / Monitoring':['browning-strike-force-pro-dcl','hikmicro-lynx-lh25','minox-nvd-650'],
  },
  'Mining & Geology': {
    'Geological Survey':['brunton-geolite','brunton-compro-transit','brunton-f-5012-axis'],
    'Mapping / GNSS':['garmin-gpsmap-65s','garmin-montana-700'],
    'Compasses / Pocket Transits':['brunton-geolite','brunton-compro-transit','brunton-f-5012-axis'],
    'Distance Measurement':['garmin-gpsmap-65s','garmin-montana-700'],
    'Rugged Computing':['panasonic-toughbook'],
    'Field Inspection':['ralcam-h408b'],
  },
};

export function findEquipment(industry: string, requirement: string) {
  const options = finderOptions[industry];
  if (!options || !Object.hasOwn(options, requirement)) throw new Error('Choose a valid industry and requirement.');
  return products.filter(p => options[requirement].includes(p.slug));
}
export function productBelongsToCategory(product: Product, categoryId: string) {
  return product.category === categoryId || product.categoryIds?.includes(categoryId) === true;
}
export const whatsAppUrl = (message: string) => `https://wa.me/919818320178?text=${encodeURIComponent(message)}`;
