import type { Product } from '@/lib/catalogue';

export const campingPhase4Products: Product[] = [
  // =========================================================================
  // GROUP A: CAMPING TENTS
  // =========================================================================
  {
    slug: 'coleman-weathermaster-10-person-tent',
    name: 'WeatherMaster® 10-Person Tent',
    brand: 'Coleman',
    category: 'forestry',
    image: 'coleman-weathermaster-10-person-tent',
    gallery: ['coleman-weathermaster-10-person-tent'],
    label: '10-PERSON EXPEDITION CABIN TENT',
    summary: 'Spacious cabin-style field tent engineered with the WeatherTec™ system, rigid hinged door, room divider, and 6 ft. 8 in. center height for multi-person forestry expeditions and field station crew quarters.',
    specs: [
      ['Capacity', '10 Person (Fits 3 Queen Airbeds)'],
      ['Floor Dimensions', '17 ft x 9 ft (5.18 m x 2.74 m)'],
      ['Center Height', '6 ft 8 in (2.03 m)'],
      ['Weather Protection', 'WeatherTec™ System (welded corners & inverted seams)'],
      ['Wind Rating', 'Tested to withstand up to 35 mph winds'],
      ['Doors', '1 Rigid Hinged Door + 1 Zippered Door'],
      ['Ventilation', 'Angled windows, mesh roof vents & ground vent'],
      ['Setup System', 'Color-coded steel and fiberglass pole structure with pin-and-ring system'],
      ['Electrical Access', 'E-Port power extension cord access point'],
      ['Weight', 'Approx. 33.8 lbs (15.3 kg)'],
    ],
    features: [
      'WeatherTec™ system features patented welded tub-style floor corners and inverted seams to keep rain out',
      'Generous 17 x 9 ft floor plan with 6 ft 8 in center height allows crew members to stand upright and move freely',
      'Rigid patented hinged door provides fast, latching access without constantly fighting door zippers',
      'Included room divider curtain creates two distinct living or storage quarters for extended field stays',
      'Angled window design allows airflow during rain showers while keeping water from entering the shelter',
      'Integrated E-Port flap allows protected electrical cords to power laptops, lighting, and survey gear'
    ],
    page: 1,
    subcategories: ['forestry-camping-safety-climate-products'],
    categoryIds: ['forestry'],
    tags: ['Camping & Field Equipment', 'Camping Tents']
  },
  {
    slug: 'coleman-weathermaster-6-person-screen-room',
    name: 'WeatherMaster® 6-Person Tent with Screen Room',
    brand: 'Coleman',
    category: 'forestry',
    image: 'coleman-weathermaster-6-person-screen-room',
    gallery: ['coleman-weathermaster-6-person-screen-room'],
    label: '6-PERSON FIELD TENT WITH SCREEN ROOM',
    summary: 'Heavy-duty expedition cabin tent featuring an enclosed floorless screen room for bug-free field documentation and equipment staging, built with the WeatherTec™ water-shedding system.',
    specs: [
      ['Capacity', '6 Person (Fits 2 Queen Airbeds)'],
      ['Total Dimensions', '17 ft x 9 ft (Main Room: 11 x 9 ft; Screen Room: 9 x 6 ft)'],
      ['Center Height', '6 ft 8 in (2.03 m)'],
      ['Screen Room', 'Enclosed 9 x 6 ft bug-free mesh vestibule with drain channels'],
      ['Weather Protection', 'WeatherTec™ System (welded floors & inverted protected seams)'],
      ['Wind Rating', 'Engineered and tested to withstand 35+ mph winds'],
      ['Door Type', 'Patented rigid hinged front door'],
      ['Ventilation', 'Variflo™ adjustable ventilation system and reverse-angle windows'],
      ['Weight', 'Approx. 35.9 lbs (16.3 kg)'],
      ['Electrical Access', 'E-Port access for exterior power routing'],
    ],
    features: [
      'Attached 9 x 6 ft screen room provides a shaded, insect-free staging area for fieldwork notes, meals, and boot storage',
      'WeatherTec™ tub floors with patented corner welds and protected seams guard against ground moisture infiltration',
      'Rigid hinged door opens and closes with ease, providing effortless access during active field camp operations',
      'Vertical cabin wall structure and 6 ft 8 in ceiling provide superior livable volume and headroom',
      'Strong steel and fiberglass hybrid frame engineered and tested to maintain structural integrity in 35 mph winds',
      'Variflo™ adjustable airflow system with reverse-angle side windows promotes cross-ventilation even in rainfall'
    ],
    page: 1,
    subcategories: ['forestry-camping-safety-climate-products'],
    categoryIds: ['forestry'],
    tags: ['Camping & Field Equipment', 'Camping Tents']
  },
  {
    slug: 'coleman-skydome-6-person-camping-tent',
    name: 'Skydome™ 6-Person Camping Tent',
    brand: 'Coleman',
    category: 'forestry',
    image: 'coleman-skydome-6-person-camping-tent',
    gallery: ['coleman-skydome-6-person-camping-tent'],
    label: 'RAPID-PITCH 6-PERSON DOME TENT',
    summary: 'Fast-deployment dome tent featuring pre-attached poles for under-5-minute setup, nearly vertical walls delivering 20% more headroom, and WeatherTec™ storm protection for mobile forestry crews.',
    specs: [
      ['Capacity', '6 Person (Fits 2 Queen Airbeds)'],
      ['Floor Dimensions', '10 ft x 8.5 ft (3.05 m x 2.59 m)'],
      ['Center Height', '6 ft (1.83 m)'],
      ['Setup Time', 'Under 5 minutes with pre-attached quick-pitch poles'],
      ['Headroom', 'Nearly vertical walls provide 20% more headroom than conventional domes'],
      ['Weather Protection', 'WeatherTec™ System with tub floor and taped seams'],
      ['Wind Rating', 'Tested to withstand winds up to 35 mph'],
      ['Door', 'Extra-wide D-door for easy gear maneuvering'],
      ['Storage', 'Mesh interior storage pockets and gear loft'],
      ['Weight', 'Approx. 16.6 lbs (7.5 kg)'],
    ],
    features: [
      'Pre-attached quick-pitch fiberglass poles enable field crews to pitch the complete tent in under 5 minutes',
      'Near-vertical wall profile maximizes functional interior volume with 20% greater headroom than traditional domes',
      'WeatherTec™ welded floor corners and inverted seams prevent water ingress during prolonged downpours',
      'Wider door entry facilitates effortless loading and unloading of bulky survey packs, cots, and gear bags',
      'Integrated interior mesh gear pockets keep handheld radios, GPS units, and headlamps organized off the floor',
      'E-Port zippered flap provides weatherproof passage for electrical cables to power internal instrumentation'
    ],
    page: 1,
    subcategories: ['forestry-camping-safety-climate-products'],
    categoryIds: ['forestry'],
    tags: ['Camping & Field Equipment', 'Camping Tents']
  },

  // =========================================================================
  // GROUP B: SLEEPING BAGS & BEDDING
  // =========================================================================
  {
    slug: 'coleman-big-game-0f-sleeping-bag',
    name: 'Big Game™ 0°F Big & Tall Sleeping Bag',
    brand: 'Coleman',
    category: 'forestry',
    image: 'coleman-big-game-0f-sleeping-bag',
    gallery: ['coleman-big-game-0f-sleeping-bag'],
    label: 'EXTREME COLD 0°F EXPEDITION SLEEPING BAG',
    summary: 'Oversized heavy-duty cold-weather sleeping bag engineered with a rugged cotton canvas shell, ultra-soft sherpa lining, and EcoTherm™ insulation rated down to 0°F (-18°C) for remote field camps.',
    specs: [
      ['Temperature Rating', '0°F (-18°C) Extreme Cold'],
      ['Size / Dimensions', '84 in x 40 in (213 cm x 102 cm)'],
      ['Maximum User Height', 'Fits field personnel up to 6 ft 5 in (1.95 m)'],
      ['Shell Material', 'Heavy-duty 100% cotton canvas outer shell'],
      ['Lining Material', 'Plush sherpa fleece top cuff and cotton flannel lining'],
      ['Insulation', 'EcoTherm™ high-loft hollow polyester insulation'],
      ['Draft Protection', 'Thermolock™ full-length draft tube prevents heat loss'],
      ['Zipper System', 'ZipPlow™ patented 2-way snag-free heavy-duty zipper'],
      ['Accessories', 'Matching flannel pillow included'],
      ['Packing System', 'Roll Control™ fasteners and Quick Cord™ one-person tie system'],
    ],
    features: [
      'Engineered for sub-freezing forestry camps with an official 0°F (-18°C) extreme cold weather comfort rating',
      'Rugged cotton canvas shell resists tears, abrasions, and sparks around field campfires',
      'Plush sherpa fleece cuff and soft cotton flannel lining deliver exceptional warmth and skin comfort',
      'Thermolock™ draft tube runs along the entire zipper length to block penetrating cold air drafts',
      'ZipPlow™ zipper pushes fabric away from the teeth to eliminate snagging and zipper jams in the dark',
      'Oversized Big & Tall cut provides unrestricted sleeping comfort for researchers and technicians up to 6 ft 5 in'
    ],
    page: 1,
    subcategories: ['forestry-camping-safety-climate-products'],
    categoryIds: ['forestry'],
    tags: ['Camping & Field Equipment', 'Sleeping Bags & Bedding']
  },
  {
    slug: 'coleman-north-rim-0f-mummy-sleeping-bag',
    name: 'North Rim™ 0°F Adult Mummy Sleeping Bag',
    brand: 'Coleman',
    category: 'forestry',
    image: 'coleman-north-rim-0f-mummy-sleeping-bag',
    gallery: ['coleman-north-rim-0f-mummy-sleeping-bag'],
    label: '0°F TECHNICAL EXPEDITION MUMMY BAG',
    summary: 'Cold-weather technical mummy sleeping bag built with Coletherm® hollow polyester insulation, contoured drawstring hood, 3D box footbox, and ripstop shell for high-altitude alpine and winter forest patrols.',
    specs: [
      ['Temperature Rating', '0°F (-18°C)'],
      ['Style / Cut', 'Adult Mummy with Contoured Hood'],
      ['Dimensions', '82 in x 32 in (208 cm x 81 cm)'],
      ['Maximum User Height', 'Fits campers up to 6 ft 2 in (1.88 m)'],
      ['Shell Material', 'Durable polyester ripstop water-resistant cover'],
      ['Insulation Type', 'Coletherm® hollow polyester thermal fill'],
      ['Footbox', 'Box-shaped 3D footbox provides ergonomic toe room'],
      ['Hood System', 'Semi-sculpted adjustable hood with cinch drawstring'],
      ['Draft Protection', 'Thermolock™ draft tube and insulated shoulder collar'],
      ['Weight', 'Approx. 5.8 lbs (2.6 kg)'],
    ],
    features: [
      'Mummy silhouette with sculpted hood efficiently retains core body warmth in frigid sub-zero field environments',
      'Coletherm® hollow fiber insulation traps dead air to maintain consistent thermal loft even in damp air',
      'Full-length Thermolock™ draft tube and internal collar stop cold air from penetrating through the closure',
      '3D box-shaped footbox design eliminates toe compression and cold spots at the base of the bag',
      'Ripstop polyester outer shell resists punctures from rough camp flooring and branches',
      'Two-way ZipPlow™ snag-free zipper enables footbox ventilation on warmer evenings'
    ],
    page: 1,
    subcategories: ['forestry-camping-safety-climate-products'],
    categoryIds: ['forestry'],
    tags: ['Camping & Field Equipment', 'Sleeping Bags & Bedding']
  },
  {
    slug: 'coleman-brazos-20f-sleeping-bag',
    name: 'Brazos™ 20°F Cold-Weather Sleeping Bag',
    brand: 'Coleman',
    category: 'forestry',
    image: 'coleman-brazos-20f-sleeping-bag',
    gallery: ['coleman-brazos-20f-sleeping-bag'],
    label: '20°F RUGGED FIELD SLEEPING BAG',
    summary: 'Dependable cold-weather sleeping bag rated for 20°F to 40°F expeditions, featuring Fiberlock™ quilt construction, soft brushed tricot lining, and Roll Control™ packing for field personnel.',
    specs: [
      ['Temperature Rating', '20°F to 40°F (-7°C to 4°C)'],
      ['Shape / Cut', 'Rectangular Field Cut'],
      ['Dimensions', '75 in x 33 in (190 cm x 84 cm)'],
      ['Maximum User Height', 'Fits heights up to 5 ft 11 in (1.80 m)'],
      ['Shell Material', 'Durable polyester shell'],
      ['Lining Material', 'Soft brushed polyester tricot lining'],
      ['Insulation', 'Coletherm® hollow polyester fill with Fiberlock™ construction'],
      ['Draft Protection', 'Thermolock™ zipper draft baffle'],
      ['Zipper', 'ZipPlow™ 2-way snag-free zipper; compatible with second bag zip-together'],
      ['Packing', 'Roll Control™ locking pins and Quick Cord™ system'],
    ],
    features: [
      'Comfort-rated for 20°F down to freezing, ideal for spring, autumn, and mountain forestry field missions',
      'Fiberlock™ construction prevents insulation fibers from shifting, maintaining even thermal coverage',
      'Brushed tricot lining provides warm, quiet, and breathable comfort throughout overnight field rests',
      'Thermolock™ draft tube lines the zipper track to prevent convective heat loss along the side',
      'Patented ZipPlow™ zipper mechanism pushes fabric clear of the runner to prevent snags and fabric tears',
      'Roll Control™ edge loops and Quick Cord™ closure allow fast, single-person rolling and tying at daybreak'
    ],
    page: 1,
    subcategories: ['forestry-camping-safety-climate-products'],
    categoryIds: ['forestry'],
    tags: ['Camping & Field Equipment', 'Sleeping Bags & Bedding']
  },

  // =========================================================================
  // GROUP C: SHELTERS & CANOPIES
  // =========================================================================
  {
    slug: 'coleman-oasis-10x10-canopy',
    name: 'OASIS™ 10 x 10 Canopy',
    brand: 'Coleman',
    category: 'forestry',
    image: 'coleman-oasis-10x10-canopy',
    gallery: ['coleman-oasis-10x10-canopy'],
    label: 'INSTANT 10x10 FIELD CANOPY',
    summary: 'Rapid-deployment 10x10 ft overhead shade canopy featuring OnePeak™ one-push center hub technology, heavy-duty steel frame, roof ventilation valve, and UPF 50+ UVGuard™ protection for survey stations.',
    specs: [
      ['Shade Coverage', '100 sq ft (9.3 sq m)'],
      ['Canopy Dimensions', '10 ft x 10 ft (3.05 m x 3.05 m)'],
      ['Center Height', '9 ft 2 in (2.79 m)'],
      ['Deployment System', 'OnePeak™ one-push center hub instant pitch'],
      ['Frame Material', 'One-piece powder-coated steel frame'],
      ['Wind Resistance', 'Tested to withstand winds up to 35 mph when properly staked'],
      ['UV Protection', 'UVGuard™ fabric rated UPF 50+'],
      ['Ventilation', 'Roof peak air vent releases trapped heat and enhances wind stability'],
      ['Leg Adjustment', 'Comfort Grip™ pinch-free button telescoping legs with 3 height settings'],
      ['Transport', 'Heavy-duty wheeled carry bag with dual handles included'],
      ['Weight', 'Approx. 43.4 lbs (19.7 kg)'],
    ],
    features: [
      'OnePeak™ center hub allows a single field researcher to extend and lock the entire canopy with one central push',
      'UVGuard™ canopy material delivers UPF 50+ sun protection to shield sensitive field equipment and personnel',
      'Vented roof apex releases trapped warm air and prevents wind lift during sudden gusts on exposed field sites',
      'Comfort Grip™ telescoping leg system features pinch-free buttons with three adjustable height levels',
      'Robust powder-coated steel frame tested to endure sustained 35 mph winds when fully staked and guyed',
      'Durable wheeled carry bag fits easily into truck beds and glides over rough terrain for simple transport'
    ],
    page: 1,
    subcategories: ['forestry-camping-safety-climate-products'],
    categoryIds: ['forestry'],
    tags: ['Fire Fighting Equipment', 'Camping & Field Equipment', 'Shelters & Canopies']
  },
  {
    slug: 'coleman-back-home-10-5x9-screen-canopy',
    name: 'Back Home™ 10.5 x 9 Screen Canopy Tent',
    brand: 'Coleman',
    category: 'forestry',
    image: 'coleman-back-home-10-5x9-screen-canopy',
    gallery: ['coleman-back-home-10-5x9-screen-canopy'],
    label: 'ONE-PUSH INSECT-PROOF SCREEN SHELTER',
    summary: 'Fully enclosed insect-screen field shelter featuring OnePeak™ one-push setup, high-density mesh walls, two large zippered doors, and UPF 50+ sun canopy sized to fit over outdoor research tables.',
    specs: [
      ['Footprint Dimensions', '10 ft 8 in x 9 ft 2 in (3.25 m x 2.79 m)'],
      ['Center Height', '9 ft (2.74 m)'],
      ['Shade Coverage', 'Over 73 sq ft (6.8 sq m)'],
      ['Enclosure', 'Full 360° ultra-fine insect mesh perimeter with ground skirts'],
      ['Entryways', '2 Large zippered front and back doors with tie-backs'],
      ['Setup Mechanism', 'OnePeak™ one-push center hub deployment'],
      ['Sun Protection', 'UVGuard™ UPF 50+ rated roof fabric'],
      ['Frame Construction', 'Heavy-gauge steel frame with Comfort Grip™ buttons'],
      ['Internal Clearance', 'Engineered to fit completely over standard 6–8 ft camp picnic tables'],
      ['Weight', 'Approx. 47.9 lbs (21.7 kg)'],
      ['Portability', 'Wheeled storage bag with pull handle included'],
    ],
    features: [
      'High-density insect-proof mesh walls keep biting flies, mosquitoes, and ticks out of camp mess and work spaces',
      'OnePeak™ technology enables rapid, tool-free setup from underneath the shelter with a single upward push',
      'Two expansive zippered doorways allow unobstructed crew pass-through and rapid equipment handling',
      'Generous 9 ft peak height and expansive footprint comfortably cover field dining tables and calibration benches',
      'Sturdy steel frame provides rigid structural resistance against gusty mountain and riparian valley winds',
      'Rugged wheeled transit case protects the canopy during bumpy 4x4 transport into remote research stations'
    ],
    page: 1,
    subcategories: ['forestry-camping-safety-climate-products'],
    categoryIds: ['forestry'],
    tags: ['Fire Fighting Equipment', 'Camping & Field Equipment', 'Shelters & Canopies']
  },
  {
    slug: 'coleman-flex-n-go-10x10-shelter',
    name: "Flex 'N Go™ 10 x 10 Shelter",
    brand: 'Coleman',
    category: 'forestry',
    image: 'coleman-flex-n-go-10x10-shelter',
    gallery: ['coleman-flex-n-go-10x10-shelter'],
    label: 'PORTABLE LIGHTWEIGHT 10x10 FIELD SHELTER',
    summary: "Lightweight, highly portable 10x10 ft field shelter featuring a streamlined steel frame, OnePeak™ rapid setup, and UPF 50+ weather-resistant canopy for mobile teams requiring fast staging.",
    specs: [
      ['Shade Coverage', '100 sq ft (9.3 sq m)'],
      ['Canopy Dimensions', '10 ft x 10 ft (3.05 m x 3.05 m)'],
      ['Center Height', '8 ft 8 in (2.64 m)'],
      ['Setup System', 'OnePeak™ one-push center hub'],
      ['Frame Construction', 'Lightweight folding steel truss frame'],
      ['UV Protection', 'UPF 50+ UVGuard™ sun blocking fabric'],
      ['Leg Adjustment', 'Comfort Grip™ pinch-free extension buttons'],
      ['Weight', 'Approx. 32.6 lbs (14.8 kg)'],
      ['Carry System', 'Compact wheeled transport bag included'],
      ['Anchoring', 'Heavy-duty ground stakes and pre-attached guy lines included'],
    ],
    features: [
      'Optimized lightweight steel frame weighs just 32.6 lbs, making it significantly easier to carry across rough ground',
      'OnePeak™ one-push hub enables single-operator deployment in minutes without requiring tools',
      'Full 100 sq ft of overhead canopy protection blocks 98% of harmful UV rays with UPF 50+ rating',
      'Comfort Grip™ leg adjustment system protects hands and fingers from pinching during height configuration',
      'Compact folded profile fits into smaller utility vehicles, patrol SUVs, and research boat holds',
      'Supplied with wheeled carry bag and ground anchor kit for reliable stabilization in breezy conditions'
    ],
    page: 1,
    subcategories: ['forestry-camping-safety-climate-products'],
    categoryIds: ['forestry'],
    tags: ['Fire Fighting Equipment', 'Camping & Field Equipment', 'Shelters & Canopies']
  },

  // =========================================================================
  // GROUP D: CAMP FURNITURE & COTS
  // =========================================================================
  {
    slug: 'coleman-trailhead-ii-camping-cot',
    name: 'Trailhead™ II Camping Cot',
    brand: 'Coleman',
    category: 'forestry',
    image: 'coleman-trailhead-ii-camping-cot',
    gallery: ['coleman-trailhead-ii-camping-cot'],
    label: 'MILITARY-STYLE HEAVY-DUTY FIELD COT',
    summary: 'Rugged military-style steel cross-bar folding cot engineered to support up to 300 lbs, elevating field personnel 17 inches off damp, rocky, or frozen forest terrain for healthy rest.',
    specs: [
      ['Weight Capacity', 'Supports up to 300 lbs (136 kg)'],
      ['Dimensions (Unfolded)', '73 in x 35 in x 17 in (185 cm x 89 cm x 43 cm)'],
      ['Maximum User Height', 'Accommodates individuals up to 6 ft 2 in (1.88 m)'],
      ['Ground Clearance', '17 in (43 cm) elevation above terrain'],
      ['Frame Material', 'Heavy-duty powder-coated dual-X cross-bar steel frame'],
      ['Bed Fabric', 'High-tensile abrasion-resistant 600D polyester canvas'],
      ['Design Style', 'Classic military folding field cot'],
      ['Folded Dimensions', 'Approx. 38 in x 8 in x 4 in (97 cm x 20 cm x 10 cm)'],
      ['Weight', 'Approx. 18.2 lbs (8.3 kg)'],
      ['Accessories', 'Heavy-duty carry bag with shoulder strap included'],
    ],
    features: [
      'Elevates field personnel 17 inches above rocky, damp, uneven, or snake-inhabited forest floors',
      'Heavy-duty dual cross-bar steel frame provides rock-solid structural stability and supports up to 300 lbs',
      'High-tensile polyester sleeping surface delivers taut, ergonomic back support throughout long field deployments',
      'Generous 73 x 35 inch sleeping area accommodates workers up to 6 ft 2 in with comfortable arm room',
      'Under-cot clearance provides massive auxiliary storage space for survey packs, boots, and waterproof cases',
      'Folds into a compact carry bag for streamlined transport and neat stacking in supply depot tents'
    ],
    page: 1,
    subcategories: ['forestry-camping-safety-climate-products'],
    categoryIds: ['forestry'],
    tags: ['Camping & Field Equipment', 'Camp Furniture & Cots']
  },
  {
    slug: 'coleman-pack-away-camping-cot-side-table',
    name: 'Pack-Away® Camping Cot with Side Table',
    brand: 'Coleman',
    category: 'forestry',
    image: 'coleman-pack-away-camping-cot-side-table',
    gallery: ['coleman-pack-away-camping-cot-side-table'],
    label: 'EXPEDITION COT WITH INTEGRATED WORK TABLE',
    summary: 'Extra-wide, extra-long expedition folding cot featuring a removable side utility table with cup holder, heavy-duty steel frame supporting 300 lbs, and rapid accordion folding for field camp quarters.',
    specs: [
      ['Weight Capacity', 'Supports up to 300 lbs (136 kg)'],
      ['Cot Dimensions', '80 in x 44 in x 17 in (203 cm x 112 cm x 43 cm)'],
      ['Sleeping Area', '80 in x 32 in (203 cm x 81 cm)'],
      ['Maximum User Height', 'Fits field operators up to 6 ft 6 in (1.98 m)'],
      ['Side Table', 'Removable side table with integrated mesh cup / radio holder'],
      ['Frame Construction', 'Heavy-duty accordion-folding steel frame'],
      ['Fabric', 'Heavy-gauge tear-resistant polyester fabric'],
      ['Elevation', '17 in (43 cm) height above ground level'],
      ['Folded Dimensions', '40 in x 6 in x 6 in (102 cm x 15 cm x 15 cm)'],
      ['Weight', 'Approx. 21 lbs (9.5 kg)'],
    ],
    features: [
      'Extra-long 80-inch frame comfortably supports taller field specialists and researchers up to 6 ft 6 in',
      'Removable side table provides an immediate surface for field tablets, notebooks, radios, and beverages',
      'Accordion-folding frame deploys and packs away in seconds without wrestling loose cross-bars',
      'Heavy-duty steel frame construction provides reliable 300 lb weight capacity without bowing',
      'Generous 17-inch height provides clean separation from cold ground and creates protected under-bed storage',
      'Includes durable carry bag with drawstring closure and shoulder sling for transport between basecamps'
    ],
    page: 1,
    subcategories: ['forestry-camping-safety-climate-products'],
    categoryIds: ['forestry'],
    tags: ['Camping & Field Equipment', 'Camp Furniture & Cots']
  },
  {
    slug: 'coleman-cooler-quad-camping-chair',
    name: 'Cooler Quad Camping Chair',
    brand: 'Coleman',
    category: 'forestry',
    image: 'coleman-cooler-quad-camping-chair',
    gallery: ['coleman-cooler-quad-camping-chair'],
    label: 'HEAVY-DUTY FIELD CHAIR WITH BUILT-IN COOLER',
    summary: 'Comfortable heavy-duty folding field chair featuring a built-in 4-can insulated cooler pouch, cushioned seat, adjustable armrests, mesh storage pocket, and 325 lb weight capacity for field camp staging.',
    specs: [
      ['Weight Capacity', 'Supports up to 325 lbs (147.4 kg)'],
      ['Seat Dimensions', 'Seat width: 24 in (61 cm); Seat height: 18.1 in (46 cm)'],
      ['Built-in Cooler', 'Insulated 4-can cooler compartment integrated into left armrest'],
      ['Frame Material', 'Heavy-duty tubular steel frame'],
      ['Fabric Material', 'Durable polyester with fully cushioned seat and backrest'],
      ['Armrests', 'Adjustable height armrests with tensioning straps'],
      ['Storage Features', 'Mesh beverage holder on right armrest + hanging side gear pocket'],
      ['Folded Portability', 'Compact quad-folding design with carry bag and shoulder strap'],
      ['Weight', 'Approx. 8.8 lbs (4.0 kg)'],
    ],
    features: [
      'Built-in insulated soft cooler in the armrest keeps cold beverages or sample vials chilled within arm reach',
      'Fully cushioned backrest and wide 24-inch seat provide supportive relaxation after arduous field surveys',
      'Heavy-duty powder-coated tubular steel frame easily supports up to 325 lbs across rugged ground',
      'Integrated side mesh storage organizer holds notebooks, smartphones, two-way radios, and field guides',
      'Adjustable armrest heights allow customizable ergonomics for personnel of varying builds',
      'Collapses smoothly into an included heavy-duty carry bag with shoulder strap for rapid relocation'
    ],
    page: 1,
    subcategories: ['forestry-camping-safety-climate-products'],
    categoryIds: ['forestry'],
    tags: ['Camping & Field Equipment', 'Camp Furniture & Cots']
  },

  // =========================================================================
  // GROUP E: CAMPING LIGHTING
  // =========================================================================
  {
    slug: 'coleman-classic-recharge-800-lantern',
    name: 'Classic Recharge 800 Lumens LED Lantern',
    brand: 'Coleman',
    category: 'forestry',
    image: 'coleman-classic-recharge-800-lantern',
    gallery: ['coleman-classic-recharge-800-lantern'],
    label: '800-LUMEN RECHARGEABLE FIELD LANTERN',
    summary: 'High-output rechargeable LED field lantern delivering up to 800 lumens, built-in 4800 mAh power bank for charging electronics, IPX4 weather resistance, and 45-hour low runtime for research camps.',
    specs: [
      ['Light Output', '800 Lumens (High) / 300 Lumens (Medium) / 100 Lumens (Low)'],
      ['Runtime', '5 Hours (High) / 15 Hours (Medium) / 45 Hours (Low / Flashing)'],
      ['Beam Distance', '18 Meters (High) / 11 Meters (Medium) / 7 Meters (Low)'],
      ['Internal Battery', 'Built-in 4800 mAh rechargeable lithium-ion battery'],
      ['Power Bank Output', 'USB-A output port for emergency phone and radio charging'],
      ['Environmental Rating', 'IPX4 water-resistant against splashing and rain'],
      ['Impact Resistance', 'Durable impact-resistant composite casing'],
      ['Charging Cable', 'USB-to-USB-C charging cord nests neatly inside base compartment'],
      ['Bail Handle', 'Large folding steel bail handle with built-in hanging carabiner'],
      ['Indicators', 'LED battery state-of-charge charge indicator lights'],
    ],
    features: [
      'High-powered 800-lumen output illuminates large field camps, mess shelters, and equipment staging bays',
      'Integrated 4800 mAh lithium-ion power bank recharges GPS units, mobile phones, and satellite messengers',
      'Three brightness modes plus flashing mode provide flexible management between intensity and 45-hour runtime',
      'IPX4 water resistance and impact-tested construction withstand harsh weather and rigorous expedition handling',
      'Heavy-duty bail handle with integrated carabiner hook allows secure hanging from tent poles and tree branches',
      'Self-storing USB-C charging cord housed directly in the lantern base prevents loss in the field'
    ],
    page: 1,
    subcategories: ['forestry-camping-safety-climate-products'],
    categoryIds: ['forestry'],
    tags: ['Camping & Field Equipment', 'Camping Lighting']
  },
  {
    slug: 'coleman-classic-recharge-400-lantern',
    name: 'Classic Recharge 400 Lumens LED Lantern',
    brand: 'Coleman',
    category: 'forestry',
    image: 'coleman-classic-recharge-400-lantern',
    gallery: ['coleman-classic-recharge-400-lantern'],
    label: 'COMPACT RECHARGEABLE 400-LUMEN LANTERN',
    summary: 'Compact, lightweight rechargeable LED lantern producing up to 400 lumens of warm diffused light, featuring a built-in 2600 mAh battery, IPX4 water resistance, and carabiner bail handle for tent interiors.',
    specs: [
      ['Light Output', '400 Lumens (High) / 150 Lumens (Medium) / 50 Lumens (Low)'],
      ['Runtime', '5 Hours (High) / 13 Hours (Medium) / 40 Hours (Low)'],
      ['Internal Battery', 'Built-in 2600 mAh rechargeable lithium-ion battery'],
      ['Illumination Pattern', '360° Warm white glare-free diffused light'],
      ['Environmental Rating', 'IPX4 water-resistant against rain and damp conditions'],
      ['Charging Interface', 'USB-C rechargeable with cord storage in base'],
      ['Handle', 'Folding steel bail handle with built-in carabiner clip'],
      ['Form Factor', 'Compact field footprint suitable for tabletop or hanging placement'],
      ['Construction', 'Impact-resistant polycarbonate globe and polymer housing'],
      ['Weight', 'Approx. 1.2 lbs (0.54 kg)'],
    ],
    features: [
      'Compact 400-lumen illumination provides warm, glare-free light ideal for tent cabins and mapping tables',
      'Rechargeable 2600 mAh internal battery eliminates the recurring operational cost of disposable dry cells',
      'Offers three intuitive brightness settings with up to 40 hours of continuous runtime on the low setting',
      'IPX4 water-resistant rating ensures reliable operation in heavy morning dew and steady rainfall',
      'Integrated carabiner handle clips directly onto overhead tent ridge loops and field shelter frames',
      'Rugged impact-resistant globe and base survive inevitable drops and rough packing in equipment totes'
    ],
    page: 1,
    subcategories: ['forestry-camping-safety-climate-products'],
    categoryIds: ['forestry'],
    tags: ['Camping & Field Equipment', 'Camping Lighting']
  },
  {
    slug: 'coleman-quad-pro-800l-led-lantern',
    name: 'Quad® Pro 800L LED Lantern',
    brand: 'Coleman',
    category: 'forestry',
    image: 'coleman-quad-pro-800l-led-lantern',
    gallery: ['coleman-quad-pro-800l-led-lantern'],
    label: 'MODULAR 800-LUMEN MULTI-PANEL LANTERN',
    summary: 'Modular multi-panel field lantern featuring 4 detachable magnetic light panels with individual flashlights, base light retention, USB device charging, and up to 400 hours of runtime for camp operations.',
    specs: [
      ['Total Light Output', '800 Lumens (High) / 100 Lumens (Low)'],
      ['Detachable Panels', '4 Independent rechargeable take-along light panels'],
      ['Individual Panel Features', 'Directional flashlight, power button, fold-down stand, magnetic back'],
      ['Base Illumination', 'Base light stays illuminated even when all 4 panels are removed'],
      ['Runtime (Base + Panels)', 'Up to 20 Hours (High) / Up to 400 Hours (Low)'],
      ['Panel Standalone Runtime', 'Up to 3 hours per individual panel away from base'],
      ['Power Source', '8 D-cell batteries or compatible rechargeable power cartridge'],
      ['Device Charging', 'USB 5V/1A charging port for mobile devices and instruments'],
      ['Water Resistance', 'IPX4 water-resistant engineering'],
      ['Beam Range', 'Up to 15 meters on high'],
    ],
    features: [
      'Four detachable panels allow 4 crew members to take individual handheld lights while base keeps camp lit',
      'Each individual panel features a built-in forward flashlight and fold-down handle that doubles as a stand',
      'Magnetic panel backings adhere instantly to vehicles, trailers, steel poles, and field toolboxes',
      'Panels recharge automatically whenever they are docked back onto the main lantern housing',
      'USB output port provides emergency power replenishment for mission-critical smartphones and radios',
      'Extensive battery runtime delivers up to 400 continuous hours on low setting across long field expeditions'
    ],
    page: 1,
    subcategories: ['forestry-camping-safety-climate-products'],
    categoryIds: ['forestry'],
    tags: ['Camping & Field Equipment', 'Camping Lighting']
  },

  // =========================================================================
  // GROUP F: CAMP COOKING & ESSENTIALS
  // =========================================================================
  {
    slug: 'coleman-guide-series-dual-fuel-stove',
    name: 'Guide Series® Dual Fuel™ Camping Stove',
    brand: 'Coleman',
    category: 'forestry',
    image: 'coleman-guide-series-dual-fuel-stove',
    gallery: ['coleman-guide-series-dual-fuel-stove'],
    label: 'EXPEDITION DUAL FUEL™ 2-BURNER STOVE',
    summary: 'Legendary expedition dual-fuel stove engineered to run on either Coleman® Liquid Fuel or unleaded gasoline, producing 14,000 BTUs across 2 Band-a-Blu™ burners with WindBlock™ panels for off-grid bases.',
    specs: [
      ['Total Heat Output', '14,000 BTUs across 2 independently controlled Band-a-Blu™ burners'],
      ['Fuel Versatility', 'Dual Fuel™ technology: operates on Coleman® Liquid Fuel or unleaded gasoline'],
      ['Fuel Tank Capacity', '2.5 Pints (1.18 Liters)'],
      ['Burn Time', 'Up to 2 hours with both burners on high on one tank of fuel'],
      ['Cooking Surface', 'Accommodates two 10-inch pans or skillets simultaneously'],
      ['Wind Protection', 'Adjustable WindBlock™ side panels shield burners and adjust for wider pans'],
      ['Boil Time', 'Approx. 4 minutes for 1 quart of water'],
      ['Construction', 'Heavy-gauge stamped steel case with folding lid and heavy-duty latch'],
      ['Grate Type', 'Heavy-duty removable nickel-chrome plated steel cooking grate'],
      ['Weight', 'Approx. 12 lbs (5.4 kg)'],
    ],
    features: [
      'Dual Fuel™ engineering operates on Coleman® Liquid Fuel or automotive unleaded gasoline found in any field post',
      'Eliminates reliance on disposable propane canisters in remote expedition regions where canisters are unavailable',
      'Two Band-a-Blu™ burners generate 14,000 total BTUs of reliable cooking power with precise flame adjustment',
      'WindBlock™ side shields protect the flame from blustery mountain winds and adjust to fit larger pots',
      'Substantial 2.5-pint integrated fuel tank delivers up to two full hours of burn time on the maximum setting',
      'Durable stamped steel case folds into a self-contained briefcase with carry handle for rugged transport'
    ],
    page: 1,
    subcategories: ['forestry-camping-safety-climate-products'],
    categoryIds: ['forestry'],
    tags: ['Camping & Field Equipment', 'Camp Cooking & Essentials']
  },
  {
    slug: 'coleman-cascade-3-in-1-camping-stove',
    name: 'Cascade™ 3-in-1 Camping Stove',
    brand: 'Coleman',
    category: 'forestry',
    image: 'coleman-cascade-3-in-1-camping-stove',
    gallery: ['coleman-cascade-3-in-1-camping-stove'],
    label: '3-IN-1 STOVE, GRILL & GRIDDLE SYSTEM',
    summary: 'Versatile 20,000 BTU propane camping stove featuring interchangeable cast-iron grill and griddle plates, Instastart™ push-button ignition, and built-in wind guards for diverse camp cooking needs.',
    specs: [
      ['Total Heat Output', '20,000 BTUs (two 10,000 BTU adjustable burners)'],
      ['Configuration / Accessories', 'Includes removable cast-iron grill and griddle plates with accessory carry pouch'],
      ['Ignition System', 'Instastart™ push-button matchless ignition'],
      ['Fuel Type', '16.4 oz propane cylinder (compatible with 20 lb bulk tank via adapter hose)'],
      ['Burn Time', 'Up to 1 hour on high with one 16.4 oz propane cylinder'],
      ['Wind Protection', 'Folding side wind-deflection shields'],
      ['Pan Compatibility', 'Fits two 10-inch pans or skillets when griddle/grill plates are removed'],
      ['Cooktop Cleanup', 'Removable chrome-plated grate and aluminized steel cooktop'],
      ['Chassis', 'Painted steel casing with recessed carry handle and secure front latch'],
      ['Weight', 'Approx. 17.5 lbs (7.9 kg)'],
    ],
    features: [
      '3-in-1 cooking versatility allows simultaneous or alternating use of standard burner, flat griddle, and ribbed grill',
      'Interchangeable heavy-duty cast-iron grill and griddle accessories store neatly inside the lid',
      'Instastart™ push-button ignition offers instant, dependable matchless lighting in windy conditions',
      'Two independently adjustable burners deliver 20,000 BTUs with precise low-simmer temperature control',
      'Built-in folding wind guards shield flames from breezes to maintain thermal efficiency and conserve fuel',
      'Removable chrome-plated grate and aluminized grease tray make post-meal field cleanup quick and effortless'
    ],
    page: 1,
    subcategories: ['forestry-camping-safety-climate-products'],
    categoryIds: ['forestry'],
    tags: ['Camping & Field Equipment', 'Camp Cooking & Essentials']
  },
  {
    slug: 'coleman-triton-2-burner-camping-stove',
    name: 'Triton™ 2-Burner Propane Camping Stove',
    brand: 'Coleman',
    category: 'forestry',
    image: 'coleman-triton-2-burner-camping-stove',
    gallery: ['coleman-triton-2-burner-camping-stove'],
    label: 'HIGH-OUTPUT 22,000 BTU FIELD STOVE',
    summary: 'High-output portable 2-burner propane field stove delivering 22,000 BTUs, featuring WindBlock™ shielding, precision simmer control, and heavy-duty transport latch for demanding camp cooking.',
    specs: [
      ['Total Heat Output', '22,000 BTUs (two 11,000 BTU independently controlled burners)'],
      ['Fuel Source', 'Standard 16.4 oz propane cylinder (bulk tank compatible with adapter)'],
      ['Burn Time', 'Up to 1 hour on high with a 16.4 oz propane canister'],
      ['Pan Clearance', 'Fits one 12-inch and one 10-inch pan simultaneously'],
      ['Wind Protection', 'Adjustable WindBlock™ panels shield burners from crosswinds'],
      ['Temperature Control', 'Precision control knobs for fine simmer to rapid boil adjustment'],
      ['Grate Material', 'Heavy-duty chrome-plated steel cooking grate'],
      ['Cooktop Surface', 'Aluminized steel cooktop for rust prevention and easy wiping'],
      ['Transport Features', 'Heavy-duty steel case with secure front latch and built-in handle'],
      ['Weight', 'Approx. 11.2 lbs (5.1 kg)'],
    ],
    features: [
      'High-output dual burners deliver 22,000 total BTUs to rapidly boil water and prepare hot rations in cold weather',
      'Expansive cooking area accommodates both a 12-inch skillet and a 10-inch pot at the same time',
      'Adjustable WindBlock™ side panels deflect crosswinds and fold down to accommodate extra-wide cookware',
      'Independent precision burner knobs provide smooth rotation from gentle simmer to roaring boil',
      'Durable heavy-gauge steel casing features a robust mechanical latch to prevent accidental opening during transit',
      'Removable chrome-plated grate and rust-resistant cooktop allow rapid wipedown after grease and food splatters'
    ],
    page: 1,
    subcategories: ['forestry-camping-safety-climate-products'],
    categoryIds: ['forestry'],
    tags: ['Camping & Field Equipment', 'Camp Cooking & Essentials']
  }
];
